monorepo_root = true

[settings]
idiomatic_version_file_enable_tools = ["pnpm", "rust"]
lockfile = true

[monorepo]
config_roots = [
	"apps/box-agent",
	"apps/control-plane",
	"apps/courier",
	"apps/dispatcher",
	"apps/manager",
	"apps/point",
	"apps/point/app",
]
lockfile = true
