// Build the three token outputs (CSS vars, Tailwind preset, typed TS index)
// from DTCG JSON in src/. Run via `pnpm --filter @petalnet/tokens build`.
//
// style-dictionary v4+ handles DTCG natively. Its config-as-code form lets us
// produce the per-theme CSS + the Tailwind preset + the TS index from one
// graph, sharing the primitive-level transforms.

import fs from "node:fs/promises";
import path from "node:path";

import StyleDictionary from "style-dictionary";

import { renderDaisyThemeCss, toDaisyTheme } from "./daisyui.mts";

const root = path.resolve(import.meta.dirname, "..");

// Flatten a style-dictionary dictionary to the resolved { name: value } map the
// daisyUI generator (and the TS index) consume.
function flatten(dictionary) {
	const flat = {};
	for (const t of dictionary.allTokens) flat[t.name] = t.$value ?? t.value;
	return flat;
}

// Format helpers ----------------------------------------------------------

// CSS custom properties for a specific theme: scope under `[data-theme="..."]`
// so DaisyUI's `@plugin "daisyui/theme"` block can claim them.
StyleDictionary.registerFormat({
	name: "css/theme",
	format: ({ dictionary, options }) => {
		const selector = options.selector ?? ":root";
		const lines = dictionary.allTokens.map((t) => `  --${t.name}: ${t.$value ?? t.value};`);
		return `${selector} {\n${lines.join("\n")}\n}\n`;
	},
});

// Tailwind preset — exports an object slotted into a Tailwind v4 `@theme`
// directive or a v3 config's `theme.extend`. We emit a thin TS module that
// re-shapes the dictionary to Tailwind's expected leaf paths.
StyleDictionary.registerFormat({
	name: "ts/tailwind-preset",
	format: ({ dictionary }) => {
		const out = {
			colors: {},
			spacing: {},
			borderRadius: {},
			fontFamily: {},
			fontSize: {},
			fontWeight: {},
		};
		for (const t of dictionary.allTokens) {
			const [head, ...rest] = t.path;
			const leaf = rest.join("-") || "DEFAULT";
			const val = t.$value ?? t.value;
			if (head === "color")
				(out.colors[rest[0]] ??= {})[rest.slice(1).join("-") || "DEFAULT"] = val;
			else if (head === "space") out.spacing[leaf] = val;
			else if (head === "radius") out.borderRadius[leaf] = val;
			else if (head === "font" && rest[0] === "family")
				out.fontFamily[rest[1]] = Array.isArray(val) ? val : [val];
			else if (head === "font" && rest[0] === "size") out.fontSize[rest[1]] = val;
			else if (head === "font" && rest[0] === "weight") out.fontWeight[rest[1]] = String(val);
		}
		return `// AUTO-GENERATED by tokens/tools/build.mjs — do not edit.\nconst preset = ${JSON.stringify(out, null, 2)} as const;\nexport default preset;\n`;
	},
});

// Typed TS index for the rare non-Tailwind caller.
StyleDictionary.registerFormat({
	name: "ts/index",
	format: ({ dictionary }) => {
		const flat = flatten(dictionary);
		return `// AUTO-GENERATED by tokens/tools/build.mjs — do not edit.\nexport const tokens = ${JSON.stringify(flat, null, 2)} as const;\nexport type TokenName = keyof typeof tokens;\n`;
	},
});

// daisyUI v5 theme block — a `@plugin "daisyui/theme"` CSS file mapped from the
// resolved per-theme leaves. options.daisyName / .daisyOpts come from the
// platform file config so the same format serves both paper + ink.
StyleDictionary.registerFormat({
	name: "css/daisyui-theme",
	format: ({ dictionary, options }) =>
		`/* AUTO-GENERATED by tokens/tools/build.mts — do not edit. */\n${renderDaisyThemeCss(
			options.daisyName,
			toDaisyTheme(flatten(dictionary)),
			options.daisyOpts,
		)}`,
});

// daisyUI theme as a JS object — for callers that want the theme programmatically
// (tooling, theme switchers, Storybook) rather than as a CSS plugin block.
StyleDictionary.registerFormat({
	name: "ts/daisyui-theme",
	format: ({ dictionary }) =>
		`// AUTO-GENERATED by tokens/tools/build.mts — do not edit.\n` +
		`export default ${JSON.stringify(toDaisyTheme(flatten(dictionary)), null, 2)};\n`,
});

// Two themes share the primitives; their semantic layer maps to a CSS-var
// selector keyed by [data-theme] so DaisyUI / Tailwind can swap them at
// runtime without rebuilding.
async function buildTheme(theme) {
	const sd = new StyleDictionary({
		source: [`${root}/src/primitives/*.json`, `${root}/src/semantic/${theme}.json`],
		platforms: {
			css: {
				transformGroup: "css",
				files: [
					{
						destination: `tokens.${theme}.css`,
						format: "css/theme",
						options: {
							selector: theme === "light" ? `:root,[data-theme="light"]` : `[data-theme="dark"]`,
						},
					},
				],
				buildPath: `${root}/dist/`,
			},
		},
	});
	await sd.buildAllPlatforms();
}

// Combined Tailwind preset + TS index from the LIGHT-themed graph (primitives
// + semantic light) — they're shape-identical to dark, just different values
// at the leaf, which we already emit per-theme above.
//
// transformGroup "css" gives kebab-case names like `color-gray-50` so the
// `tokens` map in index.js matches the CSS-var pattern (`--color-gray-50`),
// instead of style-dictionary's default PascalCase. Same key shape both
// outputs => one mental model for callers.
async function buildSharedArtifacts() {
	const sd = new StyleDictionary({
		source: [`${root}/src/primitives/*.json`, `${root}/src/semantic/light.json`],
		platforms: {
			ts: {
				transformGroup: "css",
				files: [
					{ destination: "tailwind.preset.js", format: "ts/tailwind-preset" },
					{ destination: "index.js", format: "ts/index" },
				],
				buildPath: `${root}/dist/`,
			},
		},
	});
	await sd.buildAllPlatforms();
}

// daisyUI v5 themes — `paper` (light, default) and `ink` (dark, prefersdark).
// Each is built from its own resolved graph (primitives + that semantic layer)
// so the theme object carries fully-resolved hex values, not references.
async function buildDaisyTheme(semantic, daisyName, daisyOpts) {
	const sd = new StyleDictionary({
		source: [`${root}/src/primitives/*.json`, `${root}/src/semantic/${semantic}.json`],
		platforms: {
			daisy: {
				transformGroup: "css",
				buildPath: `${root}/dist/`,
				files: [
					{
						destination: `daisyui.${daisyName}.css`,
						format: "css/daisyui-theme",
						options: { daisyName, daisyOpts },
					},
					{
						destination: `daisyui.${daisyName}.js`,
						format: "ts/daisyui-theme",
					},
				],
			},
		},
	});
	await sd.buildAllPlatforms();
}

// Concatenate the two daisyUI theme CSS blocks into one importable file.
async function concatDaisyCss() {
	const paper = await fs.readFile(`${root}/dist/daisyui.paper.css`, "utf8");
	const ink = await fs.readFile(`${root}/dist/daisyui.ink.css`, "utf8");
	await fs.writeFile(
		`${root}/dist/daisyui.css`,
		`/* AUTO-GENERATED — PetalNet daisyUI v5 themes (paper + ink). */\n` +
			`/* Import after \`@plugin "daisyui";\` to register both themes. */\n\n${paper}\n${ink}`,
	);
}

// Concatenate the two CSS theme files into one for consumers who want a
// single `@import "@petalnet/tokens/css"`.
async function concatCss() {
	const light = await fs.readFile(`${root}/dist/tokens.light.css`, "utf8");
	const dark = await fs.readFile(`${root}/dist/tokens.dark.css`, "utf8");
	await fs.writeFile(
		`${root}/dist/tokens.css`,
		`/* AUTO-GENERATED — see tokens/tools/build.mjs */\n\n${light}\n${dark}`,
	);
}

// Type declarations for the JS-output files. Kept hand-written + tiny so we
// don't pay tsc on the generated artifact.
async function writeDts() {
	await fs.writeFile(
		`${root}/dist/tailwind.preset.d.ts`,
		`declare const preset: Record<string, Record<string, string | string[]>>;\nexport default preset;\n`,
	);
	await fs.writeFile(
		`${root}/dist/index.d.ts`,
		`export declare const tokens: Record<string, string | readonly string[]>;\nexport type TokenName = keyof typeof tokens;\n`,
	);
	const daisyDts = `declare const theme: Record<string, string>;\nexport default theme;\n`;
	await fs.writeFile(`${root}/dist/daisyui.paper.d.ts`, daisyDts);
	await fs.writeFile(`${root}/dist/daisyui.ink.d.ts`, daisyDts);
}

// ---------------------------------------------------------------------------

await fs.mkdir(`${root}/dist`, { recursive: true });
await buildTheme("light");
await buildTheme("dark");
await buildSharedArtifacts();
await buildDaisyTheme("light", "paper", { default: true, colorScheme: "light" });
await buildDaisyTheme("dark", "ink", { prefersdark: true, colorScheme: "dark" });
await concatDaisyCss();
await concatCss();
await writeDts();
console.log("✓ tokens built");
