import { operation, type OperationErrors } from "@petalnet/effect-api";
import { Effect } from "effect";

import {
	AttemptPublish,
	ClaimMutationReceipt,
	ClaimReceipt,
	ClaimRelease,
	ClaimRenew,
	ProjectCreate,
	ProjectCreateReceipt,
	ProjectPlan,
	ProjectPlanReceipt,
	PublishReceipt,
	ReadyTasks,
	ReviewReceipt,
	ReviewSubmit,
	TaskClaim,
	TaskComplete,
	TaskCompleteReceipt,
	WorkReady,
	LibrarySearch,
	LibrarySearchResults,
	LibraryGetVersion,
	LibraryVersion,
} from "../../projects/schema";
import { ProjectService, type ProjectError } from "./service";

const errors = {
	ActorDenied: { status: 403, message: (error) => error.message },
	ActorNotCurrent: { status: 403, message: (error) => error.message },
	CommandConflict: { status: 409, message: (error) => error.message },
	FenceConflict: { status: 409, message: (error) => error.message },
	ActorDatabaseError: { status: 503, message: "The project database is unavailable" },
	HomeOwnerUnbound: { status: 503, message: "The project database is unavailable" },
	CapabilityContainmentConflict: { status: 503, message: "The project database is unavailable" },
	ProjectDatabaseError: { status: 503, message: "The project database is unavailable" },
} satisfies OperationErrors<ProjectError>;

export const projectOperations = [
	operation({
		name: "project.create",
		description: "Create a Grove project Task and its initial immutable Version.",
		method: "POST",
		path: "/projects",
		input: ProjectCreate,
		output: ProjectCreateReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.create(input)),
		errors,
	}),
	operation({
		name: "project.plan",
		description: "Accept a bounded child Task DAG.",
		method: "POST",
		path: "/projects/:projectId/plan",
		input: ProjectPlan,
		output: ProjectPlanReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.plan(input)),
		errors,
	}),
	operation({
		name: "task.claim",
		description: "Claim a ready Task and create an Attempt.",
		method: "POST",
		path: "/tasks/:taskId/claims",
		input: TaskClaim,
		output: ClaimReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.claim(input)),
		errors,
	}),
	operation({
		name: "claim.renew",
		description: "Renew an exact fenced Claim.",
		method: "POST",
		path: "/claims/:claimId/renew",
		input: ClaimRenew,
		output: ClaimMutationReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.renew(input)),
		errors,
	}),
	operation({
		name: "claim.release",
		description: "Release an exact fenced Claim.",
		method: "POST",
		path: "/claims/:claimId/release",
		input: ClaimRelease,
		output: ClaimMutationReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.release(input)),
		errors,
	}),
	operation({
		name: "attempt.publish",
		description: "Publish one immutable Attempt output without completing its Task.",
		method: "POST",
		path: "/attempts/:attemptId/outputs",
		input: AttemptPublish,
		output: PublishReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.publish(input)),
		errors,
	}),
	operation({
		name: "work.ready",
		description: "List ready Project Tasks in deterministic dependency order.",
		method: "GET",
		path: "/projects/:projectId/work/ready",
		input: WorkReady,
		output: ReadyTasks,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.ready(input)),
		errors,
	}),
	operation({
		name: "review.submit",
		description: "Independently review an exact submitted artifact Version.",
		method: "POST",
		path: "/reviews",
		input: ReviewSubmit,
		output: ReviewReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.review(input)),
		errors,
	}),
	operation({
		name: "task.complete",
		description: "Complete an exact Task Version under its reviewed-output contract.",
		method: "POST",
		path: "/tasks/:taskId/complete",
		input: TaskComplete,
		output: TaskCompleteReceipt,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.complete(input)),
		errors,
	}),
	operation({
		name: "library.search",
		description: "Search accepted completed Project artifacts.",
		method: "GET",
		path: "/library/search",
		input: LibrarySearch,
		output: LibrarySearchResults,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.search(input)),
		errors,
	}),
	operation({
		name: "library.getVersion",
		description: "Retrieve an exact accepted artifact Version with stable citations.",
		method: "GET",
		path: "/library/objects/:objectId/versions/:versionId",
		input: LibraryGetVersion,
		output: LibraryVersion,
		handler: (input) => Effect.flatMap(ProjectService, (service) => service.getVersion(input)),
		errors,
	}),
] as const;
