// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/recovery.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -779931484;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'point_mls',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AddMemberResult> crateApiCryptoPointMlsAddMember({
    required PointMls that,
    required List<int> groupId,
    required List<int> keyPackage,
  });

  Future<Uint8List> crateApiCryptoPointMlsCreateGroup({
    required PointMls that,
    required List<int> groupId,
  });

  Future<Uint8List> crateApiCryptoPointMlsDecrypt({
    required PointMls that,
    required List<int> groupId,
    required List<int> ciphertext,
  });

  Future<Uint8List> crateApiCryptoPointMlsEncrypt({
    required PointMls that,
    required List<int> groupId,
    required List<int> plaintext,
  });

  Future<Uint8List> crateApiCryptoPointMlsExportState({required PointMls that});

  Future<Uint8List> crateApiCryptoPointMlsGenerateKeyPackage({
    required PointMls that,
  });

  bool crateApiCryptoPointMlsHasGroup({
    required PointMls that,
    required List<int> groupId,
  });

  PointMls crateApiCryptoPointMlsNew({required String identity});

  Future<void> crateApiCryptoPointMlsProcessCommit({
    required PointMls that,
    required List<int> groupId,
    required List<int> commit,
  });

  Future<Uint8List> crateApiCryptoPointMlsProcessWelcome({
    required PointMls that,
    required List<int> welcome,
  });

  PointMls crateApiCryptoPointMlsRestore({required List<int> state});

  String crateApiRecoveryGenerateRecoveryCode();

  Uint8List crateApiRecoveryRecoveryDecrypt({
    required List<int> blob,
    required String recoveryCode,
  });

  Uint8List crateApiRecoveryRecoveryEncrypt({
    required List<int> state,
    required String recoveryCode,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PointMls;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PointMls;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PointMlsPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AddMemberResult> crateApiCryptoPointMlsAddMember({
    required PointMls that,
    required List<int> groupId,
    required List<int> keyPackage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(keyPackage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_add_member_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsAddMemberConstMeta,
        argValues: [that, groupId, keyPackage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsAddMemberConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_add_member",
        argNames: ["that", "groupId", "keyPackage"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointMlsCreateGroup({
    required PointMls that,
    required List<int> groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsCreateGroupConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsCreateGroupConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_create_group",
        argNames: ["that", "groupId"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointMlsDecrypt({
    required PointMls that,
    required List<int> groupId,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsDecryptConstMeta,
        argValues: [that, groupId, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_decrypt",
        argNames: ["that", "groupId", "ciphertext"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointMlsEncrypt({
    required PointMls that,
    required List<int> groupId,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsEncryptConstMeta,
        argValues: [that, groupId, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_encrypt",
        argNames: ["that", "groupId", "plaintext"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointMlsExportState({
    required PointMls that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsExportStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsExportStateConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_export_state",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointMlsGenerateKeyPackage({
    required PointMls that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsGenerateKeyPackageConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsGenerateKeyPackageConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_generate_key_package",
        argNames: ["that"],
      );

  @override
  bool crateApiCryptoPointMlsHasGroup({
    required PointMls that,
    required List<int> groupId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoPointMlsHasGroupConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsHasGroupConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_has_group",
        argNames: ["that", "groupId"],
      );

  @override
  PointMls crateApiCryptoPointMlsNew({required String identity}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(identity, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsNewConstMeta,
        argValues: [identity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsNewConstMeta => const TaskConstMeta(
    debugName: "PointMls_new",
    argNames: ["identity"],
  );

  @override
  Future<void> crateApiCryptoPointMlsProcessCommit({
    required PointMls that,
    required List<int> groupId,
    required List<int> commit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(commit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsProcessCommitConstMeta,
        argValues: [that, groupId, commit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsProcessCommitConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_process_commit",
        argNames: ["that", "groupId", "commit"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointMlsProcessWelcome({
    required PointMls that,
    required List<int> welcome,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(welcome, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsProcessWelcomeConstMeta,
        argValues: [that, welcome],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsProcessWelcomeConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_process_welcome",
        argNames: ["that", "welcome"],
      );

  @override
  PointMls crateApiCryptoPointMlsRestore({required List<int> state}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(state, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCryptoPointMlsRestoreConstMeta,
        argValues: [state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointMlsRestoreConstMeta =>
      const TaskConstMeta(
        debugName: "PointMls_restore",
        argNames: ["state"],
      );

  @override
  String crateApiRecoveryGenerateRecoveryCode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRecoveryGenerateRecoveryCodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryGenerateRecoveryCodeConstMeta =>
      const TaskConstMeta(
        debugName: "generate_recovery_code",
        argNames: [],
      );

  @override
  Uint8List crateApiRecoveryRecoveryDecrypt({
    required List<int> blob,
    required String recoveryCode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(blob, serializer);
          sse_encode_String(recoveryCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRecoveryRecoveryDecryptConstMeta,
        argValues: [blob, recoveryCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryRecoveryDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "recovery_decrypt",
        argNames: ["blob", "recoveryCode"],
      );

  @override
  Uint8List crateApiRecoveryRecoveryEncrypt({
    required List<int> state,
    required String recoveryCode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(state, serializer);
          sse_encode_String(recoveryCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRecoveryRecoveryEncryptConstMeta,
        argValues: [state, recoveryCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryRecoveryEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "recovery_encrypt",
        argNames: ["state", "recoveryCode"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PointMls => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PointMls => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls;

  @protected
  PointMls
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointMlsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PointMls
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointMlsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PointMls
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointMlsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddMemberResult dco_decode_add_member_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AddMemberResult(
      welcome: dco_decode_list_prim_u_8_strict(arr[0]),
      commit: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  PointMls
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointMlsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PointMls
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointMlsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PointMls
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointMlsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddMemberResult sse_decode_add_member_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_welcome = sse_decode_list_prim_u_8_strict(deserializer);
    var var_commit = sse_decode_list_prim_u_8_strict(deserializer);
    return AddMemberResult(welcome: var_welcome, commit: var_commit);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    PointMls self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointMlsImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    PointMls self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointMlsImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointMls(
    PointMls self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointMlsImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_add_member_result(
    AddMemberResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.welcome, serializer);
    sse_encode_list_prim_u_8_strict(self.commit, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class PointMlsImpl extends RustOpaque implements PointMls {
  // Not to be used by end users
  PointMlsImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PointMlsImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PointMls,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PointMls,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PointMlsPtr,
  );

  Future<AddMemberResult> addMember({
    required List<int> groupId,
    required List<int> keyPackage,
  }) => RustLib.instance.api.crateApiCryptoPointMlsAddMember(
    that: this,
    groupId: groupId,
    keyPackage: keyPackage,
  );

  Future<Uint8List> createGroup({required List<int> groupId}) => RustLib
      .instance
      .api
      .crateApiCryptoPointMlsCreateGroup(that: this, groupId: groupId);

  /// Decrypt a group ciphertext back to plaintext.
  Future<Uint8List> decrypt({
    required List<int> groupId,
    required List<int> ciphertext,
  }) => RustLib.instance.api.crateApiCryptoPointMlsDecrypt(
    that: this,
    groupId: groupId,
    ciphertext: ciphertext,
  );

  /// Encrypt a location fix for a group. Returns opaque MLS ciphertext.
  Future<Uint8List> encrypt({
    required List<int> groupId,
    required List<int> plaintext,
  }) => RustLib.instance.api.crateApiCryptoPointMlsEncrypt(
    that: this,
    groupId: groupId,
    plaintext: plaintext,
  );

  /// Serialize the full MLS state for durable storage. Call after every
  /// mutation (create_group, add_member, process_welcome, process_commit).
  Future<Uint8List> exportState() =>
      RustLib.instance.api.crateApiCryptoPointMlsExportState(
        that: this,
      );

  /// A fresh one-time KeyPackage to upload to the server pool.
  Future<Uint8List> generateKeyPackage() =>
      RustLib.instance.api.crateApiCryptoPointMlsGenerateKeyPackage(
        that: this,
      );

  bool hasGroup({required List<int> groupId}) => RustLib.instance.api
      .crateApiCryptoPointMlsHasGroup(that: this, groupId: groupId);

  /// Apply a Commit (membership change) to an existing group.
  Future<void> processCommit({
    required List<int> groupId,
    required List<int> commit,
  }) => RustLib.instance.api.crateApiCryptoPointMlsProcessCommit(
    that: this,
    groupId: groupId,
    commit: commit,
  );

  /// Join a group from a Welcome; returns the group id.
  Future<Uint8List> processWelcome({required List<int> welcome}) => RustLib
      .instance
      .api
      .crateApiCryptoPointMlsProcessWelcome(that: this, welcome: welcome);
}
