// The ordered security migration (contract §3, PHASE1-DESIGN §3). ONE ordered path, no window:
// roles → tables → RLS enable+force + policy → RO role REVOKE then GRANT SELECT → security_invoker
// views. Idempotent (guarded CREATEs) so it is safe to run at every boot and in tests.
//
// Runs as the admin/owner role. The runtime then connects as console_app / console_ro.

import type { Sql } from "./pool.ts";

// L1 uses Timescale hypertables. Global UUID dedup lives in the plain `emission_ids` gate because
// Timescale unique indexes must contain the time partition column.
const STATEMENTS: readonly string[] = [
	`create extension if not exists timescaledb cascade`,

	// --- runtime roles (cluster-global; all NOSUPERUSER NOBYPASSRLS so RLS actually binds) -----
	//   console_app    — caller-scoped reads (RLS filters to app.scopes)
	//   console_ro     — read-only SQL mode
	//   console_writer — the appender: inserts any scope + sees all rows (for dedup), NOT superuser
	`do $$ begin
	   if not exists (select 1 from pg_roles where rolname = 'console_app') then
	     create role console_app nologin nosuperuser nobypassrls;
	   end if;
	   if not exists (select 1 from pg_roles where rolname = 'console_ro') then
	     create role console_ro nologin nosuperuser nobypassrls;
	   end if;
	   if not exists (select 1 from pg_roles where rolname = 'console_writer') then
	     create role console_writer nologin nosuperuser nobypassrls;
	   end if;
	 end $$`,

	// --- events: the lake. seq is commit-ordered by the serialized appender. ------------------
	`create table if not exists events (
	   seq            bigint generated always as identity primary key,
	   id             uuid not null unique,
	   type           text not null,
	   ts             timestamptz not null,
	   received_at    timestamptz not null default now(),
	   source_service text not null,
	   source_host    text,
	   source_agent   text,
	   subject        text not null,
	   subject_kind   text,
	   severity       text not null,
	   action         text,
	   task_id        bigint,
	   scope          text not null,
	   dimensions     jsonb not null default '{}'::jsonb,
	   measures       jsonb not null default '{}'::jsonb,
	   links          jsonb not null default '[]'::jsonb,
	   body_ref       text,
	   meta           jsonb not null default '{}'::jsonb
	 )`,
	`create index if not exists events_type_received_idx on events (type, received_at desc)`,
	`create index if not exists events_subject_idx on events (subject)`,
	`create index if not exists events_scope_idx on events (scope)`,

	// --- L1 production lake: global id gate + Timescale storage -------------------------------
	// A hypertable cannot keep a UNIQUE(id) that omits its time partition key. Keep the global,
	// durable idempotency decision in a plain table and make seq there; events receives that exact
	// seq+receipt pair in the same transaction.
	`create table if not exists emission_ids (
	   id          uuid primary key,
	   seq         bigint generated by default as identity unique,
	   received_at timestamptz not null default clock_timestamp()
	 )`,
	`create table if not exists schema_migrations (
	   name       text primary key,
	   applied_at timestamptz not null default now()
	 )`,
	// Phase-1 may still be serving while deploy migrations start. Take the lock before the snapshot
	// backfill and hold it through conversion so no old writer can commit an ungated UUID/seq.
	`lock table events in access exclusive mode`,
	`insert into emission_ids (id, seq, received_at)
	 select id, seq, received_at from events
	 on conflict (id) do nothing`,
	`select setval(
	   pg_get_serial_sequence('emission_ids', 'seq'),
	   greatest(coalesce((select max(seq) from emission_ids), 1), 1),
	   exists(select 1 from emission_ids)
	 )`,
	`alter table if exists edges drop constraint if exists edges_seq_fkey`,
	`do $$ begin
	   if exists (
	     select 1 from pg_attribute
	     where attrelid = 'events'::regclass and attname = 'seq' and attidentity <> ''
	   ) then
	     alter table events alter column seq drop identity;
	   end if;
	 end $$`,
	`alter table events drop constraint if exists events_pkey`,
	`alter table events drop constraint if exists events_id_key`,
	`do $$ begin
	   if not exists (
	     select 1 from pg_constraint where conrelid = 'events'::regclass and conname = 'events_time_seq_pk'
	   ) then
	     alter table events add constraint events_time_seq_pk primary key (received_at, seq);
	   end if;
	 end $$`,
	`create index if not exists events_id_idx on events (id)`,
	`select create_hypertable('events', by_range('received_at'), if_not_exists => true, migrate_data => true)`,

	// Long-retention contractual classes are copied atomically at append time. The raw table can
	// retain 30d without erasing audit/terminal/edge/security history, while normal reads union the
	// archive only after the raw copy has disappeared.
	`create table if not exists event_archive (
	   seq            bigint not null,
	   id             uuid not null,
	   type           text not null,
	   ts             timestamptz not null,
	   received_at    timestamptz not null,
	   source_service text not null,
	   source_host    text,
	   source_agent   text,
	   subject        text not null,
	   subject_kind   text,
	   severity       text not null,
	   action         text,
	   task_id        bigint,
	   scope          text not null,
	   dimensions     jsonb not null default '{}'::jsonb,
	   measures       jsonb not null default '{}'::jsonb,
	   links          jsonb not null default '[]'::jsonb,
	   body_ref       text,
	   meta           jsonb not null default '{}'::jsonb,
	   primary key (received_at, seq)
	 )`,
	`create index if not exists event_archive_id_idx on event_archive (id)`,
	`create index if not exists event_archive_type_received_idx on event_archive (type, received_at desc)`,
	`create index if not exists event_archive_scope_idx on event_archive (scope)`,
	`select create_hypertable('event_archive', by_range('received_at'), if_not_exists => true, migrate_data => true)`,
	`insert into event_archive
	   (seq, id, type, ts, received_at, source_service, source_host, source_agent, subject,
	    subject_kind, severity, action, task_id, scope, dimensions, measures, links, body_ref, meta)
	 select seq, id, type, ts, received_at, source_service, source_host, source_agent, subject,
	        subject_kind, severity, action, task_id, scope, dimensions, measures, links, body_ref, meta
	 from events
	 where type like 'audit.%' or type like 'term.%' or type like 'edge.%'
	    or type like 'security.%' or meta->>'retention_class' = 'audit'
	 on conflict (received_at, seq) do nothing`,
	`create or replace view lake_events with (security_invoker = true) as
	 select * from events
	 union all
	 select a.* from event_archive a
	 where not exists (
	   select 1 from events e where e.received_at = a.received_at and e.seq = a.seq
	 )`,
	// Continuous aggregates cannot be defined over an RLS-enabled hypertable. The disable/create/
	// re-enable sequence is inside this one transaction, so no caller can observe an unprotected lake.
	`alter table events no force row level security`,
	`alter table events disable row level security`,
	`create materialized view if not exists event_rollup_1m
	 with (timescaledb.continuous) as
	 select time_bucket('1 minute', received_at) as bucket,
	        type, scope, severity, count(*)::bigint as event_count
	 from events
	 group by bucket, type, scope, severity
	 with no data`,
	// Raw retention is deliberately one ordered job, not an independent Timescale retention policy:
	// after downtime it refreshes every still-raw bucket before dropping any old chunk.
	`create or replace procedure console_events_refresh_then_retain(job_id int, config jsonb)
	 language plpgsql as $$
	 declare refresh_start timestamptz;
	 begin
	   select time_bucket('1 minute', min(received_at)) into refresh_start from events;
	   if refresh_start is not null and refresh_start < now() - interval '1 minute' then
	     call refresh_continuous_aggregate(
	       'event_rollup_1m', refresh_start, now() - interval '1 minute'
	     );
	   end if;
	   perform drop_chunks('events', older_than => now() - interval '30 days');
	 end $$`,

	// edges materialized from links at ingest (graphing design §04): "why?" is a graph walk.
	`create table if not exists edges (
	   id        bigint generated always as identity primary key,
	   from_kind text not null,
	   from_id   text not null,
	   rel       text not null,
	   to_kind   text not null,
	   to_id     text not null,
	   scope     text not null,
	   seq       bigint not null references emission_ids(seq)
	 )`,
	`create index if not exists edges_from_idx on edges (from_kind, from_id)`,
	`create index if not exists edges_to_idx on edges (to_kind, to_id)`,
	`do $$ begin
	   if not exists (
	     select 1 from pg_constraint where conrelid = 'edges'::regclass and conname = 'edges_seq_fkey'
	   ) then
	     alter table edges add constraint edges_seq_fkey foreign key (seq) references emission_ids(seq);
	   end if;
	 end $$`,

	// blobs: body_ref payloads, scope-checked on fetch by the same RLS as events.
	`create table if not exists blobs (
	   id         text primary key,
	   scope      text not null,
	   bytes      bytea not null,
	   created_at timestamptz not null default now()
	 )`,

	// semantic registry: auto-registered statistic types (L2 input).
	`create table if not exists semantic_registry (
	   type        text primary key,
	   first_seen  timestamptz not null default now(),
	   last_emit   timestamptz,
	   dimensions  jsonb not null default '{}'::jsonb,
	   measures    jsonb not null default '{}'::jsonb,
	   scopes      jsonb not null default '[]'::jsonb,
	   emit_count  bigint not null default 0
	 )`,

	// producer registrations: the emit-authz allow-lists (contract §4.3), seeded out of band.
	`create table if not exists producer_registrations (
	   subject          text primary key,
	   allowed_services jsonb not null default '[]'::jsonb,
	   allowed_prefixes jsonb not null default '[]'::jsonb,
	   allowed_scopes   jsonb not null default '[]'::jsonb,
	   max_severity     text not null default 'info'
	 )`,

	// bearer verification (sha256 only; the vault keeps plaintext for re-issue, CP4).
	`create table if not exists api_tokens (
	   token_sha256 text primary key,
	   subject      text not null,
	   kind         text not null,
	   tiers        jsonb not null default '[]'::jsonb,
	   lanes        jsonb not null default '[]'::jsonb,
	   created_at   timestamptz not null default now(),
	   revoked_at   timestamptz
	 )`,

	// ReBAC grants (contract §7.2).
	`create table if not exists grants (
	   id         bigint generated always as identity primary key,
	   subject    text not null,
	   relation   text not null,
	   object     text not null,
	   condition  text,
	   valid_at   timestamptz not null default now(),
	   invalid_at timestamptz,
	   granted_by text not null,
	   zookie     bigint not null default 1
	 )`,
	`create index if not exists grants_subject_idx on grants (subject)`,

	`create table if not exists tiers (
	   name            text primary key,
	   authentik_group text,
	   propose_only    boolean not null default false
	 )`,

	// --- N1b: current-state projection (latest per entity), keyed by the PROJECTION bucket -----
	// kind is the projection-map target (fleet|heartbeat|registry|governance|card|worker|
	// box_update|edge), NOT the emission subject_kind (which is `agent` for four of them).
	`create table if not exists current_state (
	   kind              text not null,
	   subject           text not null,
	   scope             text not null,
	   state             jsonb not null,
	   observed_at       timestamptz not null,
	   producer_ts       timestamptz,
	   unreachable_since timestamptz,
	   seq               bigint not null,
	   primary key (kind, subject)
	 )`,

	// projector durability: the seq up to which current_state reflects the lake.
	`create table if not exists projection_checkpoint (
	   name         text primary key,
	   through_seq  bigint not null default 0,
	   updated_at   timestamptz not null default now()
	 )`,

	// bridge cursors: the high-water mark a co-located bridge has ingested per source (durable so a
	// restart resumes; deterministic emission ids make re-processing safe regardless).
	`create table if not exists bridge_cursor (
	   source      text primary key,
		   cursor      text not null default '',
		   below_count integer not null default 0,
		   below_hash  text not null default '',
		   updated_at  timestamptz not null default now()
		 )`,
	`alter table bridge_cursor add column if not exists below_hash text not null default ''`,

	`create table if not exists bridge_dead_letter (
		   source          text not null,
		   source_cursor   text not null,
		   emission_id     text,
		   error_code      text not null,
		   quarantined_at  timestamptz not null default now(),
		   primary key (source, source_cursor)
		 )`,

	// executor signing keys: completions are executor-SIGNED, verified here; the bridge is relay-only.
	`create table if not exists executor_keys (
	   executor    text primary key,
	   algorithm   text not null default 'ed25519',
	   public_key  text not null,
	   created_at  timestamptz not null default now(),
	   revoked_at  timestamptz
	 )`,

	// minimal Library items table (dashboards/artifacts projection) — Phase-1 wire surface.
	`create table if not exists items_min (
	   id                 text primary key,
	   kind               text not null,
	   title              text not null,
	   scope              text not null,
	   is_home            boolean not null default false,
	   created_by         text,
	   responsible_human  text,
	   payload            jsonb not null default '{}'::jsonb,
	   updated_at         timestamptz not null default now()
	 )`,

	// --- RLS: enable + force on every scoped base table, then the policy ----------------------
	`alter table current_state enable row level security`,
	`alter table current_state force row level security`,
	`alter table items_min enable row level security`,
	`alter table items_min force row level security`,
	`alter table events enable row level security`,
	`alter table events force row level security`,
	`alter table event_archive enable row level security`,
	`alter table event_archive force row level security`,
	`alter table edges enable row level security`,
	`alter table edges force row level security`,
	`alter table blobs enable row level security`,
	`alter table blobs force row level security`,

	// SELECT policy: a caller sees a row iff its scope is in the per-transaction app.scopes GUC.
	// Unset GUC → string_to_array(NULL,',') → NULL → scope = ANY(NULL) → NULL → row excluded
	// (fail-closed). console_writer (the appender) sees ALL rows so dedup can find any id, and may
	// INSERT any scope — scope authorization already happened at the emit door; the durable scope
	// tag is what caller reads filter on.
	`do $$ begin
	   if not exists (select 1 from pg_policies where tablename='events' and policyname='events_scope_select') then
	     create policy events_scope_select on events for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='events' and policyname='events_writer_all') then
	     create policy events_writer_all on events to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='event_archive' and policyname='event_archive_scope_select') then
	     create policy event_archive_scope_select on event_archive for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='event_archive' and policyname='event_archive_writer_all') then
	     create policy event_archive_writer_all on event_archive to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='edges' and policyname='edges_scope_select') then
	     create policy edges_scope_select on edges for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='edges' and policyname='edges_writer_all') then
	     create policy edges_writer_all on edges to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='blobs' and policyname='blobs_scope_select') then
	     create policy blobs_scope_select on blobs for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='blobs' and policyname='blobs_writer_all') then
	     create policy blobs_writer_all on blobs to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='current_state' and policyname='current_state_scope_select') then
	     create policy current_state_scope_select on current_state for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='current_state' and policyname='current_state_writer_all') then
	     create policy current_state_writer_all on current_state to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='items_min' and policyname='items_min_scope_select') then
	     create policy items_min_scope_select on items_min for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='items_min' and policyname='items_min_writer_all') then
	     create policy items_min_writer_all on items_min to console_writer using (true) with check (true);
	   end if;
	 end $$`,

	// --- grants -------------------------------------------------------------------------------
	`revoke all on all tables in schema public from console_ro`,
	`grant usage on schema public to console_app, console_ro, console_writer`,
	`grant select on events, event_archive, lake_events, current_state, items_min to console_ro`,
	// console_app: scoped reads across the read surface.
	`grant select on events, event_archive, lake_events, edges, blobs, current_state, items_min, semantic_registry, grants, producer_registrations, tiers, api_tokens, executor_keys to console_app`,
	`grant insert, update, select on semantic_registry to console_app, console_writer`,
	// console_writer: the appender + projector (non-superuser) — insert events/edges/blobs, upsert current_state.
	`grant insert, select on emission_ids, events, event_archive, edges, blobs to console_writer`,
	`grant usage, select on sequence emission_ids_seq_seq to console_writer`,
	`grant insert, update, select, delete on current_state, items_min to console_writer`,
	`grant insert, update, select on projection_checkpoint to console_writer`,
	`grant insert, update, select on bridge_cursor to console_writer`,
	`grant insert, select on bridge_dead_letter to console_writer`,
];

// Timescale forbids populating a continuous aggregate inside a transaction. These steps are
// additive, ordered, and resumable after the atomic schema transition above: retention is installed
// only after archive backfill and a full historical rollup refresh succeed.
const POST_COMMIT_STATEMENTS: readonly string[] = [
	`select add_continuous_aggregate_policy('event_rollup_1m',
	   start_offset => interval '29 days', end_offset => interval '1 minute',
	   schedule_interval => interval '1 minute', if_not_exists => true)`,
	`select remove_retention_policy('events', if_exists => true)`,
	`do $$ begin
	   if not exists (
	     select 1 from timescaledb_information.jobs
	     where proc_schema = 'public' and proc_name = 'console_events_refresh_then_retain'
	   ) then
	     perform add_job('public.console_events_refresh_then_retain', interval '1 day');
	   end if;
	 end $$`,
	`select add_retention_policy('event_archive', interval '370 days', if_not_exists => true)`,
	`select add_retention_policy('event_rollup_1m', interval '370 days', if_not_exists => true)`,
];

export interface MigrateOpts {
	/**
	 * When set, grant LOGIN + this password to console_app (dev/test convenience; prod uses a managed
	 * role).
	 */
	readonly appPassword?: string;
	readonly roPassword?: string;
	readonly writerPassword?: string;
}

export async function migrate(admin: Sql, opts?: MigrateOpts): Promise<void> {
	// One atomic schema transition: a failed hypertable conversion cannot strand a populated Phase 1
	// database after its old uniqueness/identity constraints have been removed.
	await admin.begin(async (tx) => {
		for (const stmt of STATEMENTS) await tx.unsafe(stmt);
	});
	const rollupBackfill = await admin<{ done: boolean }[]>`
		select exists(select 1 from schema_migrations where name = 'l1_rollup_backfill') as done`;
	if (!rollupBackfill[0]?.done) {
		await admin.unsafe(
			`call refresh_continuous_aggregate('event_rollup_1m', null, now() - interval '1 minute')`,
		);
		await admin`
			insert into schema_migrations (name) values ('l1_rollup_backfill') on conflict do nothing`;
	}
	for (const stmt of POST_COMMIT_STATEMENTS) await admin.unsafe(stmt);
	if (opts?.appPassword)
		await admin.unsafe(
			`alter role console_app login password '${opts.appPassword.replace(/'/g, "''")}'`,
		);
	if (opts?.roPassword)
		await admin.unsafe(
			`alter role console_ro login password '${opts.roPassword.replace(/'/g, "''")}'`,
		);
	if (opts?.writerPassword)
		await admin.unsafe(
			`alter role console_writer login password '${opts.writerPassword.replace(/'/g, "''")}'`,
		);
}
