/**
 * GENERATED by scripts/generate-contracts.mjs from console-api/docs/contracts/ops.json.
 * Wire metadata and argument schemas are canonical; only button verbs are UI-owned.
 */
/* oxlint-disable unicorn/no-thenable -- JSON Schema's conditional keyword is named then. */
import type { Lane } from "./types";

type JsonSchema = Record<string, unknown> & {
	type?: string | string[];
	const?: unknown;
	enum?: unknown[];
	allOf?: SchemaNode[];
	oneOf?: SchemaNode[];
	anyOf?: SchemaNode[];
	properties?: Record<string, SchemaNode>;
	required?: string[];
	additionalProperties?: SchemaNode;
	items?: SchemaNode;
	pattern?: string;
	minLength?: number;
	maxLength?: number;
	minimum?: number;
	maximum?: number;
	minItems?: number;
	maxItems?: number;
};
type SchemaNode = JsonSchema | boolean;
export type ConfirmKind = "none" | "soft" | "hard";
export type OpName = "attention.ack" | "attention.snooze" | "attention.resolve" | "task.get_ready" | "task.up_next" | "task.claim" | "task.update" | "task.close" | "task.dispatch" | "agent.start" | "agent.stop" | "agent.restart" | "agent.kill_session" | "agent.autonomy" | "governance.action" | "governance.tier" | "fleet.mode" | "channel.reclaim" | "signal.snooze" | "signal.source_mode" | "subscription.set" | "subscription.remove" | "card.repost" | "card.park" | "stats.query" | "viz.render" | "text.surface" | "window.arrange" | "dashboard.save" | "dashboard.load" | "dashboard.set_home" | "dashboard.pin" | "dashboard.delete" | "dashboard.share" | "context.receive" | "kb.search" | "kb.research" | "library.item.create" | "library.item.update" | "library.capability.propose" | "library.capability.review" | "library.link.add" | "library.hold" | "curation.propose" | "curation.approve" | "curation.reject" | "item.weed" | "item.merge" | "item.delete" | "promotion.request" | "promotion.approve" | "service.restart" | "service.stop" | "service.logs" | "host.probe" | "host.reboot" | "updates.check" | "updates.approve" | "updates.revoke" | "updates.apply" | "edge.enroll.approve" | "edge.enroll.deny" | "edge.key.revoke" | "doorman.session.drop" | "doorman.redial" | "term.watch" | "term.attach" | "term.input" | "term.resize" | "term.scrollback" | "term.detach" | "delivery.test" | "delivery.set_target" | "delivery.resend" | "delivery.cocoon";
export interface OpDef {
	op: OpName; verb: string; lane: Lane; executor: string; confirm: ConfirmKind;
	undo: boolean; humanOnly: boolean; args: JsonSchema;
}

const OPS = {
	"attention.ack": {
		"op": "attention.ack",
		"verb": "Ack",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"attention.snooze": {
		"op": "attention.snooze",
		"verb": "Snooze",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				},
				"duration_s": {
					"type": "integer",
					"minimum": 60,
					"maximum": 604800
				},
				"restore": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		}
	},
	"attention.resolve": {
		"op": "attention.resolve",
		"verb": "Done",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"task.get_ready": {
		"op": "task.get_ready",
		"verb": "Get ready",
		"lane": "viewer",
		"executor": "tracker",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"properties": {
				"capability": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"task.up_next": {
		"op": "task.up_next",
		"verb": "Up next",
		"lane": "operator",
		"executor": "tracker",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "integer"
				},
				"position": {
					"type": "integer",
					"minimum": 0
				}
			},
			"additionalProperties": false
		}
	},
	"task.claim": {
		"op": "task.claim",
		"verb": "Claim",
		"lane": "operator",
		"executor": "tracker",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"capability": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"task.update": {
		"op": "task.update",
		"verb": "Update",
		"lane": "operator",
		"executor": "tracker",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id",
				"patch"
			],
			"properties": {
				"id": {
					"type": "integer"
				},
				"patch": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"status": {
							"enum": [
								"inbox",
								"todo",
								"doing",
								"blocked",
								"review",
								"done",
								"dropped"
							]
						},
						"priority": {
							"type": "integer",
							"minimum": 0,
							"maximum": 3
						},
						"title": {
							"type": "string"
						},
						"body": {
							"type": "string"
						},
						"assignee": {
							"type": "string"
						},
						"blocked_on": {
							"type": [
								"string",
								"null"
							]
						},
						"verification_status": {
							"enum": [
								"unverified",
								"verified",
								"rejected"
							]
						},
						"rank": {
							"type": "number"
						},
						"up_next": {
							"type": "boolean"
						}
					}
				},
				"lease": {
					"type": "object",
					"required": [
						"fence",
						"claim_token"
					],
					"properties": {
						"fence": {
							"type": "integer"
						},
						"claim_token": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"force": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		}
	},
	"task.close": {
		"op": "task.close",
		"verb": "Close",
		"lane": "operator",
		"executor": "tracker",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id",
				"status",
				"reason"
			],
			"properties": {
				"id": {
					"type": "integer"
				},
				"status": {
					"enum": [
						"done",
						"dropped"
					]
				},
				"reason": {
					"type": "string",
					"minLength": 1,
					"maxLength": 2000
				},
				"lease": {
					"type": "object",
					"required": [
						"fence",
						"claim_token"
					],
					"properties": {
						"fence": {
							"type": "integer"
						},
						"claim_token": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"force": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		}
	},
	"task.dispatch": {
		"op": "task.dispatch",
		"verb": "Dispatch",
		"lane": "operator",
		"executor": "dispatcher",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"body"
			],
			"properties": {
				"task_id": {
					"type": "integer"
				},
				"recipient": {
					"type": "string"
				},
				"body": {
					"type": "string",
					"maxLength": 65536
				},
				"priority": {
					"type": "integer",
					"minimum": 0,
					"maximum": 3
				},
				"needs": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"interrupt_policy": {
					"enum": [
						"defer",
						"principal_command",
						"safety",
						"task_clarification"
					]
				},
				"thread": {
					"type": "string"
				},
				"requires_reply": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		}
	},
	"agent.start": {
		"op": "agent.start",
		"verb": "Start",
		"lane": "operator",
		"executor": "manager",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				}
			},
			"additionalProperties": false
		}
	},
	"agent.stop": {
		"op": "agent.stop",
		"verb": "Stop",
		"lane": "operator",
		"executor": "manager",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				}
			},
			"additionalProperties": false
		}
	},
	"agent.restart": {
		"op": "agent.restart",
		"verb": "Restart",
		"lane": "operator",
		"executor": "manager",
		"confirm": "soft",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				}
			},
			"additionalProperties": false
		}
	},
	"agent.kill_session": {
		"op": "agent.kill_session",
		"verb": "Kill session",
		"lane": "admin",
		"executor": "manager",
		"confirm": "hard",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle",
				"confirm_name"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				},
				"confirm_name": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"agent.autonomy": {
		"op": "agent.autonomy",
		"verb": "Autonomy",
		"lane": "operator",
		"executor": "tracker",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle",
				"autonomy"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				},
				"autonomy": {
					"enum": [
						"auto",
						"ask",
						"readonly",
						"paused"
					]
				}
			},
			"additionalProperties": false
		}
	},
	"governance.action": {
		"op": "governance.action",
		"verb": "Pause",
		"lane": "operator",
		"executor": "control-plane",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle",
				"action"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				},
				"action": {
					"enum": [
						"pause",
						"throttle",
						"downgrade",
						"restore"
					]
				},
				"delay_ms": {
					"type": "integer",
					"minimum": 0,
					"maximum": 600000
				},
				"to": {
					"enum": [
						"haiku",
						"sonnet",
						"opus"
					]
				}
			},
			"additionalProperties": false
		}
	},
	"governance.tier": {
		"op": "governance.tier",
		"verb": "Tier",
		"lane": "operator",
		"executor": "control-plane",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle",
				"tier"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				},
				"tier": {
					"enum": [
						"haiku",
						"sonnet",
						"opus"
					]
				}
			},
			"additionalProperties": false
		}
	},
	"fleet.mode": {
		"op": "fleet.mode",
		"verb": "Mode",
		"lane": "operator",
		"executor": "control-plane",
		"confirm": "soft",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"mode"
			],
			"properties": {
				"mode": {
					"enum": [
						"parallel",
						"sequential"
					]
				}
			},
			"additionalProperties": false
		}
	},
	"channel.reclaim": {
		"op": "channel.reclaim",
		"verb": "Reclaim",
		"lane": "admin",
		"executor": "manager",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				}
			},
			"additionalProperties": false
		}
	},
	"signal.snooze": {
		"op": "signal.snooze",
		"verb": "Quiet 1h",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"type_pattern"
			],
			"properties": {
				"type_pattern": {
					"type": "string"
				},
				"duration_s": {
					"type": "integer",
					"minimum": 60,
					"maximum": 86400
				}
			},
			"additionalProperties": false
		}
	},
	"signal.source_mode": {
		"op": "signal.source_mode",
		"verb": "Source mode",
		"lane": "operator",
		"executor": "console-api",
		"confirm": "none",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"source_service",
				"mode"
			],
			"properties": {
				"source_service": {
					"type": "string",
					"pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
				},
				"mode": {
					"enum": [
						"normal",
						"development"
					]
				},
				"note": {
					"type": "string",
					"maxLength": 240
				}
			},
			"additionalProperties": false
		}
	},
	"subscription.set": {
		"op": "subscription.set",
		"verb": "Save",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"pattern",
				"tier"
			],
			"properties": {
				"pattern": {
					"type": "string"
				},
				"tier": {
					"enum": [
						"feed",
						"digest",
						"interrupt"
					]
				},
				"loud": {
					"type": "boolean"
				},
				"note": {
					"type": "string",
					"maxLength": 500
				},
				"owner": {
					"type": "string"
				},
				"window": {
					"type": "string",
					"pattern": "^([0-9]{2}:[0-9]{2}|[0-9]+[mh])$"
				}
			},
			"additionalProperties": false
		}
	},
	"subscription.remove": {
		"op": "subscription.remove",
		"verb": "Remove",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"pattern"
			],
			"properties": {
				"pattern": {
					"type": "string"
				},
				"owner": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"card.repost": {
		"op": "card.repost",
		"verb": "Re-post",
		"lane": "operator",
		"executor": "dispatcher",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"card_id"
			],
			"properties": {
				"card_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"card.park": {
		"op": "card.park",
		"verb": "Park",
		"lane": "operator",
		"executor": "dispatcher",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"card_id"
			],
			"properties": {
				"card_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"stats.query": {
		"op": "stats.query",
		"verb": "Re-run",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"schema_version",
				"mode"
			],
			"additionalProperties": false,
			"properties": {
				"schema_version": {
					"const": 1
				},
				"mode": {
					"enum": [
						"structured",
						"sql"
					]
				},
				"from": {
					"type": "string",
					"maxLength": 128
				},
				"select": {
					"type": "array",
					"maxItems": 64,
					"items": {
						"type": "object",
						"required": [
							"field"
						],
						"additionalProperties": false,
						"properties": {
							"field": {
								"type": "string",
								"maxLength": 128
							},
							"agg": {
								"enum": [
									"sum",
									"avg",
									"min",
									"max",
									"count",
									"count_distinct",
									"p50",
									"p95",
									"p99",
									"last",
									"rate",
									null
								]
							},
							"as": {
								"type": "string",
								"maxLength": 64
							}
						}
					}
				},
				"where": {
					"type": "object",
					"maxProperties": 32,
					"additionalProperties": true
				},
				"group_by": {
					"type": "array",
					"maxItems": 16,
					"items": {
						"type": "string"
					}
				},
				"time": {
					"type": [
						"object",
						"null"
					],
					"additionalProperties": false,
					"properties": {
						"from": {
							"type": "string"
						},
						"to": {
							"type": [
								"string",
								"null"
							]
						},
						"bucket": {
							"type": [
								"string",
								"null"
							],
							"pattern": "^[0-9]+(s|m|h|d)$"
						},
						"fill": {
							"enum": [
								"none",
								"null",
								"zero",
								"previous",
								null
							]
						},
						"coverage": {
							"type": "boolean"
						}
					}
				},
				"order": {
					"type": [
						"array",
						"null"
					],
					"maxItems": 8,
					"items": {
						"type": "object",
						"required": [
							"field",
							"dir"
						],
						"additionalProperties": false,
						"properties": {
							"field": {
								"type": "string"
							},
							"dir": {
								"enum": [
									"asc",
									"desc"
								]
							}
						}
					}
				},
				"limit": {
					"type": [
						"integer",
						"null"
					],
					"minimum": 1,
					"maximum": 100000
				},
				"sql": {
					"type": [
						"string",
						"null"
					],
					"maxLength": 65536
				}
			},
			"allOf": [
				{
					"if": {
						"properties": {
							"mode": {
								"const": "structured"
							}
						}
					},
					"then": {
						"required": [
							"from"
						],
						"properties": {
							"sql": {
								"type": "null"
							}
						}
					}
				},
				{
					"if": {
						"properties": {
							"mode": {
								"const": "sql"
							}
						}
					},
					"then": {
						"required": [
							"sql"
						],
						"properties": {
							"from": false,
							"select": false,
							"where": false,
							"group_by": false,
							"time": false,
							"order": false
						}
					}
				}
			]
		}
	},
	"viz.render": {
		"op": "viz.render",
		"verb": "Regenerate",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"panel"
			],
			"properties": {
				"panel": {
					"type": "object",
					"required": [
						"schema_version",
						"type",
						"title"
					],
					"additionalProperties": true,
					"properties": {
						"schema_version": {
							"const": 2
						},
						"type": {
							"enum": [
								"bar",
								"line",
								"stat",
								"table",
								"pie",
								"scatter",
								"gauge",
								"heatmap",
								"histogram",
								"insight",
								"text",
								"refusal"
							]
						},
						"title": {
							"type": "string",
							"maxLength": 200
						},
						"description": {
							"type": [
								"string",
								"null"
							]
						},
						"query_ref": {
							"type": [
								"string",
								"null"
							]
						},
						"encoding": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"x": {
									"type": [
										"string",
										"null"
									]
								},
								"y": {
									"type": [
										"string",
										"null"
									]
								},
								"group_by": {
									"type": [
										"string",
										"null"
									]
								},
								"columns": {
									"type": [
										"array",
										"null"
									],
									"items": {
										"type": "string"
									}
								},
								"value": {
									"type": [
										"string",
										"null"
									]
								},
								"unit": {
									"type": [
										"string",
										"null"
									]
								},
								"color": {
									"type": [
										"string",
										"null"
									]
								},
								"color_palette": {
									"type": [
										"array",
										"null"
									],
									"items": {
										"type": "string"
									}
								},
								"color_map": {
									"type": [
										"object",
										"null"
									],
									"additionalProperties": {
										"type": "string"
									}
								}
							}
						},
						"prose": {
							"type": [
								"string",
								"null"
							]
						},
						"refusal": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"required": [
								"reason"
							],
							"properties": {
								"reason": {
									"type": "string"
								},
								"suggestions": {
									"type": "array",
									"items": {
										"type": "string"
									}
								}
							}
						},
						"summary": {
							"type": [
								"string",
								"null"
							]
						},
						"narrative": {
							"type": [
								"string",
								"null"
							]
						},
						"confidence": {
							"enum": [
								"high",
								"medium",
								"low",
								null
							]
						},
						"recommendations": {
							"type": [
								"array",
								"null"
							],
							"items": {
								"type": "string"
							}
						},
						"suggestions": {
							"type": [
								"array",
								"null"
							],
							"items": {
								"type": "string"
							}
						},
						"forecast": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"strategy": {
									"enum": [
										"auto",
										"linear",
										"drift",
										"moving_average",
										"exp_smoothing",
										"seasonal_naive"
									]
								},
								"horizon": {
									"type": "integer"
								},
								"window": {
									"type": [
										"integer",
										"null"
									]
								},
								"alpha": {
									"type": [
										"number",
										"null"
									]
								},
								"season_length": {
									"type": [
										"integer",
										"null"
									]
								},
								"confidence": {
									"enum": [
										"high",
										"medium",
										"low",
										null
									]
								},
								"interval_pct": {
									"type": [
										"number",
										"null"
									]
								}
							}
						},
						"layout": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"col": {
									"type": "integer",
									"minimum": 0,
									"maximum": 11
								},
								"span": {
									"type": "integer",
									"minimum": 3,
									"maximum": 12
								},
								"row": {
									"type": "integer",
									"minimum": 0
								},
								"height": {
									"type": [
										"integer",
										"null"
									]
								},
								"group": {
									"type": [
										"string",
										"null"
									]
								},
								"highlight": {
									"type": "boolean"
								},
								"locked": {
									"type": "boolean"
								}
							}
						},
						"live": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"pattern": {
									"type": "string"
								},
								"cadence_s": {
									"type": [
										"number",
										"null"
									]
								}
							}
						},
						"render": {
							"oneOf": [
								{
									"type": "object",
									"required": [
										"schema_version",
										"renderer",
										"spec",
										"data_query_ref",
										"selection_reason",
										"forecast_strategy"
									],
									"additionalProperties": true,
									"properties": {
										"schema_version": {
											"const": 1
										},
										"renderer": {
											"enum": [
												"vega-lite",
												"native"
											]
										},
										"spec": {
											"type": [
												"object",
												"null"
											]
										},
										"data_query_ref": {
											"type": [
												"string",
												"null"
											]
										},
										"selection_reason": {
											"type": "string"
										},
										"forecast_strategy": {
											"enum": [
												"linear",
												"drift",
												"moving_average",
												"exp_smoothing",
												"seasonal_naive",
												null
											]
										},
										"bindings": {
											"type": "array",
											"items": {
												"type": "object",
												"required": [
													"binding",
													"query_ref",
													"column",
													"value",
													"status"
												],
												"additionalProperties": false,
												"properties": {
													"binding": {
														"type": "string"
													},
													"query_ref": {
														"type": [
															"string",
															"null"
														]
													},
													"column": {
														"type": "string"
													},
													"value": true,
													"status": {
														"enum": [
															"resolved",
															"refused"
														]
													}
												}
											}
										}
									}
								},
								{
									"type": "null"
								}
							]
						}
					},
					"allOf": [
						{
							"if": {
								"properties": {
									"type": {
										"enum": [
											"bar",
											"line",
											"stat",
											"table",
											"pie",
											"scatter",
											"gauge",
											"heatmap",
											"histogram",
											"insight"
										]
									}
								}
							},
							"then": {
								"required": [
									"query_ref"
								],
								"properties": {
									"query_ref": {
										"type": "string"
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": {
										"const": "text"
									}
								}
							},
							"then": {
								"required": [
									"prose"
								],
								"properties": {
									"prose": {
										"type": "string"
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": {
										"const": "refusal"
									}
								}
							},
							"then": {
								"required": [
									"refusal"
								],
								"properties": {
									"refusal": {
										"type": "object"
									}
								}
							}
						}
					]
				}
			},
			"additionalProperties": false
		}
	},
	"text.surface": {
		"op": "text.surface",
		"verb": "Surface",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"prose"
			],
			"properties": {
				"prose": {
					"type": "string",
					"maxLength": 65536
				},
				"bindings": {
					"type": "array",
					"items": {
						"type": "object",
						"required": [
							"query_ref",
							"column"
						],
						"properties": {
							"query_ref": {
								"type": "string"
							},
							"column": {
								"type": "string"
							},
							"agg": {
								"type": "string"
							}
						},
						"additionalProperties": false
					}
				}
			},
			"additionalProperties": false
		}
	},
	"window.arrange": {
		"op": "window.arrange",
		"verb": "Arrange",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"dashboard_id",
				"ops"
			],
			"properties": {
				"dashboard_id": {
					"type": "string"
				},
				"ops": {
					"type": "array",
					"maxItems": 100,
					"items": {
						"type": "object",
						"required": [
							"verb"
						],
						"properties": {
							"verb": {
								"enum": [
									"place",
									"size",
									"group",
									"highlight",
									"clear",
									"pin"
								]
							},
							"panel_index": {
								"type": "integer"
							},
							"layout": {
								"type": "object"
							}
						},
						"additionalProperties": true
					}
				}
			},
			"additionalProperties": false
		}
	},
	"dashboard.save": {
		"op": "dashboard.save",
		"verb": "Save",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"title",
				"panels"
			],
			"properties": {
				"title": {
					"type": "string",
					"maxLength": 200
				},
				"layout": {
					"type": "object"
				},
				"panels": {
					"type": "array",
					"maxItems": 60,
					"items": {
						"type": "object",
						"required": [
							"schema_version",
							"type",
							"title"
						],
						"additionalProperties": true,
						"properties": {
							"schema_version": {
								"const": 2
							},
							"type": {
								"enum": [
									"bar",
									"line",
									"stat",
									"table",
									"pie",
									"scatter",
									"gauge",
									"heatmap",
									"histogram",
									"insight",
									"text",
									"refusal"
								]
							},
							"title": {
								"type": "string",
								"maxLength": 200
							},
							"description": {
								"type": [
									"string",
									"null"
								]
							},
							"query_ref": {
								"type": [
									"string",
									"null"
								]
							},
							"encoding": {
								"type": [
									"object",
									"null"
								],
								"additionalProperties": true,
								"properties": {
									"x": {
										"type": [
											"string",
											"null"
										]
									},
									"y": {
										"type": [
											"string",
											"null"
										]
									},
									"group_by": {
										"type": [
											"string",
											"null"
										]
									},
									"columns": {
										"type": [
											"array",
											"null"
										],
										"items": {
											"type": "string"
										}
									},
									"value": {
										"type": [
											"string",
											"null"
										]
									},
									"unit": {
										"type": [
											"string",
											"null"
										]
									},
									"color": {
										"type": [
											"string",
											"null"
										]
									},
									"color_palette": {
										"type": [
											"array",
											"null"
										],
										"items": {
											"type": "string"
										}
									},
									"color_map": {
										"type": [
											"object",
											"null"
										],
										"additionalProperties": {
											"type": "string"
										}
									}
								}
							},
							"prose": {
								"type": [
									"string",
									"null"
								]
							},
							"refusal": {
								"type": [
									"object",
									"null"
								],
								"additionalProperties": true,
								"required": [
									"reason"
								],
								"properties": {
									"reason": {
										"type": "string"
									},
									"suggestions": {
										"type": "array",
										"items": {
											"type": "string"
										}
									}
								}
							},
							"summary": {
								"type": [
									"string",
									"null"
								]
							},
							"narrative": {
								"type": [
									"string",
									"null"
								]
							},
							"confidence": {
								"enum": [
									"high",
									"medium",
									"low",
									null
								]
							},
							"recommendations": {
								"type": [
									"array",
									"null"
								],
								"items": {
									"type": "string"
								}
							},
							"suggestions": {
								"type": [
									"array",
									"null"
								],
								"items": {
									"type": "string"
								}
							},
							"forecast": {
								"type": [
									"object",
									"null"
								],
								"additionalProperties": true,
								"properties": {
									"strategy": {
										"enum": [
											"auto",
											"linear",
											"drift",
											"moving_average",
											"exp_smoothing",
											"seasonal_naive"
										]
									},
									"horizon": {
										"type": "integer"
									},
									"window": {
										"type": [
											"integer",
											"null"
										]
									},
									"alpha": {
										"type": [
											"number",
											"null"
										]
									},
									"season_length": {
										"type": [
											"integer",
											"null"
										]
									},
									"confidence": {
										"enum": [
											"high",
											"medium",
											"low",
											null
										]
									},
									"interval_pct": {
										"type": [
											"number",
											"null"
										]
									}
								}
							},
							"layout": {
								"type": [
									"object",
									"null"
								],
								"additionalProperties": true,
								"properties": {
									"col": {
										"type": "integer",
										"minimum": 0,
										"maximum": 11
									},
									"span": {
										"type": "integer",
										"minimum": 3,
										"maximum": 12
									},
									"row": {
										"type": "integer",
										"minimum": 0
									},
									"height": {
										"type": [
											"integer",
											"null"
										]
									},
									"group": {
										"type": [
											"string",
											"null"
										]
									},
									"highlight": {
										"type": "boolean"
									},
									"locked": {
										"type": "boolean"
									}
								}
							},
							"live": {
								"type": [
									"object",
									"null"
								],
								"additionalProperties": true,
								"properties": {
									"pattern": {
										"type": "string"
									},
									"cadence_s": {
										"type": [
											"number",
											"null"
										]
									}
								}
							},
							"render": {
								"oneOf": [
									{
										"type": "object",
										"required": [
											"schema_version",
											"renderer",
											"spec",
											"data_query_ref",
											"selection_reason",
											"forecast_strategy"
										],
										"additionalProperties": true,
										"properties": {
											"schema_version": {
												"const": 1
											},
											"renderer": {
												"enum": [
													"vega-lite",
													"native"
												]
											},
											"spec": {
												"type": [
													"object",
													"null"
												]
											},
											"data_query_ref": {
												"type": [
													"string",
													"null"
												]
											},
											"selection_reason": {
												"type": "string"
											},
											"forecast_strategy": {
												"enum": [
													"linear",
													"drift",
													"moving_average",
													"exp_smoothing",
													"seasonal_naive",
													null
												]
											},
											"bindings": {
												"type": "array",
												"items": {
													"type": "object",
													"required": [
														"binding",
														"query_ref",
														"column",
														"value",
														"status"
													],
													"additionalProperties": false,
													"properties": {
														"binding": {
															"type": "string"
														},
														"query_ref": {
															"type": [
																"string",
																"null"
															]
														},
														"column": {
															"type": "string"
														},
														"value": true,
														"status": {
															"enum": [
																"resolved",
																"refused"
															]
														}
													}
												}
											}
										}
									},
									{
										"type": "null"
									}
								]
							}
						},
						"allOf": [
							{
								"if": {
									"properties": {
										"type": {
											"enum": [
												"bar",
												"line",
												"stat",
												"table",
												"pie",
												"scatter",
												"gauge",
												"heatmap",
												"histogram",
												"insight"
											]
										}
									}
								},
								"then": {
									"required": [
										"query_ref"
									],
									"properties": {
										"query_ref": {
											"type": "string"
										}
									}
								}
							},
							{
								"if": {
									"properties": {
										"type": {
											"const": "text"
										}
									}
								},
								"then": {
									"required": [
										"prose"
									],
									"properties": {
										"prose": {
											"type": "string"
										}
									}
								}
							},
							{
								"if": {
									"properties": {
										"type": {
											"const": "refusal"
										}
									}
								},
								"then": {
									"required": [
										"refusal"
									],
									"properties": {
										"refusal": {
											"type": "object"
										}
									}
								}
							}
						]
					}
				},
				"branch": {
					"type": "object"
				},
				"time": {
					"type": "object",
					"properties": {
						"from": {
							"type": "string"
						},
						"to": {
							"type": [
								"string",
								"null"
							]
						},
						"refresh_s": {
							"type": [
								"integer",
								"null"
							]
						}
					}
				}
			},
			"additionalProperties": false
		}
	},
	"dashboard.load": {
		"op": "dashboard.load",
		"verb": "Load",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"dashboard.set_home": {
		"op": "dashboard.set_home",
		"verb": "Set as home",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"dashboard.pin": {
		"op": "dashboard.pin",
		"verb": "Pin to home",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"panel"
			],
			"properties": {
				"panel": {
					"type": "object",
					"required": [
						"schema_version",
						"type",
						"title"
					],
					"additionalProperties": true,
					"properties": {
						"schema_version": {
							"const": 2
						},
						"type": {
							"enum": [
								"bar",
								"line",
								"stat",
								"table",
								"pie",
								"scatter",
								"gauge",
								"heatmap",
								"histogram",
								"insight",
								"text",
								"refusal"
							]
						},
						"title": {
							"type": "string",
							"maxLength": 200
						},
						"description": {
							"type": [
								"string",
								"null"
							]
						},
						"query_ref": {
							"type": [
								"string",
								"null"
							]
						},
						"encoding": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"x": {
									"type": [
										"string",
										"null"
									]
								},
								"y": {
									"type": [
										"string",
										"null"
									]
								},
								"group_by": {
									"type": [
										"string",
										"null"
									]
								},
								"columns": {
									"type": [
										"array",
										"null"
									],
									"items": {
										"type": "string"
									}
								},
								"value": {
									"type": [
										"string",
										"null"
									]
								},
								"unit": {
									"type": [
										"string",
										"null"
									]
								},
								"color": {
									"type": [
										"string",
										"null"
									]
								},
								"color_palette": {
									"type": [
										"array",
										"null"
									],
									"items": {
										"type": "string"
									}
								},
								"color_map": {
									"type": [
										"object",
										"null"
									],
									"additionalProperties": {
										"type": "string"
									}
								}
							}
						},
						"prose": {
							"type": [
								"string",
								"null"
							]
						},
						"refusal": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"required": [
								"reason"
							],
							"properties": {
								"reason": {
									"type": "string"
								},
								"suggestions": {
									"type": "array",
									"items": {
										"type": "string"
									}
								}
							}
						},
						"summary": {
							"type": [
								"string",
								"null"
							]
						},
						"narrative": {
							"type": [
								"string",
								"null"
							]
						},
						"confidence": {
							"enum": [
								"high",
								"medium",
								"low",
								null
							]
						},
						"recommendations": {
							"type": [
								"array",
								"null"
							],
							"items": {
								"type": "string"
							}
						},
						"suggestions": {
							"type": [
								"array",
								"null"
							],
							"items": {
								"type": "string"
							}
						},
						"forecast": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"strategy": {
									"enum": [
										"auto",
										"linear",
										"drift",
										"moving_average",
										"exp_smoothing",
										"seasonal_naive"
									]
								},
								"horizon": {
									"type": "integer"
								},
								"window": {
									"type": [
										"integer",
										"null"
									]
								},
								"alpha": {
									"type": [
										"number",
										"null"
									]
								},
								"season_length": {
									"type": [
										"integer",
										"null"
									]
								},
								"confidence": {
									"enum": [
										"high",
										"medium",
										"low",
										null
									]
								},
								"interval_pct": {
									"type": [
										"number",
										"null"
									]
								}
							}
						},
						"layout": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"col": {
									"type": "integer",
									"minimum": 0,
									"maximum": 11
								},
								"span": {
									"type": "integer",
									"minimum": 3,
									"maximum": 12
								},
								"row": {
									"type": "integer",
									"minimum": 0
								},
								"height": {
									"type": [
										"integer",
										"null"
									]
								},
								"group": {
									"type": [
										"string",
										"null"
									]
								},
								"highlight": {
									"type": "boolean"
								},
								"locked": {
									"type": "boolean"
								}
							}
						},
						"live": {
							"type": [
								"object",
								"null"
							],
							"additionalProperties": true,
							"properties": {
								"pattern": {
									"type": "string"
								},
								"cadence_s": {
									"type": [
										"number",
										"null"
									]
								}
							}
						},
						"render": {
							"oneOf": [
								{
									"type": "object",
									"required": [
										"schema_version",
										"renderer",
										"spec",
										"data_query_ref",
										"selection_reason",
										"forecast_strategy"
									],
									"additionalProperties": true,
									"properties": {
										"schema_version": {
											"const": 1
										},
										"renderer": {
											"enum": [
												"vega-lite",
												"native"
											]
										},
										"spec": {
											"type": [
												"object",
												"null"
											]
										},
										"data_query_ref": {
											"type": [
												"string",
												"null"
											]
										},
										"selection_reason": {
											"type": "string"
										},
										"forecast_strategy": {
											"enum": [
												"linear",
												"drift",
												"moving_average",
												"exp_smoothing",
												"seasonal_naive",
												null
											]
										},
										"bindings": {
											"type": "array",
											"items": {
												"type": "object",
												"required": [
													"binding",
													"query_ref",
													"column",
													"value",
													"status"
												],
												"additionalProperties": false,
												"properties": {
													"binding": {
														"type": "string"
													},
													"query_ref": {
														"type": [
															"string",
															"null"
														]
													},
													"column": {
														"type": "string"
													},
													"value": true,
													"status": {
														"enum": [
															"resolved",
															"refused"
														]
													}
												}
											}
										}
									}
								},
								{
									"type": "null"
								}
							]
						}
					},
					"allOf": [
						{
							"if": {
								"properties": {
									"type": {
										"enum": [
											"bar",
											"line",
											"stat",
											"table",
											"pie",
											"scatter",
											"gauge",
											"heatmap",
											"histogram",
											"insight"
										]
									}
								}
							},
							"then": {
								"required": [
									"query_ref"
								],
								"properties": {
									"query_ref": {
										"type": "string"
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": {
										"const": "text"
									}
								}
							},
							"then": {
								"required": [
									"prose"
								],
								"properties": {
									"prose": {
										"type": "string"
									}
								}
							}
						},
						{
							"if": {
								"properties": {
									"type": {
										"const": "refusal"
									}
								}
							},
							"then": {
								"required": [
									"refusal"
								],
								"properties": {
									"refusal": {
										"type": "object"
									}
								}
							}
						}
					]
				}
			},
			"additionalProperties": false
		}
	},
	"dashboard.delete": {
		"op": "dashboard.delete",
		"verb": "Delete",
		"lane": "viewer",
		"executor": "library",
		"confirm": "soft",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"dashboard.share": {
		"op": "dashboard.share",
		"verb": "Share",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id",
				"subject"
			],
			"properties": {
				"id": {
					"type": "string"
				},
				"subject": {
					"type": "string"
				},
				"relation": {
					"enum": [
						"viewer",
						"editor"
					]
				}
			},
			"additionalProperties": false
		}
	},
	"context.receive": {
		"op": "context.receive",
		"verb": "Receive",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"payload"
			],
			"properties": {
				"payload": {
					"type": "object",
					"required": [
						"element_kind",
						"value"
					],
					"properties": {
						"element_kind": {
							"type": "string"
						},
						"field": {
							"type": "string"
						},
						"value": {},
						"datum": {
							"type": "object"
						},
						"query_ref": {
							"type": "string"
						},
						"entity_ref": {
							"type": "string"
						}
					},
					"additionalProperties": false
				}
			},
			"additionalProperties": false
		}
	},
	"kb.search": {
		"op": "kb.search",
		"verb": "Search",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"q"
			],
			"properties": {
				"q": {
					"type": "string",
					"maxLength": 2000
				},
				"kinds": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"limit": {
					"type": "integer",
					"maximum": 100
				}
			},
			"additionalProperties": false
		}
	},
	"kb.research": {
		"op": "kb.research",
		"verb": "Research",
		"lane": "editor",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"query"
			],
			"properties": {
				"query": {
					"type": "string",
					"maxLength": 4000
				}
			},
			"additionalProperties": false
		}
	},
	"library.item.create": {
		"op": "library.item.create",
		"verb": "Create",
		"lane": "editor",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"item"
			],
			"properties": {
				"item": {
					"type": "object",
					"required": [
						"kind",
						"title",
						"scope"
					],
					"additionalProperties": true
				}
			},
			"additionalProperties": false
		}
	},
	"library.item.update": {
		"op": "library.item.update",
		"verb": "Update",
		"lane": "editor",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id",
				"patch"
			],
			"properties": {
				"id": {
					"type": "string"
				},
				"patch": {
					"type": "object"
				}
			},
			"additionalProperties": false
		}
	},
	"library.capability.propose": {
		"op": "library.capability.propose",
		"verb": "Propose",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"capability",
				"title",
				"version",
				"scope",
				"artifact_base64"
			],
			"properties": {
				"capability": {
					"type": "string",
					"minLength": 1,
					"maxLength": 128
				},
				"title": {
					"type": "string",
					"minLength": 1,
					"maxLength": 160
				},
				"version": {
					"type": "string",
					"minLength": 1,
					"maxLength": 64
				},
				"scope": {
					"type": "string"
				},
				"artifact_base64": {
					"type": "string",
					"maxLength": 1398104
				}
			},
			"additionalProperties": false
		}
	},
	"library.capability.review": {
		"op": "library.capability.review",
		"verb": "Review",
		"lane": "admin",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"proposal_id",
				"decision"
			],
			"properties": {
				"proposal_id": {
					"type": "string"
				},
				"decision": {
					"enum": [
						"under-review",
						"promoted",
						"rejected"
					]
				}
			},
			"additionalProperties": false
		}
	},
	"library.link.add": {
		"op": "library.link.add",
		"verb": "Add",
		"lane": "editor",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"from_id",
				"to_id",
				"rel_type"
			],
			"properties": {
				"from_id": {
					"type": "string"
				},
				"to_id": {
					"type": "string"
				},
				"rel_type": {
					"enum": [
						"belongs-to",
						"supersedes",
						"derived-from",
						"duplicate-of",
						"references"
					]
				},
				"reason": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"library.hold": {
		"op": "library.hold",
		"verb": "Hold",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"item_id",
				"for_user"
			],
			"properties": {
				"item_id": {
					"type": "string"
				},
				"for_user": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"curation.propose": {
		"op": "curation.propose",
		"verb": "Propose",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"type",
				"item_id",
				"reason"
			],
			"properties": {
				"type": {
					"enum": [
						"weed",
						"merge",
						"dedup",
						"retire",
						"follow-up"
					]
				},
				"item_id": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"curation.approve": {
		"op": "curation.approve",
		"verb": "Approve",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"proposal_id"
			],
			"properties": {
				"proposal_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"curation.reject": {
		"op": "curation.reject",
		"verb": "Reject",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"proposal_id"
			],
			"properties": {
				"proposal_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"item.weed": {
		"op": "item.weed",
		"verb": "Weed",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"item.merge": {
		"op": "item.merge",
		"verb": "Merge",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id",
				"into_id"
			],
			"properties": {
				"id": {
					"type": "string"
				},
				"into_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"item.delete": {
		"op": "item.delete",
		"verb": "Delete",
		"lane": "operator",
		"executor": "library",
		"confirm": "hard",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"id",
				"confirm_name"
			],
			"properties": {
				"id": {
					"type": "string"
				},
				"confirm_name": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"promotion.request": {
		"op": "promotion.request",
		"verb": "Request",
		"lane": "viewer",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"id"
			],
			"properties": {
				"id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"promotion.approve": {
		"op": "promotion.approve",
		"verb": "Approve",
		"lane": "operator",
		"executor": "library",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"request_id"
			],
			"properties": {
				"request_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"service.restart": {
		"op": "service.restart",
		"verb": "Restart",
		"lane": "operator",
		"executor": "box-agent",
		"confirm": "soft",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"host",
				"service"
			],
			"properties": {
				"host": {
					"type": "string"
				},
				"service": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"service.stop": {
		"op": "service.stop",
		"verb": "Stop",
		"lane": "operator",
		"executor": "box-agent",
		"confirm": "hard",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"host",
				"service",
				"confirm_name"
			],
			"properties": {
				"host": {
					"type": "string"
				},
				"service": {
					"type": "string"
				},
				"confirm_name": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"service.logs": {
		"op": "service.logs",
		"verb": "Logs",
		"lane": "operator",
		"executor": "box-agent",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"host",
				"service"
			],
			"properties": {
				"host": {
					"type": "string"
				},
				"service": {
					"type": "string"
				},
				"lines": {
					"type": "integer",
					"maximum": 2000
				}
			},
			"additionalProperties": false
		}
	},
	"host.probe": {
		"op": "host.probe",
		"verb": "Probe",
		"lane": "operator",
		"executor": "probe-runner",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"target"
			],
			"properties": {
				"target": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"host.reboot": {
		"op": "host.reboot",
		"verb": "Reboot",
		"lane": "admin",
		"executor": "box-agent",
		"confirm": "hard",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"box_id",
				"confirm_name"
			],
			"properties": {
				"box_id": {
					"type": "string"
				},
				"confirm_name": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"updates.check": {
		"op": "updates.check",
		"verb": "Check now",
		"lane": "operator",
		"executor": "box-agent",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"box_id"
			],
			"properties": {
				"box_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"updates.approve": {
		"op": "updates.approve",
		"verb": "Approve",
		"lane": "operator",
		"executor": "console-api",
		"confirm": "none",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"box_id",
				"packages"
			],
			"properties": {
				"box_id": {
					"type": "string"
				},
				"packages": {
					"type": "array",
					"minItems": 1,
					"maxItems": 500,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 256
					}
				}
			},
			"additionalProperties": false
		}
	},
	"updates.revoke": {
		"op": "updates.revoke",
		"verb": "Revoke approval",
		"lane": "operator",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"approval_id"
			],
			"properties": {
				"approval_id": {
					"type": "string",
					"format": "uuid"
				}
			},
			"additionalProperties": false
		}
	},
	"updates.apply": {
		"op": "updates.apply",
		"verb": "Apply now",
		"lane": "operator",
		"executor": "box-agent",
		"confirm": "soft",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"box_id"
			],
			"properties": {
				"box_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"edge.enroll.approve": {
		"op": "edge.enroll.approve",
		"verb": "Approve enrollment",
		"lane": "admin",
		"executor": "edge",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"pubkey_fp",
				"handle"
			],
			"properties": {
				"pubkey_fp": {
					"type": "string"
				},
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				}
			},
			"additionalProperties": false
		}
	},
	"edge.enroll.deny": {
		"op": "edge.enroll.deny",
		"verb": "Deny",
		"lane": "admin",
		"executor": "edge",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"pubkey_fp"
			],
			"properties": {
				"pubkey_fp": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"edge.key.revoke": {
		"op": "edge.key.revoke",
		"verb": "Revoke",
		"lane": "admin",
		"executor": "edge",
		"confirm": "hard",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"pubkey_fp",
				"confirm_name"
			],
			"properties": {
				"pubkey_fp": {
					"type": "string"
				},
				"confirm_name": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"doorman.session.drop": {
		"op": "doorman.session.drop",
		"verb": "Drop session",
		"lane": "admin",
		"executor": "edge",
		"confirm": "soft",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"session_id"
			],
			"properties": {
				"session_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"doorman.redial": {
		"op": "doorman.redial",
		"verb": "Redial",
		"lane": "admin",
		"executor": "manager",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"handle"
			],
			"properties": {
				"handle": {
					"type": "string",
					"pattern": "^[a-z0-9][a-z0-9._-]*$"
				}
			},
			"additionalProperties": false
		}
	},
	"term.watch": {
		"op": "term.watch",
		"verb": "Watch session",
		"lane": "term_admin",
		"executor": "pty",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"host",
				"tmux_session",
				"pane_id"
			],
			"properties": {
				"host": {
					"type": "string"
				},
				"tmux_session": {
					"type": "string"
				},
				"pane_id": {
					"type": "string"
				},
				"scrollback_lines": {
					"type": "integer",
					"maximum": 10000
				}
			},
			"additionalProperties": false
		}
	},
	"term.attach": {
		"op": "term.attach",
		"verb": "Attach",
		"lane": "term_admin",
		"executor": "pty",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"stream_id"
			],
			"properties": {
				"stream_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"term.input": {
		"op": "term.input",
		"verb": "Input",
		"lane": "term_admin",
		"executor": "pty",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"stream_id",
				"seq",
				"data_b64"
			],
			"properties": {
				"stream_id": {
					"type": "string"
				},
				"seq": {
					"type": "integer"
				},
				"data_b64": {
					"type": "string",
					"maxLength": 65536
				}
			},
			"additionalProperties": false
		}
	},
	"term.resize": {
		"op": "term.resize",
		"verb": "Resize",
		"lane": "term_admin",
		"executor": "pty",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"stream_id",
				"cols",
				"rows"
			],
			"properties": {
				"stream_id": {
					"type": "string"
				},
				"cols": {
					"type": "integer"
				},
				"rows": {
					"type": "integer"
				}
			},
			"additionalProperties": false
		}
	},
	"term.scrollback": {
		"op": "term.scrollback",
		"verb": "Scrollback",
		"lane": "term_admin",
		"executor": "pty",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"stream_id",
				"lines"
			],
			"properties": {
				"stream_id": {
					"type": "string"
				},
				"lines": {
					"type": "integer",
					"maximum": 10000
				}
			},
			"additionalProperties": false
		}
	},
	"term.detach": {
		"op": "term.detach",
		"verb": "Detach",
		"lane": "term_admin",
		"executor": "pty",
		"confirm": "none",
		"undo": false,
		"humanOnly": true,
		"args": {
			"type": "object",
			"required": [
				"stream_id"
			],
			"properties": {
				"stream_id": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"delivery.test": {
		"op": "delivery.test",
		"verb": "Send a test",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"properties": {},
			"additionalProperties": false
		}
	},
	"delivery.set_target": {
		"op": "delivery.set_target",
		"verb": "Change target",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"channel",
				"target"
			],
			"properties": {
				"channel": {
					"const": "matrix"
				},
				"target": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"delivery.resend": {
		"op": "delivery.resend",
		"verb": "Resend",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": false,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"receipt_ref"
			],
			"properties": {
				"receipt_ref": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"delivery.cocoon": {
		"op": "delivery.cocoon",
		"verb": "Until 07:00",
		"lane": "viewer",
		"executor": "console-api",
		"confirm": "none",
		"undo": true,
		"humanOnly": false,
		"args": {
			"type": "object",
			"required": [
				"until"
			],
			"properties": {
				"until": {
					"type": "string",
					"format": "date-time"
				}
			},
			"additionalProperties": false
		}
	}
} as const satisfies Record<OpName, OpDef>;
/** @public Generated valid arguments for compatibility tests and downstream consumers. */
export const OP_TEST_FIXTURES = {
	"attention.ack": {
		"id": "fixture"
	},
	"attention.snooze": {
		"id": "fixture"
	},
	"attention.resolve": {
		"id": "fixture"
	},
	"task.get_ready": {},
	"task.up_next": {
		"id": 0
	},
	"task.claim": {},
	"task.update": {
		"id": 0,
		"patch": {}
	},
	"task.close": {
		"id": 0,
		"status": "done",
		"reason": "fixture"
	},
	"task.dispatch": {
		"body": "fixture"
	},
	"agent.start": {
		"handle": "fixture"
	},
	"agent.stop": {
		"handle": "fixture"
	},
	"agent.restart": {
		"handle": "fixture"
	},
	"agent.kill_session": {
		"handle": "fixture",
		"confirm_name": "fixture"
	},
	"agent.autonomy": {
		"handle": "fixture",
		"autonomy": "auto"
	},
	"governance.action": {
		"handle": "fixture",
		"action": "pause"
	},
	"governance.tier": {
		"handle": "fixture",
		"tier": "haiku"
	},
	"fleet.mode": {
		"mode": "parallel"
	},
	"channel.reclaim": {
		"handle": "fixture"
	},
	"signal.snooze": {
		"type_pattern": "fixture"
	},
	"signal.source_mode": {
		"source_service": "fixture",
		"mode": "normal"
	},
	"subscription.set": {
		"pattern": "fixture",
		"tier": "feed"
	},
	"subscription.remove": {
		"pattern": "fixture"
	},
	"card.repost": {
		"card_id": "fixture"
	},
	"card.park": {
		"card_id": "fixture"
	},
	"stats.query": {
		"schema_version": 1,
		"mode": "structured"
	},
	"viz.render": {
		"panel": {
			"schema_version": 2,
			"type": "bar",
			"title": "fixture"
		}
	},
	"text.surface": {
		"prose": "fixture"
	},
	"window.arrange": {
		"dashboard_id": "fixture",
		"ops": []
	},
	"dashboard.save": {
		"title": "fixture",
		"panels": []
	},
	"dashboard.load": {
		"id": "fixture"
	},
	"dashboard.set_home": {
		"id": "fixture"
	},
	"dashboard.pin": {
		"panel": {
			"schema_version": 2,
			"type": "bar",
			"title": "fixture"
		}
	},
	"dashboard.delete": {
		"id": "fixture"
	},
	"dashboard.share": {
		"id": "fixture",
		"subject": "fixture"
	},
	"context.receive": {
		"payload": {
			"element_kind": "fixture",
			"value": null
		}
	},
	"kb.search": {
		"q": "fixture"
	},
	"kb.research": {
		"query": "fixture"
	},
	"library.item.create": {
		"item": {
			"kind": null,
			"title": null,
			"scope": null
		}
	},
	"library.item.update": {
		"id": "fixture",
		"patch": {}
	},
	"library.capability.propose": {
		"capability": "fixture",
		"title": "fixture",
		"version": "fixture",
		"scope": "fixture",
		"artifact_base64": "fixture"
	},
	"library.capability.review": {
		"proposal_id": "fixture",
		"decision": "under-review"
	},
	"library.link.add": {
		"from_id": "fixture",
		"to_id": "fixture",
		"rel_type": "belongs-to"
	},
	"library.hold": {
		"item_id": "fixture",
		"for_user": "fixture"
	},
	"curation.propose": {
		"type": "weed",
		"item_id": "fixture",
		"reason": "fixture"
	},
	"curation.approve": {
		"proposal_id": "fixture"
	},
	"curation.reject": {
		"proposal_id": "fixture"
	},
	"item.weed": {
		"id": "fixture"
	},
	"item.merge": {
		"id": "fixture",
		"into_id": "fixture"
	},
	"item.delete": {
		"id": "fixture",
		"confirm_name": "fixture"
	},
	"promotion.request": {
		"id": "fixture"
	},
	"promotion.approve": {
		"request_id": "fixture"
	},
	"service.restart": {
		"host": "fixture",
		"service": "fixture"
	},
	"service.stop": {
		"host": "fixture",
		"service": "fixture",
		"confirm_name": "fixture"
	},
	"service.logs": {
		"host": "fixture",
		"service": "fixture"
	},
	"host.probe": {
		"target": "fixture"
	},
	"host.reboot": {
		"box_id": "fixture",
		"confirm_name": "fixture"
	},
	"updates.check": {
		"box_id": "fixture"
	},
	"updates.approve": {
		"box_id": "fixture",
		"packages": []
	},
	"updates.revoke": {
		"approval_id": "00000000-0000-4000-8000-000000000000"
	},
	"updates.apply": {
		"box_id": "fixture"
	},
	"edge.enroll.approve": {
		"pubkey_fp": "fixture",
		"handle": "fixture"
	},
	"edge.enroll.deny": {
		"pubkey_fp": "fixture"
	},
	"edge.key.revoke": {
		"pubkey_fp": "fixture",
		"confirm_name": "fixture"
	},
	"doorman.session.drop": {
		"session_id": "fixture"
	},
	"doorman.redial": {
		"handle": "fixture"
	},
	"term.watch": {
		"host": "fixture",
		"tmux_session": "fixture",
		"pane_id": "fixture"
	},
	"term.attach": {
		"stream_id": "fixture"
	},
	"term.input": {
		"stream_id": "fixture",
		"seq": 0,
		"data_b64": "fixture"
	},
	"term.resize": {
		"stream_id": "fixture",
		"cols": 0,
		"rows": 0
	},
	"term.scrollback": {
		"stream_id": "fixture",
		"lines": 0
	},
	"term.detach": {
		"stream_id": "fixture"
	},
	"delivery.test": {},
	"delivery.set_target": {
		"channel": "matrix",
		"target": "fixture"
	},
	"delivery.resend": {
		"receipt_ref": "fixture"
	},
	"delivery.cocoon": {
		"until": "2026-01-01T00:00:00Z"
	}
} as const satisfies Record<OpName, unknown>;

export interface ValidationResult {
	valid: boolean;
	errors: string[];
}

function validateSchema(schema: SchemaNode, value: unknown, path = "$", errors: string[] = []): string[] {
	if (schema === true) return errors;
	if (schema === false) { errors.push(path + " is forbidden by the contract"); return errors; }
	if (schema.const !== undefined && value !== schema.const) errors.push(path + " must equal " + JSON.stringify(schema.const));
	if (schema.enum && !schema.enum.some((item: unknown) => Object.is(item, value))) errors.push(path + " is not in the contract enum");
	for (const child of schema.allOf ?? []) validateSchema(child, value, path, errors);
	const alternatives = schema.oneOf ?? schema.anyOf;
	if (alternatives && !alternatives.some((child: SchemaNode) => validateSchema(child, value, path, []).length === 0)) errors.push(path + " does not match an allowed contract shape");
	const allowed = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
	if (allowed.length) {
		const actual = value === null ? "null" : Array.isArray(value) ? "array" : Number.isInteger(value) ? "integer" : typeof value;
		if (!allowed.includes(actual) && !(actual === "integer" && allowed.includes("number"))) {
			errors.push(path + " must be " + allowed.join(" or "));
			return errors;
		}
	}
	if (typeof value === "string") {
		if (schema.pattern && !new RegExp(schema.pattern).test(value)) errors.push(path + " does not match " + schema.pattern);
		if (schema.minLength !== undefined && value.length < schema.minLength) errors.push(path + " is too short");
		if (schema.maxLength !== undefined && value.length > schema.maxLength) errors.push(path + " is too long");
	}
	if (typeof value === "number") {
		if (schema.minimum !== undefined && value < schema.minimum) errors.push(path + " is below the minimum");
		if (schema.maximum !== undefined && value > schema.maximum) errors.push(path + " exceeds the maximum");
	}
	if (Array.isArray(value)) {
		if (schema.minItems !== undefined && value.length < schema.minItems) errors.push(path + " has too few items");
		if (schema.maxItems !== undefined && value.length > schema.maxItems) errors.push(path + " has too many items");
		if (schema.items) value.forEach((item, index) => validateSchema(schema.items!, item, path + "[" + index + "]", errors));
	}
	if (value !== null && typeof value === "object" && !Array.isArray(value)) {
		const record = value as Record<string, unknown>;
		for (const key of schema.required ?? []) if (!(key in record)) errors.push(path + "." + key + " is required");
		for (const [key, item] of Object.entries(record)) {
			if (schema.properties?.[key]) validateSchema(schema.properties[key], item, path + "." + key, errors);
			else if (schema.additionalProperties === false) errors.push(path + "." + key + " is not allowed");
			else if (schema.additionalProperties && typeof schema.additionalProperties === "object") validateSchema(schema.additionalProperties, item, path + "." + key, errors);
		}
	}
	return errors;
}

export function opDef(op: string): OpDef | undefined { return (OPS as Record<string, OpDef>)[op]; }
export function canSeeOp(op: OpDef, lanes: string[]): boolean { return lanes.includes(op.lane); }
/** @public Validate operation arguments against the canonical catalog schema. */
export function validateOpArgs(op: string, args: unknown): ValidationResult {
	const def = opDef(op);
	if (!def) return { valid: false, errors: [`Unknown operation: ${op}`] };
	const errors = validateSchema(def.args, args);
	return { valid: errors.length === 0, errors };
}
