const domains: Record<string, string> = {
  // -- Ivy League --
  "harvard university": "harvard.edu",
  "yale university": "yale.edu",
  "princeton university": "princeton.edu",
  "columbia university": "columbia.edu",
  "columbia university in the city of new york": "columbia.edu",
  "university of pennsylvania": "upenn.edu",
  "cornell university": "cornell.edu",
  "brown university": "brown.edu",
  "dartmouth college": "dartmouth.edu",

  // -- Top Private --
  "massachusetts institute of technology": "mit.edu",
  "stanford university": "stanford.edu",
  "university of chicago": "uchicago.edu",
  "california institute of technology": "caltech.edu",
  "duke university": "duke.edu",
  "northwestern university": "northwestern.edu",
  "johns hopkins university": "jhu.edu",
  "rice university": "rice.edu",
  "vanderbilt university": "vanderbilt.edu",
  "university of notre dame": "nd.edu",
  "washington university in st. louis": "wustl.edu",
  "washington university in st louis": "wustl.edu",
  "georgetown university": "georgetown.edu",
  "emory university": "emory.edu",
  "carnegie mellon university": "cmu.edu",
  "new york university": "nyu.edu",
  "boston university": "bu.edu",
  "boston college": "bc.edu",
  "tufts university": "tufts.edu",
  "wake forest university": "wfu.edu",
  "tulane university": "tulane.edu",
  "tulane university of louisiana": "tulane.edu",
  "university of southern california": "usc.edu",
  "northeastern university": "northeastern.edu",
  "case western reserve university": "case.edu",
  "university of rochester": "rochester.edu",
  "brandeis university": "brandeis.edu",
  "lehigh university": "lehigh.edu",
  "pepperdine university": "pepperdine.edu",
  "santa clara university": "scu.edu",
  "villanova university": "villanova.edu",
  "rensselaer polytechnic institute": "rpi.edu",
  "worcester polytechnic institute": "wpi.edu",
  "stevens institute of technology": "stevens.edu",
  "george washington university": "gwu.edu",
  "american university": "american.edu",
  "howard university": "howard.edu",
  "fordham university": "fordham.edu",
  "marquette university": "marquette.edu",
  "loyola university chicago": "luc.edu",
  "depaul university": "depaul.edu",
  "seton hall university": "shu.edu",
  "creighton university": "creighton.edu",
  "gonzaga university": "gonzaga.edu",
  "university of san francisco": "usfca.edu",
  "university of san diego": "sandiego.edu",
  "loyola marymount university": "lmu.edu",
  "southern methodist university": "smu.edu",
  "texas christian university": "tcu.edu",
  "baylor university": "baylor.edu",
  "brigham young university-provo": "byu.edu",
  "brigham young university": "byu.edu",
  "university of miami": "miami.edu",
  "university of richmond": "richmond.edu",
  "yeshiva university": "yu.edu",

  // -- UC System --
  "university of california-berkeley": "berkeley.edu",
  "university of california, berkeley": "berkeley.edu",
  "university of california-los angeles": "ucla.edu",
  "university of california, los angeles": "ucla.edu",
  "university of california-san diego": "ucsd.edu",
  "university of california, san diego": "ucsd.edu",
  "university of california-davis": "ucdavis.edu",
  "university of california, davis": "ucdavis.edu",
  "university of california-santa barbara": "ucsb.edu",
  "university of california, santa barbara": "ucsb.edu",
  "university of california-irvine": "uci.edu",
  "university of california, irvine": "uci.edu",
  "university of california-riverside": "ucr.edu",
  "university of california-santa cruz": "ucsc.edu",
  "university of california-san francisco": "ucsf.edu",

  // -- Big State Schools --
  "university of michigan-ann arbor": "umich.edu",
  "university of michigan": "umich.edu",
  "university of michigan-dearborn": "umd.umich.edu",
  "university of michigan-flint": "umflint.edu",
  "university of virginia-main campus": "virginia.edu",
  "university of virginia": "virginia.edu",
  "university of north carolina at chapel hill": "unc.edu",
  "university of florida": "ufl.edu",
  "university of texas at austin": "utexas.edu",
  "georgia institute of technology-main campus": "gatech.edu",
  "georgia institute of technology": "gatech.edu",
  "university of wisconsin-madison": "wisc.edu",
  "university of illinois at urbana-champaign": "illinois.edu",
  "university of illinois urbana-champaign": "illinois.edu",
  "university of illinois at chicago": "uic.edu",
  "university of illinois at springfield": "uis.edu",
  "ohio state university-main campus": "osu.edu",
  "ohio state university": "osu.edu",
  "pennsylvania state university-main campus": "psu.edu",
  "penn state university": "psu.edu",
  "university of washington-seattle campus": "washington.edu",
  "university of washington": "washington.edu",
  "university of maryland-college park": "umd.edu",
  "university of maryland": "umd.edu",
  "university of maryland-baltimore county": "umbc.edu",
  "university of maryland eastern shore": "umes.edu",
  "university of minnesota-twin cities": "umn.edu",
  "university of minnesota": "umn.edu",
  "university of minnesota-duluth": "d.umn.edu",
  "university of minnesota-morris": "morris.umn.edu",
  "purdue university-main campus": "purdue.edu",
  "purdue university": "purdue.edu",
  "indiana university-bloomington": "indiana.edu",
  "indiana university bloomington": "indiana.edu",
  "michigan state university": "msu.edu",
  "university of colorado boulder": "colorado.edu",
  "university of colorado denver": "ucdenver.edu",
  "university of colorado colorado springs": "uccs.edu",
  "rutgers university-new brunswick": "rutgers.edu",
  "rutgers university-newark": "rutgers.edu",
  "rutgers university-camden": "rutgers.edu",
  "rutgers university": "rutgers.edu",
  "university of pittsburgh-pittsburgh campus": "pitt.edu",
  "university of pittsburgh": "pitt.edu",
  "university of iowa": "uiowa.edu",
  "iowa state university": "iastate.edu",
  "university of oregon": "uoregon.edu",
  "oregon state university": "oregonstate.edu",
  "university of connecticut": "uconn.edu",
  "university of arizona": "arizona.edu",
  "arizona state university-tempe": "asu.edu",
  "arizona state university": "asu.edu",
  "university of georgia": "uga.edu",
  "texas a & m university-college station": "tamu.edu",
  "texas a&m university": "tamu.edu",
  "university of utah": "utah.edu",
  "university of kansas": "ku.edu",
  "kansas state university": "ksu.edu",
  "university of kentucky": "uky.edu",
  "university of tennessee-knoxville": "utk.edu",
  "university of tennessee": "utk.edu",
  "university of tennessee-chattanooga": "utc.edu",
  "university of tennessee-martin": "utm.edu",
  "university of oklahoma-norman campus": "ou.edu",
  "university of oklahoma": "ou.edu",
  "oklahoma state university-main campus": "okstate.edu",
  "university of nebraska-lincoln": "unl.edu",
  "university of nebraska at omaha": "unomaha.edu",
  "university of nebraska at kearney": "unk.edu",
  "university of missouri-columbia": "missouri.edu",
  "university of missouri": "missouri.edu",
  "university of missouri-kansas city": "umkc.edu",
  "university of missouri-st louis": "umsl.edu",
  "missouri university of science and technology": "mst.edu",
  "university of south carolina-columbia": "sc.edu",
  "university of south carolina": "sc.edu",
  "university of alabama": "ua.edu",
  "the university of alabama": "ua.edu",
  "university of alabama at birmingham": "uab.edu",
  "university of alabama in huntsville": "uah.edu",
  "university of arkansas": "uark.edu",
  "university of mississippi": "olemiss.edu",
  "mississippi state university": "msstate.edu",
  "louisiana state university and agricultural & mechanical college": "lsu.edu",
  "louisiana state university": "lsu.edu",
  "university of louisville": "louisville.edu",
  "west virginia university": "wvu.edu",
  "university of cincinnati-main campus": "uc.edu",
  "university of cincinnati": "uc.edu",
  "university of delaware": "udel.edu",
  "university of vermont": "uvm.edu",
  "university of new hampshire-main campus": "unh.edu",
  "university of new hampshire": "unh.edu",
  "university of rhode island": "uri.edu",
  "university of maine": "umaine.edu",
  "university of hawaii at manoa": "hawaii.edu",
  "university of hawaii at hilo": "hilo.hawaii.edu",
  "university of alaska fairbanks": "uaf.edu",
  "university of alaska anchorage": "uaa.edu",
  "university of idaho": "uidaho.edu",
  "university of wyoming": "uwyo.edu",
  "university of montana": "umt.edu",
  "montana state university": "montana.edu",
  "university of north dakota": "und.edu",
  "north dakota state university-main campus": "ndsu.edu",
  "university of south dakota": "usd.edu",
  "south dakota state university": "sdstate.edu",
  "university of new mexico-main campus": "unm.edu",
  "university of new mexico": "unm.edu",
  "university of nevada-las vegas": "unlv.edu",
  "university of nevada, las vegas": "unlv.edu",
  "university of nevada-reno": "unr.edu",
  "university of nevada, reno": "unr.edu",

  // -- Other State / Regional Unis --
  "virginia tech": "vt.edu",
  "virginia polytechnic institute and state university": "vt.edu",
  "florida state university": "fsu.edu",
  "university of central florida": "ucf.edu",
  "florida atlantic university": "fau.edu",
  "florida international university": "fiu.edu",
  "university of south florida-main campus": "usf.edu",
  "university of south florida": "usf.edu",
  "florida agricultural and mechanical university": "famu.edu",
  "university of north florida": "unf.edu",
  "clemson university": "clemson.edu",
  "north carolina state university at raleigh": "ncsu.edu",
  "north carolina state university": "ncsu.edu",
  "east carolina university": "ecu.edu",
  "university of north carolina at charlotte": "charlotte.edu",
  "unc charlotte": "charlotte.edu",
  "university of north carolina at greensboro": "uncg.edu",
  "unc greensboro": "uncg.edu",
  "university of north carolina wilmington": "uncw.edu",
  "university of north carolina at asheville": "unca.edu",
  "university of north carolina at pembroke": "uncp.edu",
  "appalachian state university": "appstate.edu",
  "western carolina university": "wcu.edu",
  "north carolina agricultural and technical state university": "ncat.edu",
  "north carolina central university": "nccu.edu",
  "georgia state university": "gsu.edu",
  "georgia southern university": "georgiasouthern.edu",
  "kennesaw state university": "kennesaw.edu",
  "university of north texas": "unt.edu",
  "university of texas at san antonio": "utsa.edu",
  "university of texas at dallas": "utdallas.edu",
  "university of texas at arlington": "uta.edu",
  "university of texas at el paso": "utep.edu",
  "university of texas at tyler": "uttyler.edu",
  "texas state university": "txstate.edu",
  "texas tech university": "ttu.edu",
  "texas a & m university-commerce": "tamuc.edu",
  "texas a & m university-corpus christi": "tamucc.edu",
  "texas a & m university-kingsville": "tamuk.edu",
  "texas a & m international university": "tamiu.edu",
  "sam houston state university": "shsu.edu",
  "stephen f austin state university": "sfasu.edu",
  "texas southern university": "tsu.edu",
  "texas woman's university": "twu.edu",
  "university of houston": "uh.edu",
  "university of houston-clear lake": "uhcl.edu",
  "university of houston-downtown": "uhd.edu",
  "san diego state university": "sdsu.edu",
  "san jose state university": "sjsu.edu",
  "san francisco state university": "sfsu.edu",
  "california state university-fullerton": "fullerton.edu",
  "california state university, fullerton": "fullerton.edu",
  "california state university-long beach": "csulb.edu",
  "california state university, long beach": "csulb.edu",
  "california state university-northridge": "csun.edu",
  "california state university, northridge": "csun.edu",
  "california state university-sacramento": "csus.edu",
  "sacramento state university": "csus.edu",
  "california state university-fresno": "fresnostate.edu",
  "fresno state university": "fresnostate.edu",
  "california state university-chico": "csuchico.edu",
  "california state university-los angeles": "calstatela.edu",
  "california state university-san bernardino": "csusb.edu",
  "california state university-dominguez hills": "csudh.edu",
  "california state university-east bay": "csueastbay.edu",
  "california state university-bakersfield": "csub.edu",
  "california state university-stanislaus": "csustan.edu",
  "california state polytechnic university-pomona": "cpp.edu",
  "california polytechnic state university-san luis obispo": "calpoly.edu",
  "humboldt state university": "humboldt.edu",
  "sonoma state university": "sonoma.edu",
  "portland state university": "pdx.edu",
  "boise state university": "boisestate.edu",
  "university of northern colorado": "unco.edu",
  "colorado state university-fort collins": "colostate.edu",
  "colorado state university": "colostate.edu",
  "colorado school of mines": "mines.edu",
  "university of denver": "du.edu",
  "colorado college": "coloradocollege.edu",
  "washington state university": "wsu.edu",
  "western washington university": "wwu.edu",
  "eastern washington university": "ewu.edu",
  "central washington university": "cwu.edu",
  "university of puget sound": "pugetsound.edu",
  "seattle university": "seattleu.edu",
  "seattle pacific university": "spu.edu",
  "pacific lutheran university": "plu.edu",
  "university of portland": "up.edu",
  "utah state university": "usu.edu",
  "weber state university": "weber.edu",
  "utah valley university": "uvu.edu",
  "southern utah university": "suu.edu",
  "dixie state university": "dixie.edu",
  "university of northern iowa": "uni.edu",
  "iowa wesleyan college": "iw.edu",
  "drake university": "drake.edu",
  "university of central arkansas": "uca.edu",
  "arkansas state university-main campus": "astate.edu",
  "arkansas tech university": "atu.edu",
  "university of central missouri": "ucmo.edu",
  "missouri state university-springfield": "missouristate.edu",
  "southeast missouri state university": "semo.edu",
  "northwest missouri state university": "nwmissouri.edu",
  "truman state university": "truman.edu",
  "university of central oklahoma": "uco.edu",
  "university of tulsa": "utulsa.edu",
  "oral roberts university": "oru.edu",
  "oklahoma baptist university": "okbu.edu",
  "oklahoma christian university": "oc.edu",
  "oklahoma city university": "okcu.edu",
  "university of louisiana at lafayette": "louisiana.edu",
  "university of louisiana at monroe": "ulm.edu",
  "university of new orleans": "uno.edu",
  "louisiana tech university": "latech.edu",
  "mcneese state university": "mcneese.edu",
  "southeastern louisiana university": "southeastern.edu",
  "loyola university new orleans": "loyno.edu",
  "nicholls state university": "nicholls.edu",
  "northwestern state university of louisiana": "nsula.edu",
  "southern university and a & m college": "subr.edu",
  "grambling state university": "gram.edu",
  "xavier university of louisiana": "xula.edu",
  "middle tennessee state university": "mtsu.edu",
  "east tennessee state university": "etsu.edu",
  "tennessee state university": "tnstate.edu",
  "tennessee technological university": "tntech.edu",
  "university of memphis": "memphis.edu",
  "belmont university": "belmont.edu",
  "lipscomb university": "lipscomb.edu",
  "austin peay state university": "apsu.edu",
  "alabama state university": "alasu.edu",
  "alabama a & m university": "aamu.edu",
  "auburn university": "auburn.edu",
  "auburn university at montgomery": "aum.edu",
  "troy university": "troy.edu",
  "jacksonville state university": "jsu.edu",
  "tuskegee university": "tuskegee.edu",
  "samford university": "samford.edu",
  "university of south alabama": "southalabama.edu",
  "university of north alabama": "una.edu",
  "university of west alabama": "uwa.edu",
  "university of montevallo": "montevallo.edu",
  "university of mobile": "umobile.edu",
  "mississippi college": "mc.edu",
  "mississippi university for women": "muw.edu",
  "mississippi valley state university": "mvsu.edu",
  "jackson state university": "jsums.edu",
  "delta state university": "deltastate.edu",
  "university of southern mississippi": "usm.edu",
  "alcorn state university": "alcorn.edu",
  "kentucky state university": "kysu.edu",
  "eastern kentucky university": "eku.edu",
  "western kentucky university": "wku.edu",
  "murray state university": "murraystate.edu",
  "morehead state university": "moreheadstate.edu",
  "northern kentucky university": "nku.edu",
  "south carolina state university": "scsu.edu",
  "coastal carolina university": "coastal.edu",
  "college of charleston": "cofc.edu",
  "winthrop university": "winthrop.edu",
  "francis marion university": "fmarion.edu",
  "delaware state university": "desu.edu",
  "virginia commonwealth university": "vcu.edu",
  "george mason university": "gmu.edu",
  "james madison university": "jmu.edu",
  "old dominion university": "odu.edu",
  "college of william and mary": "wm.edu",
  "college of william & mary": "wm.edu",
  "liberty university": "liberty.edu",
  "radford university": "radford.edu",
  "longwood university": "longwood.edu",
  "christopher newport university": "cnu.edu",
  "hampton university": "hamptonu.edu",
  "norfolk state university": "nsu.edu",
  "virginia state university": "vsu.edu",
  "virginia military institute": "vmi.edu",
  "washington and lee university": "wlu.edu",
  "university of mary washington": "umw.edu",
  "towson university": "towson.edu",
  "salisbury university": "salisbury.edu",
  "bowie state university": "bowiestate.edu",
  "frostburg state university": "frostburg.edu",
  "morgan state university": "morgan.edu",
  "coppin state university": "coppin.edu",
  "loyola university maryland": "loyola.edu",
  "central connecticut state university": "ccsu.edu",
  "southern connecticut state university": "southernct.edu",
  "eastern connecticut state university": "easternct.edu",
  "western connecticut state university": "wcsu.edu",
  "university of hartford": "hartford.edu",
  "quinnipiac university": "qu.edu",
  "sacred heart university": "sacredheart.edu",
  "fairfield university": "fairfield.edu",
  "university of new haven": "newhaven.edu",
  "university of bridgeport": "bridgeport.edu",
  "bridgewater state university": "bridgew.edu",
  "framingham state university": "framingham.edu",
  "salem state university": "salemstate.edu",
  "fitchburg state university": "fitchburgstate.edu",
  "westfield state university": "westfield.ma.edu",
  "worcester state university": "worcester.edu",
  "suffolk university": "suffolk.edu",
  "simmons college": "simmons.edu",
  "emerson college": "emerson.edu",
  "lesley university": "lesley.edu",
  "university of massachusetts-amherst": "umass.edu",
  "university of massachusetts-boston": "umb.edu",
  "university of massachusetts-lowell": "uml.edu",
  "university of massachusetts-dartmouth": "umassd.edu",
  "clark university": "clarku.edu",
  "stony brook university": "stonybrook.edu",
  "university at buffalo": "buffalo.edu",
  "suny at albany": "albany.edu",
  "suny at binghamton": "binghamton.edu",
  "suny college at geneseo": "geneseo.edu",
  "suny at new paltz": "newpaltz.edu",
  "suny oswego": "oswego.edu",
  "suny oneonta": "oneonta.edu",
  "suny cortland": "cortland.edu",
  "suny at fredonia": "fredonia.edu",
  "suny at plattsburgh": "plattsburgh.edu",
  "suny college at brockport": "brockport.edu",
  "suny buffalo state": "buffalostate.edu",
  "suny college at potsdam": "potsdam.edu",
  "suny college at old westbury": "oldwestbury.edu",
  "suny college of environmental science and forestry": "esf.edu",
  "syracuse university": "syracuse.edu",
  "rochester institute of technology": "rit.edu",
  "clarkson university": "clarkson.edu",
  "colgate university": "colgate.edu",
  "hofstra university": "hofstra.edu",
  "ithaca college": "ithaca.edu",
  "marist college": "marist.edu",
  "st john's university-new york": "stjohns.edu",
  "pace university-new york": "pace.edu",
  "new york institute of technology": "nyit.edu",
  "adelphi university": "adelphi.edu",
  "niagara university": "niagara.edu",
  "manhattan college": "manhattan.edu",
  "siena college": "siena.edu",
  "iona college": "iona.edu",
  "the new school": "newschool.edu",
  "pratt institute-main": "pratt.edu",
  "cooper union for the advancement of science and art": "cooper.edu",
  "barnard college": "barnard.edu",
  "bard college": "bard.edu",
  "sarah lawrence college": "sarahlawrence.edu",
  "wagner college": "wagner.edu",
  "le moyne college": "lemoyne.edu",
  "canisius college": "canisius.edu",
  "st bonaventure university": "sbu.edu",
  "st lawrence university": "stlawu.edu",
  "st john fisher college": "sjfc.edu",
  "alfred university": "alfred.edu",
  "hartwick college": "hartwick.edu",
  "new jersey institute of technology": "njit.edu",
  "the college of new jersey": "tcnj.edu",
  "rowan university": "rowan.edu",
  "stockton university": "stockton.edu",
  "montclair state university": "montclair.edu",
  "kean university": "kean.edu",
  "rider university": "rider.edu",
  "monmouth university": "monmouth.edu",
  "saint peter's university": "saintpeters.edu",
  "temple university": "temple.edu",
  "drexel university": "drexel.edu",
  "duquesne university": "duq.edu",
  "saint joseph's university": "sju.edu",
  "la salle university": "lasalle.edu",
  "bucknell university": "bucknell.edu",
  "dickinson college": "dickinson.edu",
  "gettysburg college": "gettysburg.edu",
  "franklin and marshall college": "fandm.edu",
  "franklin & marshall college": "fandm.edu",
  "muhlenberg college": "muhlenberg.edu",
  "ursinus college": "ursinus.edu",
  "haverford college": "haverford.edu",
  "bryn mawr college": "brynmawr.edu",
  "swarthmore college": "swarthmore.edu",
  "lafayette college": "lafayette.edu",
  "allegheny college": "allegheny.edu",
  "susquehanna university": "susqu.edu",
  "lycoming college": "lycoming.edu",
  "moravian college": "moravian.edu",
  "elizabethtown college": "etown.edu",
  "grove city college": "gcc.edu",
  "juniata college": "juniata.edu",
  "messiah college": "messiah.edu",
  "point park university": "pointpark.edu",
  "robert morris university": "rmu.edu",
  "chatham university": "chatham.edu",
  "indiana university of pennsylvania-main campus": "iup.edu",
  "slippery rock university of pennsylvania": "sru.edu",
  "west chester university of pennsylvania": "wcupa.edu",
  "shippensburg university of pennsylvania": "ship.edu",
  "kutztown university of pennsylvania": "kutztown.edu",
  "bloomsburg university of pennsylvania": "bloomu.edu",
  "millersville university of pennsylvania": "millersville.edu",
  "mansfield university of pennsylvania": "mansfield.edu",
  "clarion university of pennsylvania": "clarion.edu",
  "edinboro university of pennsylvania": "edinboro.edu",
  "lock haven university": "lockhaven.edu",
  "east stroudsburg university of pennsylvania": "esu.edu",
  "university of scranton": "scranton.edu",
  "widener university-main campus": "widener.edu",
  "wilkes university": "wilkes.edu",
  "arcadia university": "arcadia.edu",
  "mercyhurst university": "mercyhurst.edu",
  "gannon university": "gannon.edu",
  "marywood university": "marywood.edu",
  "seton hill university": "setonhill.edu",
  "saint vincent college": "stvincent.edu",
  "saint francis university": "francis.edu",
  "waynesburg university": "waynesburg.edu",

  // -- Top Liberal Arts --
  "williams college": "williams.edu",
  "amherst college": "amherst.edu",
  "wellesley college": "wellesley.edu",
  "bowdoin college": "bowdoin.edu",
  "middlebury college": "middlebury.edu",
  "pomona college": "pomona.edu",
  "claremont mckenna college": "cmc.edu",
  "harvey mudd college": "hmc.edu",
  "scripps college": "scrippscollege.edu",
  "pitzer college": "pitzer.edu",
  "carleton college": "carleton.edu",
  "macalester college": "macalester.edu",
  "grinnell college": "grinnell.edu",
  "oberlin college": "oberlin.edu",
  "kenyon college": "kenyon.edu",
  "denison university": "denison.edu",
  "college of wooster": "wooster.edu",
  "hamilton college": "hamilton.edu",
  "union college": "union.edu",
  "skidmore college": "skidmore.edu",
  "vassar college": "vassar.edu",
  "bates college": "bates.edu",
  "colby college": "colby.edu",
  "connecticut college": "conncoll.edu",
  "trinity college": "trincoll.edu",
  "wesleyan university": "wesleyan.edu",
  "mount holyoke college": "mtholyoke.edu",
  "smith college": "smith.edu",
  "reed college": "reed.edu",
  "whitman college": "whitman.edu",
  "rhodes college": "rhodes.edu",
  "sewanee-university of the south": "sewanee.edu",
  "sewanee: the university of the south": "sewanee.edu",
  "centre college": "centre.edu",
  "furman university": "furman.edu",
  "rollins college": "rollins.edu",
  "agnes scott college": "agnesscott.edu",
  "spelman college": "spelman.edu",
  "morehouse college": "morehouse.edu",
  "clark atlanta university": "cau.edu",
  "davidson college": "davidson.edu",
  "elon university": "elon.edu",
  "high point university": "highpoint.edu",
  "lewis & clark college": "lclark.edu",
  "wofford college": "wofford.edu",
  "hendrix college": "hendrix.edu",
  "southwestern university": "southwestern.edu",
  "depauw university": "depauw.edu",
  "wabash college": "wabash.edu",
  "earlham college": "earlham.edu",
  "beloit college": "beloit.edu",
  "lawrence university": "lawrence.edu",
  "ripon college": "ripon.edu",
  "knox college": "knox.edu",
  "lake forest college": "lakeforest.edu",
  "wheaton college": "wheaton.edu",
  "illinois wesleyan university": "iwu.edu",
  "augustana college": "augustana.edu",
  "hope college": "hope.edu",
  "kalamazoo college": "kzoo.edu",
  "albion college": "albion.edu",
  "alma college": "alma.edu",
  "calvin college": "calvin.edu",
  "hillsdale college": "hillsdale.edu",
  "college of the holy cross": "holycross.edu",
  "stonehill college": "stonehill.edu",
  "merrimack college": "merrimack.edu",
  "assumption college": "assumption.edu",
  "saint anselm college": "anselm.edu",
  "saint michael's college": "smcvt.edu",
  "bennington college": "bennington.edu",
  "champlain college": "champlain.edu",
  "norwich university": "norwich.edu",
  "berea college": "berea.edu",
  "transylvania university": "transy.edu",
  "washington & jefferson college": "washjeff.edu",
  "st olaf college": "stolaf.edu",
  "saint olaf college": "stolaf.edu",
  "gustavus adolphus college": "gustavus.edu",
  "saint johns university": "csbsju.edu",
  "college of saint benedict": "csbsju.edu",
  "concordia college at moorhead": "cord.edu",
  "saint cloud state university": "stcloudstate.edu",
  "winona state university": "winona.edu",
  "bemidji state university": "bemidjistate.edu",
  "minnesota state university-mankato": "mnsu.edu",
  "southwest minnesota state university": "smsu.edu",
  "hampshire college": "hampshire.edu",
  "providence college": "providence.edu",
  "bryant university": "bryant.edu",
  "rhode island school of design": "risd.edu",
  "rhode island college": "ric.edu",
  "roger williams university": "rwu.edu",
  "salve regina university": "salve.edu",
  "southern new hampshire university": "snhu.edu",
  "keene state college": "keene.edu",
  "plymouth state university": "plymouth.edu",
  "franklin pierce university": "franklinpierce.edu",
  "new england college": "nec.edu",
  "st mary's college of maryland": "smcm.edu",
  "goucher college": "goucher.edu",
  "mcdaniel college": "mcdaniel.edu",
  "hood college": "hood.edu",
  "stevenson university": "stevenson.edu",
  "maryland institute college of art": "mica.edu",
  "washington college": "washcoll.edu",
  "colby-sawyer college": "colby-sawyer.edu",
  "hampden-sydney college": "hsc.edu",
  "randolph-macon college": "rmc.edu",
  "roanoke college": "roanoke.edu",
  "emory & henry college": "ehc.edu",
  "hollins university": "hollins.edu",
  "sweet briar college": "sbc.edu",
  "shenandoah university": "su.edu",
  "lynchburg college": "lynchburg.edu",
  "bridgewater college": "bridgewater.edu",
  "eastern mennonite university": "emu.edu",
  "mary baldwin college": "marybaldwin.edu",
  "regent university": "regent.edu",
  "lees-mcrae college": "lmc.edu",
  "lenoir-rhyne university": "lr.edu",
  "guilford college": "guilford.edu",
  "greensboro college": "greensboro.edu",
  "meredith college": "meredith.edu",
  "campbell university": "campbell.edu",
  "gardner-webb university": "gardner-webb.edu",
  "catawba college": "catawba.edu",
  "wingate university": "wingate.edu",
  "barton college": "barton.edu",
  "fayetteville state university": "uncfsu.edu",
  "elizabeth city state university": "ecsu.edu",
  "winston-salem state university": "wssu.edu",
  "johnson c smith university": "jcsu.edu",
  "shaw university": "shawu.edu",
  "coker college": "coker.edu",
  "converse college": "converse.edu",
  "presbyterian college": "presby.edu",
  "newberry college": "newberry.edu",
  "erskine college": "erskine.edu",
  "lander university": "lander.edu",
  "berry college": "berry.edu",
  "oglethorpe university": "oglethorpe.edu",
  "mercer university": "mercer.edu",
  "savannah college of art and design": "scad.edu",
  "valdosta state university": "valdosta.edu",
  "columbus state university": "columbusstate.edu",
  "georgia college and state university": "gcsu.edu",
  "university of west georgia": "westga.edu",
  "university of north georgia": "ung.edu",
  "fort valley state university": "fvsu.edu",
  "savannah state university": "savannahstate.edu",
  "albany state university": "asurams.edu",
  "florida institute of technology": "fit.edu",
  "florida southern college": "flsouthern.edu",
  "eckerd college": "eckerd.edu",
  "stetson university": "stetson.edu",
  "jacksonville university": "ju.edu",
  "nova southeastern university": "nova.edu",
  "palm beach atlantic university": "pba.edu",
  "saint leo university": "saintleo.edu",
  "the university of tampa": "ut.edu",
  "lynn university": "lynn.edu",
  "barry university": "barry.edu",
  "bethune-cookman university": "cookman.edu",
  "flagler college-st augustine": "flagler.edu",
  "embry-riddle aeronautical university-daytona beach": "erau.edu",
  "embry-riddle aeronautical university-prescott": "erau.edu",
  "ringling college of art and design": "ringling.edu",
  "university of the west florida": "uwf.edu",
  "florida memorial university": "fmuniv.edu",
  "southeastern university": "seu.edu",
  "grand canyon university": "gcu.edu",
  "northern arizona university": "nau.edu",
  "prescott college": "prescott.edu",
  "arizona christian university": "arizonachristian.edu",
  "new mexico state university-main campus": "nmsu.edu",
  "new mexico institute of mining and technology": "nmt.edu",
  "eastern new mexico university-main campus": "enmu.edu",
  "new mexico highlands university": "nmhu.edu",
  "idaho state university": "isu.edu",
  "northwest nazarene university": "nnu.edu",
  "the college of idaho": "collegeofidaho.edu",
  "brigham young university-idaho": "byui.edu",
  "lewis-clark state college": "lcsc.edu",

  // -- Midwest Private --
  "saint louis university": "slu.edu",
  "rockhurst university": "rockhurst.edu",
  "webster university": "webster.edu",
  "lindenwood university": "lindenwood.edu",
  "drury university": "drury.edu",
  "maryville university of saint louis": "maryville.edu",
  "william jewell college": "jewell.edu",
  "baker university": "bakeru.edu",
  "emporia state university": "emporia.edu",
  "fort hays state university": "fhsu.edu",
  "pittsburg state university": "pittstate.edu",
  "wichita state university": "wichita.edu",
  "washburn university": "washburn.edu",
  "university of dayton": "udayton.edu",
  "xavier university": "xavier.edu",
  "miami university-oxford": "miamioh.edu",
  "miami university": "miamioh.edu",
  "ohio university-main campus": "ohio.edu",
  "bowling green state university-main campus": "bgsu.edu",
  "bowling green state university": "bgsu.edu",
  "kent state university at kent": "kent.edu",
  "kent state university": "kent.edu",
  "university of akron main campus": "uakron.edu",
  "university of akron": "uakron.edu",
  "cleveland state university": "csuohio.edu",
  "university of toledo": "utoledo.edu",
  "wright state university-main campus": "wright.edu",
  "wright state university": "wright.edu",
  "youngstown state university": "ysu.edu",
  "john carroll university": "jcu.edu",
  "baldwin wallace university": "bw.edu",
  "ohio northern university": "onu.edu",
  "ohio wesleyan university": "owu.edu",
  "otterbein university": "otterbein.edu",
  "capital university": "capital.edu",
  "muskingum university": "muskingum.edu",
  "wittenberg university": "wittenberg.edu",
  "cedarville university": "cedarville.edu",
  "ashland university": "ashland.edu",
  "hiram college": "hiram.edu",
  "marietta college": "marietta.edu",
  "tiffin university": "tiffin.edu",
  "ball state university": "bsu.edu",
  "indiana state university": "indstate.edu",
  "northern illinois university": "niu.edu",
  "southern illinois university-carbondale": "siu.edu",
  "southern illinois university-edwardsville": "siue.edu",
  "western michigan university": "wmich.edu",
  "central michigan university": "cmich.edu",
  "eastern michigan university": "emich.edu",
  "grand valley state university": "gvsu.edu",
  "wayne state university": "wayne.edu",
  "ferris state university": "ferris.edu",
  "michigan technological university": "mtu.edu",
  "northern michigan university": "nmu.edu",
  "saginaw valley state university": "svsu.edu",
  "lake superior state university": "lssu.edu",
  "western illinois university": "wiu.edu",
  "eastern illinois university": "eiu.edu",
  "illinois state university": "ilstu.edu",
  "illinois institute of technology": "iit.edu",
  "bradley university": "bradley.edu",
  "north central college": "noctrl.edu",
  "north park university": "northpark.edu",
  "elmhurst college": "elmhurst.edu",
  "millikin university": "millikin.edu",
  "monmouth college": "monmouthcollege.edu",
  "rockford university": "rockford.edu",
  "roosevelt university": "roosevelt.edu",
  "dominican university": "dom.edu",
  "olivet nazarene university": "olivet.edu",
  "quincy university": "quincy.edu",
  "university of st francis": "stfrancis.edu",
  "saint xavier university": "sxu.edu",
  "butler university": "butler.edu",
  "valparaiso university": "valpo.edu",
  "university of indianapolis": "uindy.edu",
  "university of evansville": "evansville.edu",
  "university of southern indiana": "usi.edu",
  "indiana wesleyan university": "indwes.edu",
  "rose-hulman institute of technology": "rose-hulman.edu",
  "taylor university": "taylor.edu",
  "trine university": "trine.edu",
  "hanover college": "hanover.edu",
  "franklin college": "franklincollege.edu",
  "manchester university": "manchester.edu",
  "anderson university": "anderson.edu",
  "saint mary's college": "saintmarys.edu",
  "goshen college": "goshen.edu",
  "university of wisconsin-milwaukee": "uwm.edu",
  "university of wisconsin-eau claire": "uwec.edu",
  "university of wisconsin-green bay": "uwgb.edu",
  "university of wisconsin-la crosse": "uwlax.edu",
  "university of wisconsin-oshkosh": "uwosh.edu",
  "university of wisconsin-whitewater": "uww.edu",
  "university of wisconsin-stout": "uwstout.edu",
  "university of wisconsin-platteville": "uwplatt.edu",
  "university of wisconsin-river falls": "uwrf.edu",
  "university of wisconsin-stevens point": "uwsp.edu",
  "university of wisconsin-parkside": "uwp.edu",
  "university of wisconsin-superior": "uwsuper.edu",
  "milwaukee school of engineering": "msoe.edu",
  "carthage college": "carthage.edu",
  "carroll university": "carrollu.edu",
  "st norbert college": "snc.edu",
  "concordia university-wisconsin": "cuw.edu",
  "augsburg college": "augsburg.edu",
  "hamline university": "hamline.edu",
  "bethel university": "bethel.edu",
  "university of saint thomas": "stthomas.edu",
  "saint mary's university of minnesota": "smumn.edu",
  "college of saint scholastica": "css.edu",
  "university of mary": "umary.edu",
  "kettering university": "kettering.edu",
  "oakland university": "oakland.edu",
  "spring arbor university": "arbor.edu",
  "cornerstone university": "cornerstone.edu",
  "andrews university": "andrews.edu",
  "adrián college": "adrian.edu",
  "adrian college": "adrian.edu",
  "siena heights university": "sienaheights.edu",
  "university of dubuque": "dbq.edu",
  "loras college": "loras.edu",
  "luther college": "luther.edu",
  "wartburg college": "wartburg.edu",
  "coe college": "coe.edu",
  "cornell college": "cornellcollege.edu",
  "simpson college": "simpson.edu",
  "dordt college": "dordt.edu",
  "buena vista university": "bvu.edu",
  "central college": "central.edu",
  "grand view university": "grandview.edu",
  "morningside college": "morningside.edu",
  "upper iowa university": "uiu.edu",
  "mount mercy university": "mtmercy.edu",
  "briar cliff university": "briarcliff.edu",
  "clarke university": "clarke.edu",
  "university of sioux falls": "usiouxfalls.edu",
  "south dakota school of mines and technology": "sdsmt.edu",
  "dakota state university": "dsu.edu",
  "black hills state university": "bhsu.edu",
  "northern state university": "northern.edu",
  "mayville state university": "mayvillestate.edu",
  "minot state university": "minotstateu.edu",
  "dickinson state university": "dickinsonstate.edu",
  "valley city state university": "vcsu.edu",
  "doane college": "doane.edu",
  "hastings college": "hastings.edu",
  "nebraska wesleyan university": "nebrwesleyan.edu",
  "peru state college": "peru.edu",
  "chadron state college": "csc.edu",
  "wayne state college": "wsc.edu",
  "concordia university-nebraska": "cune.edu",
  "midland university": "midlandu.edu",
  "bellevue university": "bellevue.edu",
  "western new mexico university": "wnmu.edu",
  "nevada state college": "nsc.edu",
  "hawaii pacific university": "hpu.edu",
  "chaminade university of honolulu": "chaminade.edu",
  "rocky mountain college": "rocky.edu",
  "carroll college": "carroll.edu",
  "montana state university-billings": "msubillings.edu",
  "colorado mesa university": "coloradomesa.edu",
  "adams state university": "adams.edu",
  "fort lewis college": "fortlewis.edu",
  "regis university": "regis.edu",
  "colorado christian university": "ccu.edu",
  "metropolitan state university of denver": "msudenver.edu",
  "naropa university": "naropa.edu",
  "western state colorado university": "western.edu",
  "colorado state university-pueblo": "csupueblo.edu",
  "colorado technical university-colorado springs": "coloradotech.edu",
  "willamette university": "willamette.edu",
  "linfield college": "linfield.edu",
  "george fox university": "georgefox.edu",
  "corban university": "corban.edu",
  "pacific university": "pacificu.edu",
  "western oregon university": "wou.edu",
  "eastern oregon university": "eou.edu",
  "oregon health & science university": "ohsu.edu",
  "oregon institute of technology": "oit.edu",
  "whitworth university": "whitworth.edu",
  "northwest university": "northwestu.edu",
  "walla walla university": "wallawalla.edu",
  "chapman university": "chapman.edu",
  "occidental college": "oxy.edu",
  "university of la verne": "laverne.edu",
  "university of the pacific": "pacific.edu",
  "university of redlands": "redlands.edu",
  "whittier college": "whittier.edu",
  "biola university": "biola.edu",
  "azusa pacific university": "apu.edu",
  "california baptist university": "calbaptist.edu",
  "california lutheran university": "callutheran.edu",
  "point loma nazarene university": "pointloma.edu",
  "fresno pacific university": "fresno.edu",
  "westmont college": "westmont.edu",
  "saint mary's college of california": "stmarys-ca.edu",
  "menlo college": "menlo.edu",
  "dominican university of california": "dominican.edu",
  "mills college": "mills.edu",
  "woodbury university": "woodbury.edu",
  "art center college of design": "artcenter.edu",
  "california institute of the arts": "calarts.edu",
  "otis college of art and design": "otis.edu",
  "san francisco conservatory of music": "sfcm.edu",
  "loma linda university": "llu.edu",
  "national university": "nu.edu",
  "university of mary hardin-baylor": "umhb.edu",
  "abilene christian university": "acu.edu",
  "hardin-simmons university": "hsutx.edu",
  "houston baptist university": "hbu.edu",
  "dallas baptist university": "dbu.edu",
  "university of dallas": "udallas.edu",
  "texas lutheran university": "tlu.edu",
  "texas wesleyan university": "txwes.edu",
  "austin college": "austincollege.edu",
  "trinity university": "trinity.edu",
  "st edward's university": "stedwards.edu",
  "st mary's university": "stmarytx.edu",
  "university of the incarnate word": "uiw.edu",
  "schreiner university": "schreiner.edu",
  "angelo state university": "angelo.edu",
  "tarleton state university": "tarleton.edu",
  "midwestern state university": "mwsu.edu",
  "west texas a & m university": "wtamu.edu",
  "lamar university": "lamar.edu",
  "letourneau university": "letu.edu",
  "mcmurry university": "mcm.edu",
  "lubbock christian university": "lcu.edu",
  "howard payne university": "hputx.edu",
  "prairie view a & m university": "pvamu.edu",
  "harding university": "harding.edu",
  "ouachita baptist university": "obu.edu",
  "henderson state university": "hsu.edu",
  "john brown university": "jbu.edu",
  "lyon college": "lyon.edu",
  "southern arkansas university main campus": "saumag.edu",
  "campbellsville university": "campbellsville.edu",
  "bellarmine university": "bellarmine.edu",
  "asbury university": "asbury.edu",
  "spalding university": "spalding.edu",
  "university of the cumberlands": "ucumberlands.edu",
  "university of pikeville": "upike.edu",
  "georgetown college": "georgetowncollege.edu",
  "lindsey wilson college": "lindsey.edu",
  "kentucky wesleyan college": "kwc.edu",
  "dillard university": "dillard.edu",
  "centenary college of louisiana": "centenary.edu",
  "louisiana college": "lacollege.edu",
  "fisk university": "fisk.edu",
  "maryville college": "maryvillecollege.edu",
  "milligan college": "milligan.edu",
  "carson-newman college": "cn.edu",
  "lee university": "leeuniversity.edu",
  "king university": "king.edu",
  "union university": "uu.edu",
  "tusculum college": "tusculum.edu",
  "southern adventist university": "southern.edu",
  "trevecca nazarene university": "trevecca.edu",
  "freed-hardeman university": "fhu.edu",
  "christian brothers university": "cbu.edu",
  "cumberland university": "cumberland.edu",
  "lincoln memorial university": "lmunet.edu",
  "charleston southern university": "csuniv.edu",
  "north greenville university": "ngu.edu",
  "southern wesleyan university": "swu.edu",
  "claflin university": "claflin.edu",
  "the citadel": "citadel.edu",
  "benedict college": "benedict.edu",
  "columbia international university": "ciu.edu",
  "limestone college": "limestone.edu",
  "bob jones university": "bju.edu",
  "united states military academy": "usma.edu",
  "united states naval academy": "usna.edu",
  "united states air force academy": "usafa.edu",
  "united states coast guard academy": "uscga.edu",
  "united states merchant marine academy": "usmma.edu",
  "gallaudet university": "gallaudet.edu",
  "catholic university of america": "cua.edu",
  "trinity washington university": "trinitydc.edu",
  "university of the district of columbia": "udc.edu",
  "notre dame of maryland university": "ndm.edu",
  "mount st mary's university": "msmary.edu",
  "wilmington university": "wilmu.edu",
  "goldey-beacom college": "gbc.edu",
  "post university": "post.edu",
  "mitchell college": "mitchell.edu",
  "hobart william smith colleges": "hws.edu",
  "houghton college": "houghton.edu",
  "wells college": "wells.edu",
  "nazareth college of rochester": "naz.edu",
  "mercy college": "mercy.edu",
  "molloy college": "molloy.edu",
  "manhattanville college": "mville.edu",
  "marymount manhattan college": "mmm.edu",
  "d'youville college": "dyc.edu",
  "long island university-brooklyn campus": "liu.edu",
  "long island university-c w post campus": "liu.edu",
  "westminster college": "westminstercollege.edu",
  "drew university": "drew.edu",
  "fairleigh dickinson university-metropolitan campus": "fdu.edu",
  "georgian court university": "georgian.edu",
  "william paterson university of new jersey": "wpunj.edu",
  "new jersey city university": "njcu.edu",
  "ramapo college of new jersey": "ramapo.edu",
  "saint joseph's college of maine": "sjcme.edu",
  "husson university": "husson.edu",
  "university of new england": "une.edu",
  "university of southern maine": "usm.maine.edu",
  "thomas college": "thomas.edu",
  "college of the atlantic": "coa.edu",
  "maine college of art": "meca.edu",
  "maine maritime academy": "mainemaritime.edu",
  "springfield college": "springfield.edu",
  "western new england university": "wne.edu",
  "wentworth institute of technology": "wit.edu",
  "gordon college": "gordon.edu",
  "endicott college": "endicott.edu",
  "marshall university": "marshall.edu",
  "shepherd university": "shepherd.edu",
  "concord university": "concord.edu",
  "fairmont state university": "fairmontstate.edu",
  "west liberty university": "westliberty.edu",
  "west virginia state university": "wvstateu.edu",
  "west virginia wesleyan college": "wvwc.edu",
  "wheeling jesuit university": "wju.edu",
  "university of charleston": "ucwv.edu",
  "davis & elkins college": "dewv.edu",
  "alderson-broaddus college": "ab.edu",
  "bethany college": "bethanywv.edu",
  "glenville state college": "glenville.edu",
  "bluefield state college": "bluefieldstate.edu",
  "viterbo university": "viterbo.edu",
  "wisconsin lutheran college": "wlc.edu",
  "edgewood college": "edgewood.edu",
  "marian university": "marian.edu",
  "mount mary university": "mtmary.edu",
  "cardinal stritch university": "stritch.edu",
  "alverno college": "alverno.edu",
  "concordia university-saint paul": "csp.edu",
  "concordia university-chicago": "cuchicago.edu",
  "concordia university-irvine": "cui.edu",
  "concordia university texas": "concordia.edu",
  "concordia university-portland": "cu-portland.edu",
  "point university": "point.edu",
  "covenant college": "covenant.edu",
  "toccoa falls college": "tfc.edu",
  "reinhardt university": "reinhardt.edu",
  "shorter university": "shorter.edu",
  "lagrange college": "lagrange.edu",
  "piedmont college": "piedmont.edu",
  "brenau university": "brenau.edu",
  "young harris college": "yhc.edu",
  "texas college": "texascol.edu",
  "paul quinn college": "pqc.edu",
  "jarvis christian college": "jarvis.edu",
  "wiley college": "wileyc.edu",
  "huston-tillotson university": "htu.edu",
  "our lady of the lake university": "ollusa.edu",
  "southwestern adventist university": "swau.edu",
  "east texas baptist university": "etbu.edu",
  "wayland baptist university": "wbu.edu",
  "southwest baptist university": "sbuniv.edu",
  "evangel university": "evangel.edu",
  "missouri baptist university": "mobap.edu",
  "missouri southern state university": "mssu.edu",
  "missouri western state university": "missouriwestern.edu",
  "missouri valley college": "moval.edu",
  "fontbonne university": "fontbonne.edu",
  "avila university": "avila.edu",
  "park university": "park.edu",
  "hannibal-lagrange university": "hlg.edu",
  "college of the ozarks": "cofo.edu",
  "culver-stockton college": "culver.edu",
  "stephens college": "stephens.edu",
  "william woods university": "williamwoods.edu",
  "central methodist university-college of liberal arts and sciences": "centralmethodist.edu",
  "harris-stowe state university": "hssu.edu",
  "lincoln university": "lincolnu.edu",
  "cameron university": "cameron.edu",
  "east central university": "ecok.edu",
  "langston university": "langston.edu",
  "northeastern state university": "nsuok.edu",
  "northwestern oklahoma state university": "nwosu.edu",
  "oklahoma panhandle state university": "opsu.edu",
  "oklahoma wesleyan university": "okwu.edu",
  "rogers state university": "rsu.edu",
  "southeastern oklahoma state university": "se.edu",
  "southern nazarene university": "snu.edu",
  "southwestern oklahoma state university": "swosu.edu",
  "university of science and arts of oklahoma": "usao.edu",
  "bainbridge state college": "bainbridge.edu",
  "dalton state college": "daltonstate.edu",
  "gordon state college": "gordonstate.edu",
  "south georgia college": "sgsc.edu",
  "college of coastal georgia": "ccga.edu",
  "east georgia state college": "ega.edu",
  "georgia highlands college": "highlands.edu",
  "georgia southwestern state university": "gsw.edu",
  "armstrong atlantic state university": "armstrong.edu",
  "clayton state university": "clayton.edu",
  "southern polytechnic state university": "spsu.edu",
  "thomas university": "thomasu.edu",
  "wesleyan college": "wesleyancollege.edu",
  "paine college": "paine.edu",
  "brewton-parker college": "bpc.edu",
  "truett-mcconnell college": "truett.edu",
  "emmanuel college": "ec.edu",
  "life university": "life.edu",
  "beulah heights university": "beulah.edu",
  "south university": "southuniversity.edu",
  "columbia college-chicago": "colum.edu",
  "shimer college": "shimer.edu",
  "eureka college": "eureka.edu",
  "greenville college": "greenville.edu",
  "blackburn college": "blackburn.edu",
  "principia college": "principia.edu",
  "mcmurray college": "mac.edu",
  "mckendree university": "mckendree.edu",
  "lewis university": "lewisu.edu",
  "benedictine university": "ben.edu",
  "governors state university": "govst.edu",
  "northeastern illinois university": "neiu.edu",
  "trinity christian college": "trnty.edu",
  "trinity international university-illinois": "tiu.edu",
  "judson university": "judsonu.edu",
  "lincoln christian university": "lincolnchristian.edu",
  "moody bible institute": "moody.edu",
  "national louis university": "nl.edu",
  "robert morris university illinois": "robertmorris.edu",
  "kendall college": "kendall.edu",
  "vandercook college of music": "vandercook.edu",
  "east-west university": "eastwest.edu",
  "saint augustine college": "staugustine.edu",
  "aurora university": "aurora.edu",
  "grace college and theological seminary": "grace.edu",
  "bethel college-indiana": "bethelcollege.edu",
  "huntington university": "huntington.edu",
  "indiana institute of technology": "indianatech.edu",
  "oakland city university": "oak.edu",
  "saint josephs college": "saintjoe.edu",
  "saint mary-of-the-woods college": "smwc.edu",
  "martin university": "martin.edu",
  "calumet college of saint joseph": "ccsj.edu",
  "holy cross college": "hcc-nd.edu",
  "allen college": "allencollege.edu",
  "graceland university-lamoni": "graceland.edu",
  "saint ambrose university": "sau.edu",
  "william penn university": "wmpenn.edu",
  "waldorf college": "waldorf.edu",
  "divine word college": "dwci.edu",
  "emmaus bible college": "emmaus.edu",
  "newman university": "newmanu.edu",
  "benedictine college": "benedictine.edu",
  "midamerica nazarene university": "mnu.edu",
  "friends university": "friends.edu",
  "kansas wesleyan university": "kwu.edu",
  "university of saint mary": "stmary.edu",
  "ottawa university-ottawa": "ottawa.edu",
  "mcpherson college": "mcpherson.edu",
  "sterling college": "sterling.edu",
  "tabor college": "tabor.edu",
  "barclay college": "barclaycollege.edu",
  "alice lloyd college": "alc.edu",
  "brescia university": "brescia.edu",
  "thomas more college": "thomasmore.edu",
  "kentucky christian university": "kcu.edu",
  "midway college": "midway.edu",
};

export const collegeDomains = new Map(Object.entries(domains));
