export const collegeNames = [
  "Alabama A & M University",
  "University of Alabama at Birmingham",
  "Amridge University",
  "University of Alabama in Huntsville",
  "Alabama State University",
  "The University of Alabama",
  "Auburn University at Montgomery",
  "Auburn University",
  "Birmingham Southern College",
  "Faulkner University",
  "Huntingdon College",
  "Jacksonville State University",
  "Judson College",
  "University of West Alabama",
  "Miles College",
  "University of Mobile",
  "University of Montevallo",
  "University of North Alabama",
  "Oakwood University",
  "Samford University",
  "Stillman College",
  "Talladega College",
  "Troy University",
  "Tuskegee University",
  "University of Alaska Anchorage",
  "University of Alaska Fairbanks",
  "University of Alaska Southeast",
  "Alaska Pacific University",
  "Arizona State University-Tempe",
  "Arizona Western College",
  "University of Arizona",
  "Central Arizona College",
  "Cochise College",
  "Eastern Arizona College",
  "Embry-Riddle Aeronautical University-Prescott",
  "Glendale Community College",
  "Grand Canyon University",
  "Mesa Community College",
  "Northern Arizona University",
  "Phoenix College",
  "University of Phoenix-Phoenix Campus",
  "Pima Community College",
  "Prescott College",
  "Scottsdale Community College",
  "Arizona Christian University",
  "Yavapai College",
  "University of Arkansas at Little Rock",
  "University of Arkansas for Medical Sciences",
  "Lyon College",
  "University of Arkansas",
  "University of Arkansas at Pine Bluff",
  "Arkansas State University-Beebe",
  "Arkansas State University-Main Campus",
  "Arkansas Tech University",
  "University of Arkansas at Monticello",
  "University of Central Arkansas",
  "Central Baptist College",
  "Harding University",
  "Henderson State University",
  "Hendrix College",
  "John Brown University",
  "Ouachita Baptist University",
  "University of the Ozarks",
  "Philander Smith College",
  "Southern Arkansas University Main Campus",
  "University of Arkansas-Fort Smith",
  "Williams Baptist College",
  "Academy of Art University",
  "College of Alameda",
  "Allan Hancock College",
  "American River College",
  "Antelope Valley College",
  "Art Center College of Design",
  "Azusa Pacific University",
  "Bakersfield College",
  "Biola University",
  "Butte College",
  "Cabrillo College",
  "California Baptist University",
  "California College of the Arts",
  "California Institute of Technology",
  "California Lutheran University",
  "California Polytechnic State University-San Luis Obispo",
  "California State University-Bakersfield",
  "California State University-Stanislaus",
  "California State University-San Bernardino",
  "California State Polytechnic University-Pomona",
  "California State University-Chico",
  "California State University-Dominguez Hills",
  "California State University-Fresno",
  "California State University-Fullerton",
  "California State University-East Bay",
  "California State University-Long Beach",
  "California State University-Los Angeles",
  "California State University-Northridge",
  "California State University-Sacramento",
  "University of California-Berkeley",
  "University of California-Davis",
  "University of California-Irvine",
  "University of California-Los Angeles",
  "University of California-Riverside",
  "University of California-San Diego",
  "University of California-San Francisco",
  "University of California-Santa Barbara",
  "University of California-Santa Cruz",
  "California Institute of the Arts",
  "California Maritime Academy",
  "Canada College",
  "College of the Canyons",
  "Cerritos College",
  "Cerro Coso Community College",
  "Chabot College",
  "Chaffey College",
  "Chapman University",
  "Concordia University-Irvine",
  "San Diego Christian College",
  "Citrus College",
  "City College of San Francisco",
  "Claremont Graduate University",
  "Claremont McKenna College",
  "Coastline Community College",
  "Columbia College",
  "Contra Costa College",
  "Cosumnes River College",
  "Crafton Hills College",
  "Cuesta College",
  "Cuyamaca College",
  "Cypress College",
  "De Anza College",
  "College of the Desert",
  "Diablo Valley College",
  "Dominican University of California",
  "East Los Angeles College",
  "El Camino Community College District",
  "Evergreen Valley College",
  "Feather River Community College District",
  "Foothill College",
  "Fresno City College",
  "Fresno Pacific University",
  "Fuller Theological Seminary in California",
  "Fullerton College",
  "Gavilan College",
  "Glendale Community College",
  "Golden Gate University-San Francisco",
  "Golden West College",
  "Grossmont College",
  "Hartnell College",
  "Harvey Mudd College",
  "Holy Names University",
  "Humboldt State University",
  "Imperial Valley College",
  "Irvine Valley College",
  "John F Kennedy University",
  "Reedley College",
  "Life Pacific College",
  "University of La Verne",
  "Laguna College of Art and Design",
  "Lake Tahoe Community College",
  "Laney College",
  "Lassen Community College",
  "Life Chiropractic College West",
  "Lincoln University",
  "La Sierra University",
  "Loma Linda University",
  "Long Beach City College",
  "Los Angeles Harbor College",
  "Los Angeles Pierce College",
  "Los Angeles Southwest College",
  "Los Angeles Trade Technical College",
  "Los Angeles Valley College",
  "The Master's College and Seminary",
  "Los Angeles City College",
  "Los Angeles Mission College",
  "Los Medanos College",
  "Loyola Marymount University",
  "College of Marin",
  "Marymount California University",
  "Mendocino College",
  "Menlo College",
  "Merced College",
  "Merritt College",
  "Mills College",
  "MiraCosta College",
  "Mission College",
  "Modesto Junior College",
  "Monterey Peninsula College",
  "Moorpark College",
  "Mt San Antonio College",
  "Mount St Mary's College",
  "Mt San Jacinto Community College District",
  "Musicians Institute",
  "Napa Valley College",
  "National University",
  "Naval Postgraduate School",
  "Occidental College",
  "Ohlone College",
  "Orange Coast College",
  "Otis College of Art and Design",
  "Oxnard College",
  "Hope International University",
  "Pacific Lutheran Theological Seminary",
  "Pacific Oaks College",
  "Pacific Union College",
  "University of the Pacific",
  "Palo Verde College",
  "Palomar College",
  "Pasadena City College",
  "Pepperdine University",
  "Pitzer College",
  "Point Loma Nazarene University",
  "Pomona College",
  "Porterville College",
  "Santa Ana College",
  "University of Redlands",
  "College of the Redwoods",
  "Rio Hondo College",
  "Riverside City College",
  "Sacramento City College",
  "Saddleback College",
  "Samuel Merritt University",
  "San Diego City College",
  "San Diego Mesa College",
  "San Diego Miramar College",
  "San Diego State University",
  "University of San Diego",
  "San Francisco Art Institute",
  "San Francisco Conservatory of Music",
  "San Francisco State University",
  "University of San Francisco",
  "San Joaquin Delta College",
  "William Jessup University",
  "San Jose City College",
  "San Jose State University",
  "College of San Mateo",
  "Santa Barbara City College",
  "Santa Clara University",
  "Santa Monica College",
  "Santa Rosa Junior College",
  "Scripps College",
  "College of the Sequoias",
  "Shasta College",
  "Sierra College",
  "Simpson University",
  "College of the Siskiyous",
  "Skyline College",
  "San Bernardino Valley College",
  "Saint Mary's College of California",
  "Solano Community College",
  "Sonoma State University",
  "Vanguard University of Southern California",
  "Southwestern College",
  "University of Southern California",
  "Taft College",
  "Thomas Aquinas College",
  "Ventura College",
  "Victor Valley College",
  "Berkeley City College",
  "West Hills College-Coalinga",
  "West Los Angeles College",
  "West Valley College",
  "Westmont College",
  "Whittier College",
  "Woodbury University",
  "Yuba College",
  "Adams State University",
  "Aims Community College",
  "Arapahoe Community College",
  "University of Colorado Denver",
  "University of Colorado Colorado Springs",
  "University of Colorado Boulder",
  "Colorado Christian University",
  "Colorado College",
  "Colorado Mountain College",
  "Colorado Northwestern Community College",
  "Colorado School of Mines",
  "Colorado State University-Fort Collins",
  "Colorado Technical University-Colorado Springs",
  "Community College of Aurora",
  "Community College of Denver",
  "Denver Seminary",
  "University of Denver",
  "Fort Lewis College",
  "Front Range Community College",
  "Lamar Community College",
  "Colorado Mesa University",
  "Metropolitan State University of Denver",
  "Morgan Community College",
  "Naropa University",
  "Northeastern Junior College",
  "University of Northern Colorado",
  "Otero Junior College",
  "Pikes Peak Community College",
  "Pueblo Community College",
  "Red Rocks Community College",
  "Regis University",
  "Rocky Mountain College of Art and Design",
  "Colorado State University-Pueblo",
  "Trinidad State Junior College",
  "United States Air Force Academy",
  "Western State Colorado University",
  "Albertus Magnus College",
  "Asnuntuck Community College",
  "University of Bridgeport",
  "Central Connecticut State University",
  "Charter Oak State College",
  "Connecticut College",
  "University of Connecticut",
  "Eastern Connecticut State University",
  "Fairfield University",
  "Capital Community College",
  "University of Hartford",
  "Holy Apostles College and Seminary",
  "Housatonic Community College",
  "Manchester Community College",
  "Naugatuck Valley Community College",
  "Middlesex Community College",
  "Mitchell College",
  "Three Rivers Community College",
  "University of New Haven",
  "Norwalk Community College",
  "Northwestern Connecticut Community College",
  "Post University",
  "Quinebaug Valley Community College",
  "Quinnipiac University",
  "Sacred Heart University",
  "University of Saint Joseph",
  "Gateway Community College",
  "Southern Connecticut State University",
  "Trinity College",
  "Tunxis Community College",
  "United States Coast Guard Academy",
  "Wesleyan University",
  "Western Connecticut State University",
  "Yale University",
  "Delaware State University",
  "University of Delaware",
  "Goldey-Beacom College",
  "Wesley College",
  "Wilmington University",
  "American University",
  "Catholic University of America",
  "University of the District of Columbia",
  "Gallaudet University",
  "George Washington University",
  "Georgetown University",
  "Howard University",
  "Trinity Washington University",
  "The Baptist College of Florida",
  "Barry University",
  "Bethune-Cookman University",
  "Lynn University",
  "Eastern Florida State College",
  "Broward College",
  "College of Central Florida",
  "University of Central Florida",
  "Chipola College",
  "Daytona State College",
  "Eckerd College",
  "Edison State College",
  "Edward Waters College",
  "Embry-Riddle Aeronautical University-Daytona Beach",
  "Florida Agricultural and Mechanical University",
  "Florida Atlantic University",
  "Florida State College at Jacksonville",
  "Flagler College-St Augustine",
  "Florida College",
  "Adventist University of Health Sciences",
  "Florida Institute of Technology",
  "Florida International University",
  "Florida Keys Community College",
  "Florida Memorial University",
  "Florida Southern College",
  "Florida State University",
  "University of Florida",
  "Full Sail University",
  "Gulf Coast State College",
  "Hillsborough Community College",
  "Indian River State College",
  "Jacksonville University",
  "Keiser University-Ft Lauderdale",
  "Florida Gateway College",
  "Lake-Sumter State College",
  "State College of Florida-Manatee-Sarasota",
  "Miami Dade College",
  "University of Miami",
  "North Florida Community College",
  "University of North Florida",
  "Nova Southeastern University",
  "Northwest Florida State College",
  "Palm Beach Atlantic University",
  "Palm Beach State College",
  "Pasco-Hernando Community College",
  "Pensacola State College",
  "Polk State College",
  "Ringling College of Art and Design",
  "Rollins College",
  "Saint Leo University",
  "St Petersburg College",
  "Santa Fe College",
  "Seminole State College of Florida",
  "Saint Johns River State College",
  "South Florida State College",
  "University of South Florida-Main Campus",
  "St Thomas University",
  "Stetson University",
  "Southeastern University",
  "Tallahassee Community College",
  "The University of Tampa",
  "Trinity Baptist College",
  "Trinity College of Florida",
  "Valencia College",
  "Warner University",
  "Webber International University",
  "The University of West Florida",
  "Abraham Baldwin Agricultural College",
  "Agnes Scott College",
  "Albany State University",
  "Andrew College",
  "Armstrong Atlantic State University",
  "The Art Institute of Atlanta",
  "Point University",
  "Atlanta Metropolitan State College",
  "Clark Atlanta University",
  "Augusta State University",
  "Bainbridge State College",
  "Berry College",
  "Beulah Heights University",
  "Brenau University",
  "Brewton-Parker College",
  "College of Coastal Georgia",
  "Clayton State University",
  "Columbus State University",
  "Covenant College",
  "Dalton State College",
  "East Georgia State College",
  "Emmanuel College",
  "Emory University",
  "Georgia Highlands College",
  "Fort Valley State University",
  "Georgia Institute of Technology-Main Campus",
  "Georgia Southwestern State University",
  "Gainesville State College",
  "Georgia College and State University",
  "Georgia Military College",
  "Georgia Southern University",
  "Georgia State University",
  "University of Georgia",
  "Gordon State College",
  "Kennesaw State University",
  "LaGrange College",
  "Life University",
  "Macon State College",
  "Georgia Health Sciences University",
  "Mercer University",
  "Middle Georgia College",
  "Morehouse College",
  "Morehouse School of Medicine",
  "University of North Georgia",
  "Oglethorpe University",
  "Paine College",
  "Piedmont College",
  "Reinhardt University",
  "Savannah College of Art and Design",
  "Savannah State University",
  "Shorter University",
  "South Georgia College",
  "Spelman College",
  "Southern Polytechnic State University",
  "Thomas University",
  "Toccoa Falls College",
  "Truett-McConnell College",
  "Valdosta State University",
  "Wesleyan College",
  "University of West Georgia",
  "Young Harris College",
  "Chaminade University of Honolulu",
  "University of Hawaii at Hilo",
  "University of Hawaii at Manoa",
  "Hawaii Pacific University",
  "Honolulu Community College",
  "Kapiolani Community College",
  "Kauai Community College",
  "Leeward Community College",
  "University of Hawaii Maui College",
  "University of Hawaii-West Oahu",
  "Windward Community College",
  "Boise State University",
  "Idaho State University",
  "University of Idaho",
  "The College of Idaho",
  "Lewis-Clark State College",
  "North Idaho College",
  "Northwest Nazarene University",
  "Brigham Young University-Idaho",
  "College of Southern Idaho",
  "Augustana College",
  "Aurora University",
  "Southwestern Illinois College",
  "Black Hawk College",
  "Blackburn College",
  "Bradley University",
  "Carl Sandburg College",
  "University of Chicago",
  "City Colleges of Chicago-Kennedy-King College",
  "City Colleges of Chicago-Malcolm X College",
  "City Colleges of Chicago-Olive-Harvey College",
  "City Colleges of Chicago-Harry S Truman College",
  "City Colleges of Chicago-Richard J Daley College",
  "City Colleges of Chicago-Harold Washington College",
  "City Colleges of Chicago-Wilbur Wright College",
  "Columbia College-Chicago",
  "Concordia University-Chicago",
  "DePaul University",
  "DeVry University-Illinois",
  "College of DuPage",
  "East-West University",
  "Eastern Illinois University",
  "Elgin Community College",
  "Elmhurst College",
  "Eureka College",
  "Governors State University",
  "Greenville College",
  "Highland Community College",
  "University of Illinois at Chicago",
  "Benedictine University",
  "Illinois College of Optometry",
  "University of Illinois at Urbana-Champaign",
  "Illinois Wesleyan University",
  "Illinois Central College",
  "Illinois College",
  "Illinois Institute of Technology",
  "Illinois State University",
  "Illinois Valley Community College",
  "John A Logan College",
  "John Wood Community College",
  "Joliet Junior College",
  "Judson University",
  "Kankakee Community College",
  "Kaskaskia College",
  "Kendall College",
  "Kishwaukee College",
  "Knox College",
  "College of Lake County",
  "Lake Forest College",
  "Lake Land College",
  "Lewis and Clark Community College",
  "Lewis University",
  "Lincoln Christian University",
  "Lincoln College",
  "Lincoln Land Community College",
  "Loyola University Chicago",
  "MacMurray College",
  "McHenry County College",
  "McKendree University",
  "Millikin University",
  "Monmouth College",
  "Moody Bible Institute",
  "Moraine Valley Community College",
  "Morrison Institute of Technology",
  "Morton College",
  "National Louis University",
  "North Central College",
  "North Park University",
  "Northern Illinois University",
  "Northwestern University",
  "Northeastern Illinois University",
  "Oakton Community College",
  "Olivet Nazarene University",
  "Parkland College",
  "Prairie State College",
  "Principia College",
  "Quincy University",
  "Rend Lake College",
  "Richland Community College",
  "Robert Morris University Illinois",
  "Rock Valley College",
  "Rockford University",
  "Roosevelt University",
  "Dominican University",
  "Rush University",
  "University of St Francis",
  "Saint Xavier University",
  "University of Illinois at Springfield",
  "Sauk Valley Community College",
  "Shawnee Community College",
  "Shimer College",
  "Saint Augustine College",
  "Southeastern Illinois College",
  "Spoon River College",
  "Southern Illinois University-Carbondale",
  "Southern Illinois University-Edwardsville",
  "South Suburban College",
  "Trinity Christian College",
  "Trinity International University-Illinois",
  "Triton College",
  "VanderCook College of Music",
  "Waubonsee Community College",
  "Western Illinois University",
  "Wheaton College",
  "Harper College",
  "Anderson University",
  "Ball State University",
  "Bethel College-Indiana",
  "Butler University",
  "Calumet College of Saint Joseph",
  "DePauw University",
  "Earlham College",
  "University of Evansville",
  "Franklin College",
  "Goshen College",
  "Grace College and Theological Seminary",
  "Hanover College",
  "Holy Cross College",
  "Huntington University",
  "Ivy Tech Community College",
  "Indiana University-Purdue University-Fort Wayne",
  "Indiana University-Purdue University-Indianapolis",
  "University of Indianapolis",
  "Indiana Institute of Technology",
  "University of Southern Indiana",
  "Indiana State University",
  "Indiana University-Kokomo",
  "Indiana University-South Bend",
  "Indiana University-Bloomington",
  "Indiana University-Northwest",
  "Indiana University-Southeast",
  "Indiana University-East",
  "Manchester University",
  "Marian University",
  "Indiana Wesleyan University",
  "Martin University",
  "University of Notre Dame",
  "Oakland City University",
  "Purdue University-Calumet Campus",
  "Purdue University-North Central Campus",
  "Rose-Hulman Institute of Technology",
  "University of Saint Francis-Fort Wayne",
  "Saint Josephs College",
  "Saint Mary-of-the-Woods College",
  "Saint Mary's College",
  "Taylor University",
  "Trine University",
  "Valparaiso University",
  "Vincennes University",
  "Wabash College",
  "Purdue University-Main Campus",
  "Allen College",
  "Briar Cliff University",
  "Buena Vista University",
  "Central College",
  "Clarke University",
  "Coe College",
  "Cornell College",
  "Des Moines Area Community College",
  "Divine Word College",
  "Dordt College",
  "Drake University",
  "University of Dubuque",
  "Ellsworth Community College",
  "Emmaus Bible College",
  "Graceland University-Lamoni",
  "Grand View University",
  "Grinnell College",
  "Hawkeye Community College",
  "Indian Hills Community College",
  "Iowa Central Community College",
  "Iowa Lakes Community College",
  "Iowa State University",
  "Iowa Wesleyan College",
  "Iowa Western Community College",
  "University of Iowa",
  "Kirkwood Community College",
  "Loras College",
  "Luther College",
  "Maharishi University of Management",
  "Marshalltown Community College",
  "Mercy College of Health Sciences",
  "Morningside College",
  "Mount Mercy University",
  "North Iowa Area Community College",
  "University of Northern Iowa",
  "Northwestern College",
  "Northeast Iowa Community College-Calmar",
  "Northwest Iowa Community College",
  "Palmer College of Chiropractic-Davenport",
  "Saint Ambrose University",
  "Simpson College",
  "Southeastern Community College",
  "Southwestern Community College",
  "Upper Iowa University",
  "Waldorf College",
  "Wartburg College",
  "Western Iowa Tech Community College",
  "William Penn University",
  "Allen County Community College",
  "Baker University",
  "Barton County Community College",
  "Benedictine College",
  "Bethany College",
  "Bethel College-North Newton",
  "Butler Community College",
  "Central Christian College of Kansas",
  "Cloud County Community College",
  "Coffeyville Community College",
  "Colby Community College",
  "Cowley County Community College",
  "Dodge City Community College",
  "Donnelly College",
  "Emporia State University",
  "Fort Hays State University",
  "Barclay College",
  "Friends University",
  "Fort Scott Community College",
  "Garden City Community College",
  "Haskell Indian Nations University",
  "Hesston College",
  "Highland Community College",
  "Hutchinson Community College",
  "Independence Community College",
  "Johnson County Community College",
  "Kansas City Kansas Community College",
  "University of Kansas",
  "Newman University",
  "Kansas State University",
  "Kansas Wesleyan University",
  "Labette Community College",
  "Manhattan Christian College",
  "McPherson College",
  "MidAmerica Nazarene University",
  "Neosho County Community College",
  "Ottawa University-Ottawa",
  "Pittsburg State University",
  "Pratt Community College",
  "University of Saint Mary",
  "Southwestern College",
  "Sterling College",
  "Tabor College",
  "Washburn University",
  "Wichita State University",
  "Alice Lloyd College",
  "Asbury University",
  "Asbury Theological Seminary",
  "Bellarmine University",
  "Berea College",
  "Brescia University",
  "Campbellsville University",
  "Centre College",
  "University of the Cumberlands",
  "Eastern Kentucky University",
  "Georgetown College",
  "Kentucky State University",
  "Kentucky Wesleyan College",
  "University of Kentucky",
  "Kentucky Christian University",
  "Lindsey Wilson College",
  "University of Louisville",
  "Midway College",
  "Morehead State University",
  "Murray State University",
  "Northern Kentucky University",
  "University of Pikeville",
  "Spalding University",
  "Thomas More College",
  "Transylvania University",
  "Union College",
  "Western Kentucky University",
  "Centenary College of Louisiana",
  "Delgado Community College",
  "Dillard University",
  "Grambling State University",
  "Louisiana State University Health Sciences Center-New Orleans",
  "Louisiana State University-Alexandria",
  "Louisiana State University and Agricultural & Mechanical College",
  "Louisiana State University-Eunice",
  "Louisiana State University-Shreveport",
  "Louisiana College",
  "Louisiana Tech University",
  "Loyola University New Orleans",
  "McNeese State University",
  "University of New Orleans",
  "Nicholls State University",
  "University of Louisiana at Monroe",
  "Northwestern State University of Louisiana",
  "Our Lady of Holy Cross College",
  "Our Lady of the Lake College",
  "Southeastern Louisiana University",
  "Southern University and A & M College",
  "Southern University at New Orleans",
  "Southern University at Shreveport",
  "University of Louisiana at Lafayette",
  "Tulane University of Louisiana",
  "Xavier University of Louisiana",
  "College of the Atlantic",
  "Bates College",
  "Bowdoin College",
  "Central Maine Community College",
  "Colby College",
  "Eastern Maine Community College",
  "Husson University",
  "Kennebec Valley Community College",
  "University of Maine at Augusta",
  "University of Maine at Farmington",
  "University of Maine at Fort Kent",
  "University of Maine at Machias",
  "University of Maine",
  "Maine Maritime Academy",
  "University of Maine at Presque Isle",
  "University of New England",
  "Northern Maine Community College",
  "Maine College of Art",
  "Saint Joseph's College of Maine",
  "Southern Maine Community College",
  "University of Southern Maine",
  "Thomas College",
  "Unity College",
  "Washington County Community College",
  "Allegany College of Maryland",
  "Anne Arundel Community College",
  "Baltimore City Community College",
  "University of Baltimore",
  "Bowie State University",
  "Capitol College",
  "Cecil College",
  "College of Southern Maryland",
  "Chesapeake College",
  "Washington Adventist University",
  "Coppin State University",
  "Frostburg State University",
  "Goucher College",
  "Hood College",
  "Johns Hopkins University",
  "Loyola University Maryland",
  "University of Maryland-Baltimore County",
  "University of Maryland-College Park",
  "University of Maryland Eastern Shore",
  "University of Maryland University College",
  "Maryland Institute College of Art",
  "McDaniel College",
  "Morgan State University",
  "Mount St Mary's University",
  "Notre Dame of Maryland University",
  "Prince George's Community College",
  "St Mary's College of Maryland",
  "Salisbury University",
  "Stevenson University",
  "Towson University",
  "United States Naval Academy",
  "Washington College",
  "Amherst College",
  "Boston College",
  "Boston University",
  "Brandeis University",
  "Bridgewater State University",
  "Clark University",
  "College of the Holy Cross",
  "Emerson College",
  "Fitchburg State University",
  "Framingham State University",
  "Gordon College",
  "Hampshire College",
  "Harvard University",
  "Massachusetts Institute of Technology",
  "Lesley University",
  "University of Massachusetts-Amherst",
  "University of Massachusetts-Boston",
  "University of Massachusetts-Dartmouth",
  "University of Massachusetts-Lowell",
  "Merrimack College",
  "Mount Holyoke College",
  "Northeastern University",
  "Salem State University",
  "Simmons College",
  "Smith College",
  "Springfield College",
  "Stonehill College",
  "Suffolk University",
  "Tufts University",
  "Wellesley College",
  "Wentworth Institute of Technology",
  "Western New England University",
  "Westfield State University",
  "Wheaton College",
  "Williams College",
  "Worcester Polytechnic Institute",
  "Worcester State University",
  "Adrian College",
  "Albion College",
  "Alma College",
  "Andrews University",
  "Aquinas College",
  "Calvin College",
  "Central Michigan University",
  "Cornerstone University",
  "Eastern Michigan University",
  "Ferris State University",
  "Grand Valley State University",
  "Hillsdale College",
  "Hope College",
  "Kalamazoo College",
  "Kettering University",
  "Lake Superior State University",
  "Lawrence Technological University",
  "Madonna University",
  "Marygrove College",
  "University of Michigan-Ann Arbor",
  "University of Michigan-Dearborn",
  "University of Michigan-Flint",
  "Michigan State University",
  "Michigan Technological University",
  "Northern Michigan University",
  "Northwood University-Michigan",
  "Oakland University",
  "Olivet College",
  "Rochester College",
  "Saginaw Valley State University",
  "Siena Heights University",
  "Spring Arbor University",
  "Wayne State University",
  "Western Michigan University",
  "Augsburg College",
  "Bemidji State University",
  "Bethel University",
  "Carleton College",
  "College of Saint Benedict",
  "Concordia College at Moorhead",
  "Concordia University-Saint Paul",
  "Gustavus Adolphus College",
  "Hamline University",
  "Macalester College",
  "Minneapolis College of Art and Design",
  "Minnesota State University-Mankato",
  "Minnesota State University Moorhead",
  "University of Minnesota-Duluth",
  "University of Minnesota-Morris",
  "University of Minnesota-Twin Cities",
  "Saint Cloud State University",
  "Saint Johns University",
  "College of Saint Scholastica",
  "Saint Mary's University of Minnesota",
  "Saint Olaf College",
  "University of Saint Thomas",
  "Southwest Minnesota State University",
  "Winona State University",
  "Alcorn State University",
  "Belhaven University",
  "Blue Mountain College",
  "Delta State University",
  "Jackson State University",
  "Millsaps College",
  "Mississippi College",
  "Mississippi State University",
  "Mississippi University for Women",
  "Mississippi Valley State University",
  "University of Mississippi",
  "University of Southern Mississippi",
  "Rust College",
  "Tougaloo College",
  "William Carey University",
  "Avila University",
  "Central Methodist University-College of Liberal Arts and Sciences",
  "College of the Ozarks",
  "Columbia College",
  "Culver-Stockton College",
  "Drury University",
  "Evangel University",
  "Fontbonne University",
  "Hannibal-LaGrange University",
  "Harris-Stowe State University",
  "Lincoln University",
  "Lindenwood University",
  "Maryville University of Saint Louis",
  "University of Central Missouri",
  "Missouri Baptist University",
  "Missouri Southern State University",
  "Missouri State University-Springfield",
  "University of Missouri-Columbia",
  "University of Missouri-Kansas City",
  "University of Missouri-St Louis",
  "Missouri University of Science and Technology",
  "Missouri Valley College",
  "Missouri Western State University",
  "Northwest Missouri State University",
  "Park University",
  "Rockhurst University",
  "Saint Louis University",
  "Southeast Missouri State University",
  "Southwest Baptist University",
  "Stephens College",
  "Truman State University",
  "Washington University in St Louis",
  "Webster University",
  "Westminster College",
  "William Jewell College",
  "William Woods University",
  "Carroll College",
  "Montana State University",
  "Montana State University-Billings",
  "Montana State University-Northern",
  "Montana Tech of the University of Montana",
  "Rocky Mountain College",
  "University of Great Falls",
  "University of Montana",
  "University of Montana-Western",
  "Bellevue University",
  "Chadron State College",
  "Clarkson College",
  "College of Saint Mary",
  "Concordia University-Nebraska",
  "Creighton University",
  "Doane College",
  "Grace University",
  "Hastings College",
  "Midland University",
  "Nebraska Methodist College of Nursing & Allied Health",
  "Nebraska Wesleyan University",
  "University of Nebraska at Kearney",
  "University of Nebraska at Omaha",
  "University of Nebraska-Lincoln",
  "Peru State College",
  "Union College",
  "Wayne State College",
  "York College",
  "University of Nevada-Las Vegas",
  "University of Nevada-Reno",
  "Nevada State College",
  "Sierra Nevada College",
  "Truckee Meadows Community College",
  "Western Nevada College",
  "Colby-Sawyer College",
  "Dartmouth College",
  "Franklin Pierce University",
  "Keene State College",
  "University of New Hampshire-Main Campus",
  "New England College",
  "Plymouth State University",
  "Rivier University",
  "Saint Anselm College",
  "Southern New Hampshire University",
  "Thomas More College of the Liberal Arts",
  "Bloomfield College",
  "Caldwell College",
  "Centenary College",
  "The College of New Jersey",
  "College of Saint Elizabeth",
  "Drew University",
  "Fairleigh Dickinson University-Metropolitan Campus",
  "Felician College",
  "Georgian Court University",
  "Kean University",
  "Monmouth University",
  "Montclair State University",
  "New Jersey City University",
  "New Jersey Institute of Technology",
  "Princeton University",
  "Ramapo College of New Jersey",
  "Rider University",
  "Rowan University",
  "Rutgers University-Camden",
  "Rutgers University-New Brunswick",
  "Rutgers University-Newark",
  "Saint Peter's University",
  "Seton Hall University",
  "Stevens Institute of Technology",
  "Stockton University",
  "William Paterson University of New Jersey",
  "Eastern New Mexico University-Main Campus",
  "New Mexico Highlands University",
  "New Mexico Institute of Mining and Technology",
  "New Mexico State University-Main Campus",
  "University of New Mexico-Main Campus",
  "St John's College",
  "University of the Southwest",
  "Western New Mexico University",
  "Adelphi University",
  "Alfred University",
  "Bard College",
  "Barnard College",
  "Canisius College",
  "Clarkson University",
  "Colgate University",
  "Columbia University in the City of New York",
  "Cooper Union for the Advancement of Science and Art",
  "Cornell University",
  "CUNY Bernard M Baruch College",
  "CUNY Brooklyn College",
  "CUNY City College",
  "CUNY College of Staten Island",
  "CUNY Hunter College",
  "CUNY John Jay College of Criminal Justice",
  "CUNY Lehman College",
  "CUNY Queens College",
  "CUNY York College",
  "D'Youville College",
  "Dominican College of Blauvelt",
  "Fordham University",
  "Hamilton College",
  "Hartwick College",
  "Hobart William Smith Colleges",
  "Hofstra University",
  "Houghton College",
  "Iona College",
  "Ithaca College",
  "Le Moyne College",
  "Long Island University-Brooklyn Campus",
  "Long Island University-C W Post Campus",
  "Manhattan College",
  "Manhattanville College",
  "Marist College",
  "Marymount Manhattan College",
  "Mercy College",
  "Molloy College",
  "Mount Saint Mary College",
  "Nazareth College of Rochester",
  "The New School",
  "New York Institute of Technology",
  "New York University",
  "Niagara University",
  "Pace University-New York",
  "Polytechnic Institute of New York University",
  "Pratt Institute-Main",
  "Rensselaer Polytechnic Institute",
  "Rochester Institute of Technology",
  "University of Rochester",
  "The Sage Colleges",
  "St Bonaventure University",
  "St John Fisher College",
  "St John's University-New York",
  "St Lawrence University",
  "Sarah Lawrence College",
  "Siena College",
  "Skidmore College",
  "SUNY at Albany",
  "SUNY at Binghamton",
  "University at Buffalo",
  "Stony Brook University",
  "SUNY College at Brockport",
  "SUNY Buffalo State",
  "SUNY Cortland",
  "SUNY at Fredonia",
  "SUNY College at Geneseo",
  "SUNY at New Paltz",
  "SUNY College at Old Westbury",
  "SUNY Oneonta",
  "SUNY Oswego",
  "SUNY at Plattsburgh",
  "SUNY College at Potsdam",
  "SUNY College of Environmental Science and Forestry",
  "SUNY Maritime College",
  "SUNY College of Technology at Alfred",
  "Syracuse University",
  "Union College",
  "United States Merchant Marine Academy",
  "United States Military Academy",
  "Vassar College",
  "Wagner College",
  "Wells College",
  "Yeshiva University",
  "Appalachian State University",
  "Barton College",
  "Belmont Abbey College",
  "Bennett College for Women",
  "Campbell University",
  "Catawba College",
  "Davidson College",
  "Duke University",
  "East Carolina University",
  "Elizabeth City State University",
  "Elon University",
  "Fayetteville State University",
  "Gardner-Webb University",
  "Greensboro College",
  "Guilford College",
  "High Point University",
  "Johnson C Smith University",
  "Lees-McRae College",
  "Lenoir-Rhyne University",
  "Livingstone College",
  "Mars Hill College",
  "Meredith College",
  "Methodist University",
  "Montreat College",
  "Mount Olive College",
  "University of North Carolina at Asheville",
  "University of North Carolina at Chapel Hill",
  "University of North Carolina at Charlotte",
  "University of North Carolina at Greensboro",
  "University of North Carolina at Pembroke",
  "University of North Carolina Wilmington",
  "North Carolina Agricultural and Technical State University",
  "North Carolina Central University",
  "North Carolina State University at Raleigh",
  "North Carolina Wesleyan College",
  "Pfeiffer University",
  "Queens University of Charlotte",
  "Saint Augustine's University",
  "Salem College",
  "Shaw University",
  "Wake Forest University",
  "Warren Wilson College",
  "Western Carolina University",
  "Wingate University",
  "Winston-Salem State University",
  "Bismarck State College",
  "Dickinson State University",
  "Jamestown College",
  "Mayville State University",
  "Minot State University",
  "North Dakota State University-Main Campus",
  "University of North Dakota",
  "University of Mary",
  "Valley City State University",
  "Antioch University-Midwest",
  "Ashland University",
  "Baldwin Wallace University",
  "Bluffton University",
  "Bowling Green State University-Main Campus",
  "Capital University",
  "Case Western Reserve University",
  "Cedarville University",
  "Central State University",
  "University of Cincinnati-Main Campus",
  "Cleveland Institute of Art",
  "Cleveland State University",
  "College of Wooster",
  "University of Dayton",
  "Defiance College",
  "Denison University",
  "University of Findlay",
  "Franciscan University of Steubenville",
  "Franklin University",
  "Heidelberg University",
  "Hiram College",
  "John Carroll University",
  "Kent State University at Kent",
  "Kenyon College",
  "Lake Erie College",
  "Lourdes University",
  "Malone University",
  "Marietta College",
  "Miami University-Oxford",
  "Mount St Joseph University",
  "Mount Vernon Nazarene University",
  "Muskingum University",
  "Notre Dame College",
  "Oberlin College",
  "Ohio Dominican University",
  "Ohio Northern University",
  "Ohio State University-Main Campus",
  "Ohio University-Main Campus",
  "Ohio Wesleyan University",
  "Otterbein University",
  "University of Rio Grande",
  "Shawnee State University",
  "University of Toledo",
  "Tiffin University",
  "University of Akron Main Campus",
  "Urbana University",
  "Ursuline College",
  "Walsh University",
  "Wilmington College",
  "Wittenberg University",
  "College of Wooster",
  "Wright State University-Main Campus",
  "Xavier University",
  "Youngstown State University",
  "Cameron University",
  "East Central University",
  "Langston University",
  "Northeastern State University",
  "Northwestern Oklahoma State University",
  "University of Oklahoma-Norman Campus",
  "Oklahoma Baptist University",
  "Oklahoma Christian University",
  "Oklahoma City University",
  "Oklahoma Panhandle State University",
  "Oklahoma State University-Main Campus",
  "Oklahoma Wesleyan University",
  "Oral Roberts University",
  "Rogers State University",
  "University of Science and Arts of Oklahoma",
  "Southeastern Oklahoma State University",
  "Southern Nazarene University",
  "Southwestern Oklahoma State University",
  "University of Central Oklahoma",
  "University of Tulsa",
  "Concordia University-Portland",
  "Corban University",
  "Eastern Oregon University",
  "George Fox University",
  "Lewis & Clark College",
  "Linfield College",
  "Marylhurst University",
  "Oregon Health & Science University",
  "Oregon Institute of Technology",
  "Oregon State University",
  "Pacific University",
  "Portland State University",
  "Reed College",
  "University of Oregon",
  "University of Portland",
  "Warner Pacific College",
  "Western Oregon University",
  "Willamette University",
  "Albright College",
  "Allegheny College",
  "Arcadia University",
  "Bloomsburg University of Pennsylvania",
  "Bryn Mawr College",
  "Bucknell University",
  "Cabrini College",
  "California University of Pennsylvania",
  "Carnegie Mellon University",
  "Cedar Crest College",
  "Chatham University",
  "Chestnut Hill College",
  "Cheyney University of Pennsylvania",
  "Clarion University of Pennsylvania",
  "Dickinson College",
  "Drexel University",
  "Duquesne University",
  "East Stroudsburg University of Pennsylvania",
  "Eastern University",
  "Edinboro University of Pennsylvania",
  "Elizabethtown College",
  "Franklin and Marshall College",
  "Gannon University",
  "Geneva College",
  "Gettysburg College",
  "Grove City College",
  "Gwynedd Mercy University",
  "Haverford College",
  "Holy Family University",
  "Immaculata University",
  "Indiana University of Pennsylvania-Main Campus",
  "Juniata College",
  "King's College",
  "Kutztown University of Pennsylvania",
  "La Roche College",
  "La Salle University",
  "Lafayette College",
  "Lebanon Valley College",
  "Lehigh University",
  "Lincoln University",
  "Lock Haven University",
  "Lycoming College",
  "Mansfield University of Pennsylvania",
  "Marywood University",
  "Mercyhurst University",
  "Messiah College",
  "Millersville University of Pennsylvania",
  "Misericordia University",
  "Moravian College",
  "Muhlenberg College",
  "Neumann University",
  "University of Pennsylvania",
  "Pennsylvania State University-Main Campus",
  "Philadelphia University",
  "University of Pittsburgh-Pittsburgh Campus",
  "Point Park University",
  "Robert Morris University",
  "Rosemont College",
  "Saint Francis University",
  "Saint Joseph's University",
  "Saint Vincent College",
  "University of Scranton",
  "Seton Hill University",
  "Shippensburg University of Pennsylvania",
  "Slippery Rock University of Pennsylvania",
  "Susquehanna University",
  "Swarthmore College",
  "Temple University",
  "Thiel College",
  "University of the Sciences",
  "Ursinus College",
  "Villanova University",
  "Washington & Jefferson College",
  "Waynesburg University",
  "West Chester University of Pennsylvania",
  "Westminster College",
  "Widener University-Main Campus",
  "Wilkes University",
  "Wilson College",
  "York College of Pennsylvania",
  "Brown University",
  "Bryant University",
  "Johnson & Wales University-Providence",
  "Providence College",
  "Rhode Island College",
  "Rhode Island School of Design",
  "University of Rhode Island",
  "Roger Williams University",
  "Salve Regina University",
  "Anderson University",
  "Benedict College",
  "Bob Jones University",
  "Charleston Southern University",
  "The Citadel",
  "Claflin University",
  "Clemson University",
  "Coastal Carolina University",
  "Coker College",
  "College of Charleston",
  "Columbia College",
  "Columbia International University",
  "Converse College",
  "Erskine College",
  "Francis Marion University",
  "Furman University",
  "Lander University",
  "Limestone College",
  "Morris College",
  "Newberry College",
  "North Greenville University",
  "Presbyterian College",
  "University of South Carolina-Columbia",
  "South Carolina State University",
  "Southern Wesleyan University",
  "Winthrop University",
  "Wofford College",
  "Augustana College",
  "Black Hills State University",
  "Dakota State University",
  "Dakota Wesleyan University",
  "Mount Marty College",
  "Northern State University",
  "Presentation College",
  "University of Sioux Falls",
  "South Dakota School of Mines and Technology",
  "South Dakota State University",
  "University of South Dakota",
  "Austin Peay State University",
  "Belmont University",
  "Bethel University",
  "Bryan College-Dayton",
  "Carson-Newman College",
  "Christian Brothers University",
  "Cumberland University",
  "East Tennessee State University",
  "Fisk University",
  "Freed-Hardeman University",
  "King University",
  "Lane College",
  "Lee University",
  "LeMoyne-Owen College",
  "Lincoln Memorial University",
  "Lipscomb University",
  "Maryville College",
  "University of Memphis",
  "Middle Tennessee State University",
  "Milligan College",
  "Rhodes College",
  "Sewanee-University of the South",
  "Southern Adventist University",
  "University of Tennessee-Chattanooga",
  "University of Tennessee-Knoxville",
  "University of Tennessee-Martin",
  "Tennessee State University",
  "Tennessee Technological University",
  "Tennessee Wesleyan College",
  "Trevecca Nazarene University",
  "Tusculum College",
  "Union University",
  "Vanderbilt University",
  "Abilene Christian University",
  "Angelo State University",
  "Austin College",
  "Baylor University",
  "Concordia University Texas",
  "Dallas Baptist University",
  "University of Dallas",
  "East Texas Baptist University",
  "Hardin-Simmons University",
  "University of Houston",
  "University of Houston-Clear Lake",
  "University of Houston-Downtown",
  "University of Houston-Victoria",
  "Houston Baptist University",
  "Howard Payne University",
  "Huston-Tillotson University",
  "University of the Incarnate Word",
  "Jarvis Christian College",
  "Lamar University",
  "LeTourneau University",
  "Lubbock Christian University",
  "McMurry University",
  "Midwestern State University",
  "University of North Texas",
  "Our Lady of the Lake University",
  "Paul Quinn College",
  "Prairie View A & M University",
  "Rice University",
  "St Edward's University",
  "St Mary's University",
  "Sam Houston State University",
  "Schreiner University",
  "University of St Thomas",
  "Southern Methodist University",
  "Southwestern Adventist University",
  "Southwestern University",
  "Stephen F Austin State University",
  "Sul Ross State University",
  "Tarleton State University",
  "Texas A & M International University",
  "Texas A & M University-College Station",
  "Texas A & M University-Commerce",
  "Texas A & M University-Corpus Christi",
  "Texas A & M University-Kingsville",
  "Texas Christian University",
  "Texas College",
  "Texas Lutheran University",
  "Texas Southern University",
  "Texas State University",
  "Texas Tech University",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Texas at El Paso",
  "University of Texas at San Antonio",
  "University of Texas at Tyler",
  "University of Texas of the Permian Basin",
  "University of Texas-Pan American",
  "Texas Wesleyan University",
  "Texas Woman's University",
  "Trinity University",
  "University of Mary Hardin-Baylor",
  "Wayland Baptist University",
  "West Texas A & M University",
  "Wiley College",
  "Brigham Young University-Provo",
  "Dixie State University",
  "Southern Utah University",
  "University of Utah",
  "Utah State University",
  "Utah Valley University",
  "Weber State University",
  "Westminster College",
  "Bennington College",
  "Castleton State College",
  "Champlain College",
  "College of St Joseph",
  "Goddard College",
  "Green Mountain College",
  "Johnson State College",
  "Lyndon State College",
  "Marlboro College",
  "Middlebury College",
  "Norwich University",
  "Saint Michael's College",
  "Southern Vermont College",
  "Sterling College",
  "University of Vermont",
  "Vermont Technical College",
  "Averett University",
  "Bridgewater College",
  "Christopher Newport University",
  "College of William and Mary",
  "Eastern Mennonite University",
  "Emory & Henry College",
  "Ferrum College",
  "George Mason University",
  "Hampden-Sydney College",
  "Hampton University",
  "Hollins University",
  "James Madison University",
  "Liberty University",
  "Longwood University",
  "Lynchburg College",
  "Mary Baldwin College",
  "Marymount University",
  "Norfolk State University",
  "Old Dominion University",
  "Radford University",
  "Randolph-Macon College",
  "Randolph College",
  "Regent University",
  "Roanoke College",
  "Shenandoah University",
  "Sweet Briar College",
  "University of Mary Washington",
  "University of Richmond",
  "University of Virginia-Main Campus",
  "Virginia Commonwealth University",
  "Virginia Military Institute",
  "Virginia Polytechnic Institute and State University",
  "Virginia State University",
  "Virginia Union University",
  "Virginia Wesleyan College",
  "Washington and Lee University",
  "Central Washington University",
  "Eastern Washington University",
  "Evergreen State College",
  "Gonzaga University",
  "Heritage University",
  "Northwest University",
  "Pacific Lutheran University",
  "Saint Martin's University",
  "Seattle Pacific University",
  "Seattle University",
  "University of Puget Sound",
  "Walla Walla University",
  "Washington State University",
  "University of Washington-Seattle Campus",
  "Western Washington University",
  "Whitman College",
  "Whitworth University",
  "Alderson-Broaddus College",
  "Bethany College",
  "Bluefield State College",
  "Concord University",
  "Davis & Elkins College",
  "Fairmont State University",
  "Glenville State College",
  "Marshall University",
  "Ohio Valley University",
  "Salem International University",
  "Shepherd University",
  "University of Charleston",
  "West Liberty University",
  "West Virginia State University",
  "West Virginia University",
  "West Virginia Wesleyan College",
  "Wheeling Jesuit University",
  "Alverno College",
  "Beloit College",
  "Cardinal Stritch University",
  "Carroll University",
  "Carthage College",
  "Concordia University-Wisconsin",
  "Edgewood College",
  "Lawrence University",
  "Marian University",
  "Marquette University",
  "Milwaukee School of Engineering",
  "Mount Mary University",
  "Northland College",
  "Ripon College",
  "St Norbert College",
  "University of Wisconsin-Eau Claire",
  "University of Wisconsin-Green Bay",
  "University of Wisconsin-La Crosse",
  "University of Wisconsin-Madison",
  "University of Wisconsin-Milwaukee",
  "University of Wisconsin-Oshkosh",
  "University of Wisconsin-Parkside",
  "University of Wisconsin-Platteville",
  "University of Wisconsin-River Falls",
  "University of Wisconsin-Stevens Point",
  "University of Wisconsin-Stout",
  "University of Wisconsin-Superior",
  "University of Wisconsin-Whitewater",
  "Viterbo University",
  "Wisconsin Lutheran College",
  "University of Wyoming"
];
