// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PointMls>>
abstract class PointMls implements RustOpaqueInterface {
  Future<AddMemberResult> addMember({
    required List<int> groupId,
    required List<int> keyPackage,
  });

  Future<Uint8List> createGroup({required List<int> groupId});

  /// Decrypt a group ciphertext back to plaintext.
  Future<Uint8List> decrypt({
    required List<int> groupId,
    required List<int> ciphertext,
  });

  /// Encrypt a location fix for a group. Returns opaque MLS ciphertext.
  Future<Uint8List> encrypt({
    required List<int> groupId,
    required List<int> plaintext,
  });

  /// Serialize the full MLS state for durable storage. Call after every
  /// mutation (create_group, add_member, process_welcome, process_commit).
  Future<Uint8List> exportState();

  /// A fresh one-time KeyPackage to upload to the server pool.
  Future<Uint8List> generateKeyPackage();

  bool hasGroup({required List<int> groupId});

  /// Fresh identity — generates a new signing key and empty state.
  factory PointMls({required String identity}) =>
      RustLib.instance.api.crateApiCryptoPointMlsNew(identity: identity);

  /// Apply a Commit (membership change) to an existing group.
  Future<void> processCommit({
    required List<int> groupId,
    required List<int> commit,
  });

  /// Join a group from a Welcome; returns the group id.
  Future<Uint8List> processWelcome({required List<int> welcome});

  /// Restore from a previously exported state blob (secure storage). On error
  /// the caller should fall back to `new()` and re-join via Welcome/Commit.
  static PointMls restore({required List<int> state}) =>
      RustLib.instance.api.crateApiCryptoPointMlsRestore(state: state);

  /// A Signal-style safety number for a pairwise group — both members compute
  /// the same value from their sorted identity keys, for out-of-band verify.
  Future<String> safetyNumber({required List<int> groupId});
}

/// Welcome (for the new member) + Commit (for existing members) from an add.
class AddMemberResult {
  final Uint8List welcome;
  final Uint8List commit;

  const AddMemberResult({required this.welcome, required this.commit});

  @override
  int get hashCode => welcome.hashCode ^ commit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddMemberResult &&
          runtimeType == other.runtimeType &&
          welcome == other.welcome &&
          commit == other.commit;
}
