// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

FuzzedPoint stableFuzz({
  required double trueLat,
  required double trueLon,
  required double radiusM,
  required String sharerId,
  required String audienceId,
  required List<int> secret,
}) => RustLib.instance.api.crateApiFuzzStableFuzz(
  trueLat: trueLat,
  trueLon: trueLon,
  radiusM: radiusM,
  sharerId: sharerId,
  audienceId: audienceId,
  secret: secret,
);

Float64List fuzzRadiusPresetsM() =>
    RustLib.instance.api.crateApiFuzzFuzzRadiusPresetsM();

class FuzzedPoint {
  final double lat;
  final double lon;
  final PlatformInt64 cellX;
  final PlatformInt64 cellY;

  const FuzzedPoint({
    required this.lat,
    required this.lon,
    required this.cellX,
    required this.cellY,
  });

  @override
  int get hashCode =>
      lat.hashCode ^ lon.hashCode ^ cellX.hashCode ^ cellY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzedPoint &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lon == other.lon &&
          cellX == other.cellX &&
          cellY == other.cellY;
}
