// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A fresh high-entropy recovery code (24 Crockford-base32 symbols, grouped).
/// Show it to the user ONCE at enrollment — it is the only thing that can
/// decrypt their backup, and the server never learns it.
String generateRecoveryCode() =>
    RustLib.instance.api.crateApiRecoveryGenerateRecoveryCode();

/// Encrypt an exported MLS state blob under `recovery_code`. Upload the result
/// as-is; the server stores it as opaque bytes.
Uint8List recoveryEncrypt({
  required List<int> state,
  required String recoveryCode,
}) => RustLib.instance.api.crateApiRecoveryRecoveryEncrypt(
  state: state,
  recoveryCode: recoveryCode,
);

/// Decrypt a backup blob fetched from the server. Feed the result to
/// `PointMls.restore`. A wrong code or corrupt blob fails closed.
Uint8List recoveryDecrypt({
  required List<int> blob,
  required String recoveryCode,
}) => RustLib.instance.api.crateApiRecoveryRecoveryDecrypt(
  blob: blob,
  recoveryCode: recoveryCode,
);
