-- effect-db:up
-- Generated by effect-db; reviewed to order foreign-key dependencies first.
create schema if not exists "public";
create table "public"."user" ("id" text not null, "name" text not null, "email" text not null, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default now () not null, "updatedAt" timestamptz default now () not null, primary key ("id"), constraint "user_email_key" unique ("email"));
create table "public"."account" ("id" text not null, "userId" text not null, "accountId" text not null, "providerId" text not null, "accessToken" text, "refreshToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "idToken" text, "password" text, "createdAt" timestamptz default now () not null, "updatedAt" timestamptz default now () not null, primary key ("id"), constraint "account_userId_fkey" foreign key ("userId") references "public"."user" ("id") on delete cascade, constraint "account_providerId_accountId_key" unique ("providerId", "accountId"));
create table "public"."grove_actors" ("id" text not null, "kind" text not null, "name" text not null, "lifecycle" text default ('active')::text not null, "created_at" timestamptz default now () not null, "updated_at" timestamptz default now () not null, primary key ("id"), constraint "grove_actors_kind_check" check ((kind = (('person')::text )) OR (kind = (('agent')::text ))), constraint "grove_actors_lifecycle_check" check ((((lifecycle = (('active')::text )) OR (lifecycle = (('dormant')::text ))) OR (lifecycle = (('suspended')::text ))) OR (lifecycle = (('retired')::text ))), constraint "grove_actors_name_check" check (((length (name) ) >= (1)) AND ((length (name) ) <= (80))));
create table "public"."grove_actor_capabilities" ("actor_id" text not null, "capability" text not null, "created_at" timestamptz default now () not null, constraint "grove_actor_capabilities_actor_id_fkey" foreign key ("actor_id") references "public"."grove_actors" ("id") on delete restrict, constraint "grove_actor_capabilities_pkey" primary key ("actor_id", "capability"));
create table "public"."grove_persons" ("actor_id" text not null, "better_auth_user_id" text not null, primary key ("actor_id"), constraint "grove_persons_actor_id_fkey" foreign key ("actor_id") references "public"."grove_actors" ("id") on delete restrict, constraint "grove_persons_better_auth_user_id_key" unique ("better_auth_user_id"));
create table "public"."grove_hosts" ("id" text not null, "runner_id" text not null, "owner_person_id" text, "created_at" timestamptz default now () not null, primary key ("id"), constraint "grove_hosts_runner_id_key" unique ("runner_id"), constraint "grove_hosts_owner_person_id_fkey" foreign key ("owner_person_id") references "public"."grove_persons" ("actor_id") on delete restrict);
create table "public"."grove_agents" ("actor_id" text not null, "home_host_id" text not null, "owner_person_id" text not null, "acting_runtime_id" text, primary key ("actor_id"), constraint "grove_agents_actor_id_fkey" foreign key ("actor_id") references "public"."grove_actors" ("id") on delete restrict, constraint "grove_agents_home_host_id_fkey" foreign key ("home_host_id") references "public"."grove_hosts" ("id") on delete restrict, constraint "grove_agents_owner_person_id_fkey" foreign key ("owner_person_id") references "public"."grove_persons" ("actor_id") on delete restrict, constraint "grove_agents_acting_runtime_id_key" unique ("acting_runtime_id"));
create table "public"."grove_agent_access" ("agent_id" text not null, "person_id" text not null, "valid" boolean default true not null, "invalid_reason" text, "created_at" timestamptz default now () not null, "updated_at" timestamptz default now () not null, constraint "grove_agent_access_agent_id_fkey" foreign key ("agent_id") references "public"."grove_agents" ("actor_id") on delete restrict, constraint "grove_agent_access_person_id_fkey" foreign key ("person_id") references "public"."grove_persons" ("actor_id") on delete restrict, constraint "grove_agent_access_check" check ((valid AND (invalid_reason IS NULL)) OR ((NOT valid) AND (invalid_reason IS NOT NULL))), constraint "grove_agent_access_pkey" primary key ("agent_id", "person_id"));
create table "public"."grove_demo_sprouts" ("id" int8 generated always as identity not null, "name" text not null, "planted_at" timestamptz default now () not null, "waterings" int default 0 not null, "created_by_actor_id" text, "last_actor_id" text, primary key ("id"), constraint "grove_demo_sprouts_created_by_actor_id_fkey" foreign key ("created_by_actor_id") references "public"."grove_actors" ("id") on delete restrict, constraint "grove_demo_sprouts_last_actor_id_fkey" foreign key ("last_actor_id") references "public"."grove_actors" ("id") on delete restrict, constraint "grove_demo_sprouts_waterings_nonnegative" check (waterings >= (0)));
create table "public"."grove_external_identities" ("actor_id" text not null, "issuer" text not null, "subject" text not null, "use" text not null, "created_at" timestamptz default now () not null, constraint "grove_external_identities_actor_id_fkey" foreign key ("actor_id") references "public"."grove_actors" ("id") on delete restrict, constraint "grove_external_identities_use_check" check ((use = (('browser')::text )) OR (use = (('machine')::text ))), constraint "grove_external_identities_issuer_subject_key" unique ("issuer", "subject"), constraint "grove_external_identities_pkey" primary key ("actor_id", "issuer", "subject"));
create table "public"."session" ("id" text not null, "userId" text not null, "token" text not null, "expiresAt" timestamptz not null, "ipAddress" text, "userAgent" text, "createdAt" timestamptz default now () not null, "updatedAt" timestamptz default now () not null, primary key ("id"), constraint "session_userId_fkey" foreign key ("userId") references "public"."user" ("id") on delete cascade, constraint "session_token_key" unique ("token"));
create table "public"."verification" ("id" text not null, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default now () not null, "updatedAt" timestamptz default now () not null, primary key ("id"));
create index "account_userId_idx" on "public"."account" using btree ("userId" asc nulls last);
create index "grove_agent_access_person_idx" on "public"."grove_agent_access" using btree ("person_id" asc nulls last) where valid;
create index "grove_agents_owner_idx" on "public"."grove_agents" using btree ("owner_person_id" asc nulls last);
create index "grove_external_identities_actor_idx" on "public"."grove_external_identities" using btree ("actor_id" asc nulls last);
create index "session_userId_idx" on "public"."session" using btree ("userId" asc nulls last);
create index "verification_identifier_idx" on "public"."verification" using btree ("identifier" asc nulls last);
-- Required Home Host and demo seed data are reviewed additions, not schema changes.
insert into "public"."grove_hosts" ("id", "runner_id") values ('host-local', 'runner-local');
insert into "public"."grove_demo_sprouts" ("name") values ('Example fern');
-- effect-db:down
drop index "public"."verification_identifier_idx";
drop index "public"."session_userId_idx";
drop index "public"."grove_external_identities_actor_idx";
drop index "public"."grove_agents_owner_idx";
drop index "public"."grove_agent_access_person_idx";
drop index "public"."account_userId_idx";
drop table "public"."verification";
drop table "public"."session";
drop table "public"."grove_external_identities";
drop table "public"."grove_demo_sprouts";
drop table "public"."grove_agent_access";
drop table "public"."grove_agents";
drop table "public"."grove_hosts";
drop table "public"."grove_persons";
drop table "public"."grove_actor_capabilities";
drop table "public"."grove_actors";
drop table "public"."account";
drop table "public"."user";
-- Keep public and the CLI's migration ledger; do not cascade into unrelated objects.
