import { asynchronously } from "#domain/iteration";
// The ordered security migration (contract §3, PHASE1-DESIGN §3). ONE ordered path, no window:
// roles → tables → RLS enable+force + policy → RO role REVOKE then GRANT SELECT → security_invoker
// views. Idempotent (guarded CREATEs) so it is safe to run at every boot and in tests.
//
// Runs as the admin/owner role. The runtime then connects as console_app / console_ro.

import type { Emission } from "../emission.ts";
import { emissionFingerprint } from "../ingest/fingerprint.ts";
import { indefinitely } from "../iteration.ts";
import { embedText, EMBEDDING_MODEL, vectorLiteral } from "../semantic/embedding.ts";
import {
	semanticDocument,
	type DimensionDescriptor,
	type JoinDescriptor,
	type MeasureDescriptor,
} from "../semantic/registry.ts";
import { txSql, type Sql } from "./pool.ts";

// L1 uses Timescale hypertables. Global UUID dedup lives in the plain `emission_ids` gate because
// Timescale unique indexes must contain the time partition column.
const DOMAIN_SCHEMA_STATEMENTS: readonly string[] = [
	`create extension if not exists timescaledb cascade`,
	`create extension if not exists vector`,

	// --- runtime roles (cluster-global; all NOSUPERUSER NOBYPASSRLS so RLS actually binds) -----
	//   console_app    — caller-scoped reads (RLS filters to app.scopes)
	//   console_ro     — read-only SQL mode
	//   console_writer — the appender: inserts any scope + sees all rows (for dedup), NOT superuser
	`do $$ begin
	   if not exists (select 1 from pg_roles where rolname = 'console_app') then
	     create role console_app nologin nosuperuser nobypassrls;
	   end if;
	   if not exists (select 1 from pg_roles where rolname = 'console_ro') then
	     create role console_ro nologin nosuperuser nobypassrls;
	   end if;
	   alter role console_ro noinherit;
	   alter role console_ro set default_transaction_read_only = on;
	   if not exists (select 1 from pg_roles where rolname = 'console_writer') then
	     create role console_writer nologin nosuperuser nobypassrls;
	   end if;
	 end $$`,

	// --- events: the lake. seq is commit-ordered by the serialized appender. ------------------
	`create table if not exists events (
	   seq            bigint generated always as identity primary key,
	   id             uuid not null unique,
	   type           text not null,
	   ts             timestamptz not null,
	   received_at    timestamptz not null default now(),
	   source_service text not null,
	   source_host    text,
	   source_agent   text,
	   subject        text not null,
	   subject_kind   text,
	   severity       text not null,
	   action         text,
	   task_id        bigint,
	   scope          text not null,
	   dimensions     jsonb not null default '{}'::jsonb,
	   measures       jsonb not null default '{}'::jsonb,
	   links          jsonb not null default '[]'::jsonb,
	   body_ref       text,
	   meta           jsonb not null default '{}'::jsonb
	 )`,
	`create index if not exists events_type_received_idx on events (type, received_at desc)`,
	`create index if not exists events_subject_idx on events (subject)`,
	`create index if not exists events_scope_idx on events (scope)`,

	// --- L1 production lake: global id gate + Timescale storage -------------------------------
	// A hypertable cannot keep a UNIQUE(id) that omits its time partition key. Keep the global,
	// durable idempotency decision in a plain table and make seq there; events receives that exact
	// seq+receipt pair in the same transaction.
	`create table if not exists emission_ids (
	   id          uuid primary key,
	   seq         bigint generated by default as identity unique,
	   received_at timestamptz not null default clock_timestamp(),
	   payload_sha256 text
	 )`,
	`alter table emission_ids add column if not exists payload_sha256 text`,
	`create table if not exists schema_migrations (
	   name       text primary key,
	   applied_at timestamptz not null default now()
	 )`,

	// Better Auth core schema, generated from apps/console/auth.cli.ts. These tables own only
	// OIDC accounts and sessions; authorization continues through console grants/tiers below.
	`create table if not exists "user" (
	   "id" text primary key, "name" text not null, "email" text not null unique,
	   "emailVerified" boolean not null, "image" text,
	   "createdAt" timestamptz default current_timestamp not null,
	   "updatedAt" timestamptz default current_timestamp not null,
	   "authentikUsername" text not null, "authentikGroups" text not null,
	   "authentikSubject" text not null
	 )`,
	`alter table "user" add column if not exists "authentikSubject" text`,
	`create table if not exists better_auth_principals (
	   oidc_subject text primary key, principal_id text not null unique,
	   created_at timestamptz not null default now()
	 )`,
	`create table if not exists "session" (
	   "id" text primary key, "expiresAt" timestamptz not null, "token" text not null unique,
	   "createdAt" timestamptz default current_timestamp not null, "updatedAt" timestamptz not null,
	   "ipAddress" text, "userAgent" text,
	   "userId" text not null references "user" ("id") on delete cascade
	 )`,
	`create table if not exists "account" (
	   "id" text primary key, "accountId" text not null, "providerId" text not null,
	   "userId" text not null references "user" ("id") on delete cascade,
	   "accessToken" text, "refreshToken" text, "idToken" text,
	   "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz,
	   "scope" text, "password" text, "createdAt" timestamptz default current_timestamp not null,
	   "updatedAt" timestamptz not null
	 )`,
	`create table if not exists "verification" (
	   "id" text primary key, "identifier" text not null, "value" text not null,
	   "expiresAt" timestamptz not null, "createdAt" timestamptz default current_timestamp not null,
	   "updatedAt" timestamptz default current_timestamp not null
	 )`,
	`create index if not exists "session_userId_idx" on "session" ("userId")`,
	`create index if not exists "account_userId_idx" on "account" ("userId")`,
	`create index if not exists "verification_identifier_idx" on "verification" ("identifier")`,
	// Phase-1 may still be serving while deploy migrations start. Take the lock before the snapshot
	// backfill and hold it through conversion so no old writer can commit an ungated UUID/seq.
	`lock table events in access exclusive mode`,
	`insert into emission_ids (id, seq, received_at)
	 select id, seq, received_at from events
	 on conflict (id) do nothing`,
	`select setval(
	   pg_get_serial_sequence('emission_ids', 'seq'),
	   greatest(coalesce((select max(seq) from emission_ids), 1), 1),
	   exists(select 1 from emission_ids)
	 )`,
	`alter table if exists edges drop constraint if exists edges_seq_fkey`,
	`do $$ begin
	   if exists (
	     select 1 from pg_attribute
	     where attrelid = 'events'::regclass and attname = 'seq' and attidentity <> ''
	   ) then
	     alter table events alter column seq drop identity;
	   end if;
	 end $$`,
	`alter table events drop constraint if exists events_pkey`,
	`alter table events drop constraint if exists events_id_key`,
	`do $$ begin
	   if not exists (
	     select 1 from pg_constraint where conrelid = 'events'::regclass and conname = 'events_time_seq_pk'
	   ) then
	     alter table events add constraint events_time_seq_pk primary key (received_at, seq);
	   end if;
	 end $$`,
	`create index if not exists events_id_idx on events (id)`,
	`select create_hypertable('events', by_range('received_at'), if_not_exists => true, migrate_data => true)`,

	// Long-retention contractual classes are copied atomically at append time. The raw table can
	// retain 30d without erasing audit/terminal/edge/security history, while normal reads union the
	// archive only after the raw copy has disappeared.
	`create table if not exists event_archive (
	   seq            bigint not null,
	   id             uuid not null,
	   type           text not null,
	   ts             timestamptz not null,
	   received_at    timestamptz not null,
	   source_service text not null,
	   source_host    text,
	   source_agent   text,
	   subject        text not null,
	   subject_kind   text,
	   severity       text not null,
	   action         text,
	   task_id        bigint,
	   scope          text not null,
	   dimensions     jsonb not null default '{}'::jsonb,
	   measures       jsonb not null default '{}'::jsonb,
	   links          jsonb not null default '[]'::jsonb,
	   body_ref       text,
	   meta           jsonb not null default '{}'::jsonb,
	   primary key (received_at, seq)
	 )`,
	`create index if not exists event_archive_id_idx on event_archive (id)`,
	`create index if not exists event_archive_type_received_idx on event_archive (type, received_at desc)`,
	`create index if not exists event_archive_scope_idx on event_archive (scope)`,
	`select create_hypertable('event_archive', by_range('received_at'), if_not_exists => true, migrate_data => true)`,
	`insert into event_archive
	   (seq, id, type, ts, received_at, source_service, source_host, source_agent, subject,
	    subject_kind, severity, action, task_id, scope, dimensions, measures, links, body_ref, meta)
	 select seq, id, type, ts, received_at, source_service, source_host, source_agent, subject,
	        subject_kind, severity, action, task_id, scope, dimensions, measures, links, body_ref, meta
	 from events
	 where type like 'audit.%' or type like 'term.%' or type like 'edge.%'
	    or type like 'security.%' or meta->>'retention_class' = 'audit'
	 on conflict (received_at, seq) do nothing`,
	`create or replace view lake_events with (security_invoker = true) as
	 select * from events
	 union all
	 select a.* from event_archive a
	 where not exists (
	   select 1 from events e where e.received_at = a.received_at and e.seq = a.seq
	 )`,
	// Continuous aggregates cannot be defined over an RLS-enabled hypertable. The disable/create/
	// re-enable sequence is inside this one transaction, so no caller can observe an unprotected lake.
	`alter table events no force row level security`,
	`alter table events disable row level security`,
	`create materialized view if not exists event_rollup_1m
	 with (timescaledb.continuous) as
	 select time_bucket('1 minute', received_at) as bucket,
	        type, scope, severity, count(*)::bigint as event_count
	 from events
	 group by bucket, type, scope, severity
	 with no data`,
	// Raw retention is deliberately one ordered job, not an independent Timescale retention policy:
	// after downtime it refreshes every still-raw bucket before dropping any old chunk.
	`create or replace procedure console_events_refresh_then_retain(job_id int, config jsonb)
	 language plpgsql as $$
	 declare refresh_start timestamptz;
	 begin
	   select time_bucket('1 minute', min(received_at)) into refresh_start from events;
	   if refresh_start is not null and refresh_start < now() - interval '1 minute' then
	     call refresh_continuous_aggregate(
	       'event_rollup_1m', refresh_start, now() - interval '1 minute'
	     );
	   end if;
	   perform drop_chunks('events', older_than => now() - interval '30 days');
	 end $$`,

	// edges materialized from links at ingest (graphing design §04): "why?" is a graph walk.
	`create table if not exists edges (
	   id        bigint generated always as identity primary key,
	   from_kind text not null,
	   from_id   text not null,
	   rel       text not null,
	   to_kind   text not null,
	   to_id     text not null,
	   scope     text not null,
	   seq       bigint not null references emission_ids(seq)
	 )`,
	`create index if not exists edges_from_idx on edges (from_kind, from_id)`,
	`create index if not exists edges_to_idx on edges (to_kind, to_id)`,
	`do $$ begin
	   if not exists (
	     select 1 from pg_constraint where conrelid = 'edges'::regclass and conname = 'edges_seq_fkey'
	   ) then
	     alter table edges add constraint edges_seq_fkey foreign key (seq) references emission_ids(seq);
	   end if;
	 end $$`,

	// blobs: body_ref payloads, scope-checked on fetch by the same RLS as events.
	`create table if not exists blobs (
	   id         text primary key,
	   scope      text not null,
	   bytes      bytea not null,
	   created_at timestamptz not null default now()
	 )`,

	// L2 semantic registry: auto-derived field semantics, observed joins, and scoped RAG corpus.
	`create table if not exists semantic_registry (
	   type           text primary key,
	   first_seen     timestamptz not null default now(),
	   last_emit      timestamptz,
	   first_producer text,
	   dimensions     jsonb not null default '{}'::jsonb,
	   measures       jsonb not null default '{}'::jsonb,
	   joins          jsonb not null default '[]'::jsonb,
	   scopes         jsonb not null default '[]'::jsonb,
	   emit_count     bigint not null default 0,
	   updated_at     timestamptz not null default now()
	 )`,
	`alter table semantic_registry add column if not exists first_producer text`,
	`alter table semantic_registry add column if not exists joins jsonb not null default '[]'::jsonb`,
	`alter table semantic_registry add column if not exists updated_at timestamptz not null default now()`,
	// Caller-visible semantics are projected per scope.  The global row above is writer-only
	// coordination/state; exposing it would let one overlapping grant reveal fields seen elsewhere.
	`create table if not exists semantic_registry_scoped (
	   type           text not null references semantic_registry(type) on delete cascade,
	   scope          text not null,
	   first_seen     timestamptz not null default now(),
	   last_emit      timestamptz,
	   dimensions     jsonb not null default '{}'::jsonb,
	   measures       jsonb not null default '{}'::jsonb,
	   joins          jsonb not null default '[]'::jsonb,
	   emit_count     bigint not null default 0,
	   updated_at     timestamptz not null default now(),
	   primary key (type, scope)
	 )`,
	// Upgrade L1's compact {field:"type"} maps to catalog-contract descriptors in place.
	`update semantic_registry r set dimensions = (
	   select coalesce(jsonb_object_agg(key,
	     case when jsonb_typeof(value) = 'string'
	       then jsonb_build_object('type', value #>> '{}', 'cardinality', null)
	       else value end), '{}'::jsonb)
	   from jsonb_each(r.dimensions)
	 ) where exists (select 1 from jsonb_each(r.dimensions) where jsonb_typeof(value) = 'string')`,
	`update semantic_registry r set measures = (
	   select coalesce(jsonb_object_agg(key,
	     case when jsonb_typeof(value) = 'string'
	       then jsonb_build_object('kind', value #>> '{}', 'unit', null)
	       else value end), '{}'::jsonb)
	   from jsonb_each(r.measures)
	 ) where exists (select 1 from jsonb_each(r.measures) where jsonb_typeof(value) = 'string')`,
	`create table if not exists semantic_field_values (
	   statistic_type text not null references semantic_registry(type) on delete cascade,
	   field          text not null,
	   value_hash     text not null,
	   first_seen     timestamptz not null default now(),
	   primary key (statistic_type, field, value_hash)
	 )`,
	`create table if not exists semantic_field_values_scoped (
	   statistic_type text not null,
	   scope          text not null,
	   field          text not null,
	   value_hash     text not null,
	   first_seen     timestamptz not null default now(),
	   primary key (statistic_type, scope, field, value_hash),
	   foreign key (statistic_type, scope)
	     references semantic_registry_scoped(type, scope) on delete cascade
	 )`,
	`create table if not exists producer_rate_windows (
	   subject            text primary key,
	   minute_started_at  timestamptz not null default clock_timestamp(),
	   minute_emit_count  integer not null default 0,
	   hour_started_at    timestamptz not null default clock_timestamp(),
	   hour_new_type_count integer not null default 0
	 )`,
	`create table if not exists semantic_proposals (
	   id               bigint generated always as identity primary key,
	   kind             text not null,
	   producer_subject text not null,
	   statistic_type   text not null,
	   scope            text not null,
	   payload          jsonb not null default '{}'::jsonb,
	   status           text not null default 'pending',
	   created_at       timestamptz not null default now(),
	   resolved_at      timestamptz
	 )`,
	`create index if not exists semantic_proposals_pending_idx
	 on semantic_proposals (producer_subject, statistic_type, kind) where status = 'pending'`,
	`create table if not exists emission_quarantine (
	   id               uuid primary key,
	   producer_subject text not null,
	   statistic_type   text not null,
	   scope            text not null,
	   reason           text not null,
	   observed_at      timestamptz not null default now(),
	   retry_after      timestamptz
	 )`,
	`alter table emission_quarantine add column if not exists payload_sha256 text`,
	`alter table emission_quarantine add column if not exists retry_after timestamptz`,
	`update emission_quarantine set retry_after = observed_at +
	   case when reason = 'emit_rate_limited' then interval '1 minute' else interval '1 hour' end
	 where retry_after is null`,
	`create table if not exists semantic_views (
	   name          text primary key,
	   relation_name text not null unique,
	   description   text not null,
	   fields        jsonb not null default '{}'::jsonb,
	   scopes        jsonb not null default '["*"]'::jsonb,
	   enabled       boolean not null default true,
	   updated_at    timestamptz not null default now()
	 )`,
	`create or replace view statistic_relationships with (security_invoker = true) as
	 select e.*, x.rel as edge_rel, x.to_kind as edge_to_kind, x.to_id as edge_to_id
	 from lake_events e join edges x on x.seq = e.seq`,
	`insert into semantic_views (name, relation_name, description, fields) values
	 ('events', 'lake_events', 'All caller-visible statistics in the raw plus protected archive lake',
	  '{"shape":"event"}'::jsonb),
	 ('relationships', 'statistic_relationships', 'Statistics joined to their materialized relationship edges',
	  '{"shape":"event","edge_rel":{"type":"string"},"edge_to_kind":{"type":"string"},"edge_to_id":{"type":"string"}}'::jsonb)
	 on conflict (name) do update set relation_name = excluded.relation_name,
	   description = excluded.description, fields = excluded.fields, updated_at = now()`,
	`create table if not exists semantic_documents (
	   id              text primary key,
	   kind            text not null check (kind in ('statistic', 'query', 'view')),
	   source_ref      text not null,
	   content         text not null,
	   scopes          jsonb not null default '[]'::jsonb,
	   embedding       vector(384) not null,
	   embedding_model text not null,
	   updated_at      timestamptz not null default now()
	 )`,
	`create index if not exists semantic_documents_embedding_hnsw
	 on semantic_documents using hnsw (embedding vector_cosine_ops)`,
	`create index if not exists semantic_documents_content_fts
	 on semantic_documents using gin (to_tsvector('simple', content))`,
	`create table if not exists query_history (
	   query_ref       text primary key,
	   request         jsonb not null,
	   sql_text        text not null,
	   params          jsonb not null default '[]'::jsonb,
	   scopes          jsonb not null default '[]'::jsonb,
	   columns         jsonb not null default '[]'::jsonb,
	   row_count       integer not null,
	   execution_ms    integer,
	   status          text not null default 'success',
	   created_at      timestamptz not null default now()
	 )`,

	// producer registrations: the emit-authz allow-lists (contract §4.3), seeded out of band.
	`create table if not exists producer_registrations (
	   subject          text primary key,
	   allowed_services jsonb not null default '[]'::jsonb,
	   allowed_prefixes jsonb not null default '[]'::jsonb,
	   allowed_scopes   jsonb not null default '[]'::jsonb,
	   max_severity     text not null default 'info',
	   max_emit_per_min integer not null default 6000,
	   max_new_types_per_hour integer not null default 20
	 )`,
	`alter table producer_registrations add column if not exists max_emit_per_min integer not null default 6000`,
	`alter table producer_registrations add column if not exists max_new_types_per_hour integer not null default 20`,

	// bearer verification (sha256 only; the vault keeps plaintext for re-issue, CP4).
	`create table if not exists api_tokens (
	   token_sha256 text primary key,
	   subject      text not null,
	   kind         text not null,
	   tiers        jsonb not null default '[]'::jsonb,
	   lanes        jsonb not null default '[]'::jsonb,
	   created_at   timestamptz not null default now(),
	   revoked_at   timestamptz
	 )`,

	// ReBAC grants (contract §7.2).
	`create table if not exists grants (
	   id         bigint generated always as identity primary key,
	   subject    text not null,
	   relation   text not null,
	   object     text not null,
	   condition  text,
	   valid_at   timestamptz not null default now(),
	   invalid_at timestamptz,
	   granted_by text not null,
	   zookie     bigint not null default 1
	 )`,
	`do $$ begin
	   if not exists (select 1 from pg_constraint where conname = 'grants_valid_window') then
	     alter table grants add constraint grants_valid_window
	       check (invalid_at is null or invalid_at > valid_at) not valid;
	   end if;
	 end $$`,
	`create index if not exists grants_subject_idx on grants (subject)`,
	`create index if not exists grants_object_idx on grants (object)`,
	`create sequence if not exists grant_zookie_seq`,
	`create table if not exists grant_set_state (
	   singleton boolean primary key default true check (singleton),
	   zookie bigint not null
	 )`,
	`insert into grant_set_state (singleton, zookie)
	 select true, greatest(coalesce(max(zookie), 0), 1) from grants
	 on conflict (singleton) do update set zookie = greatest(grant_set_state.zookie, excluded.zookie)`,
	`select setval('grant_zookie_seq', greatest(
	   (select zookie from grant_set_state where singleton),
	   (select last_value from grant_zookie_seq)
	 ), true)`,
	`create or replace function fence_grant_change() returns trigger language plpgsql
	 security definer set search_path = pg_catalog, public as $$
	 declare next_zookie bigint;
	 begin
	   next_zookie := nextval('grant_zookie_seq');
	   insert into grant_set_state (singleton, zookie) values (true, next_zookie)
	     on conflict (singleton) do update
	       set zookie = greatest(grant_set_state.zookie, excluded.zookie);
	   if tg_op <> 'DELETE' then new.zookie := next_zookie; end if;
	   perform pg_notify('console_grants_changed', next_zookie::text);
	   if tg_op = 'DELETE' then return old; else return new; end if;
	 end $$`,
	`drop trigger if exists grants_fence_change on grants`,
	`create trigger grants_fence_change before insert or update or delete on grants
	 for each row execute function fence_grant_change()`,
	`create table if not exists grant_mutations (
	   principal_id text not null,
	   request_id uuid not null,
	   request_hash text not null,
	   result jsonb not null,
	   created_at timestamptz not null default now(),
	   primary key (principal_id, request_id)
	 )`,

	`create table if not exists tiers (
	   name            text primary key,
	   authentik_group text,
	   description     text not null default '',
	   default_relations jsonb not null default '[]'::jsonb,
	   propose_only    boolean not null default false
	 )`,
	`alter table tiers add column if not exists description text not null default ''`,
	`alter table tiers add column if not exists default_relations jsonb not null default '[]'::jsonb`,
	`update tiers set
	   description = case name
	     when 'owner' then 'Full administration of explicitly visible resources.'
	     when 'moderator' then 'Operate explicitly visible resources without changing ownership.'
	     when 'collaborator' then 'View explicitly shared resources and propose changes for owner promotion.'
	     when 'guest' then 'No implicit access; every visible resource requires an explicit grant.'
	     else description end,
	   default_relations = case name
	     when 'owner' then '["owner"]'::jsonb
	     when 'moderator' then '["operator"]'::jsonb
	     when 'collaborator' then '["viewer"]'::jsonb
	     else default_relations end
	 where name in ('owner', 'moderator', 'collaborator', 'guest')
	   and description = '' and default_relations = '[]'::jsonb`,
	`do $$ begin
	   if not exists (select 1 from pg_constraint where conname = 'tiers_name_format') then
	     alter table tiers add constraint tiers_name_format
	       check (name ~ '^[a-z][a-z0-9_-]{0,63}$');
	   end if;
	   if not exists (select 1 from pg_constraint where conname = 'tiers_default_relations_valid') then
	     alter table tiers add constraint tiers_default_relations_valid check (
	       jsonb_typeof(default_relations) = 'array'
	       and default_relations <@ '["viewer", "editor", "operator", "owner"]'::jsonb
	     );
	   end if;
	 end $$`,
	`create table if not exists proposal_mutations (
	   principal_id    text not null,
	   request_id      uuid not null,
	   request_hash    text not null,
	   operation       text not null,
	   proposal_task_id bigint,
	   state           text not null default 'ready',
	   dispatch_started_at timestamptz,
	   created_at      timestamptz not null default now(),
	   primary key (principal_id, request_id),
	   constraint proposal_mutations_state_valid check (state in ('ready', 'dispatching', 'complete'))
	 )`,
	`alter table proposal_mutations add column if not exists state text not null default 'ready'`,
	`alter table proposal_mutations add column if not exists dispatch_started_at timestamptz`,
	`update proposal_mutations set state = 'complete' where proposal_task_id is not null`,
	`do $$ begin
	   if not exists (select 1 from pg_constraint where conname = 'proposal_mutations_state_valid') then
	     alter table proposal_mutations add constraint proposal_mutations_state_valid
	       check (state in ('ready', 'dispatching', 'complete'));
	   end if;
	 end $$`,
	`create table if not exists assistant_sessions (
	   principal_id       text primary key,
	   principal_kind     text not null,
	   tiers              jsonb not null default '[]'::jsonb,
	   lanes              jsonb not null default '[]'::jsonb,
	   auth_source        text not null default 'legacy',
	   auth_session_id    text,
	   external_session_id text not null unique,
	   manager_session_id text unique,
	   state              text not null default 'creating',
	   window_layout      jsonb not null default '{"ops":[]}'::jsonb,
	   last_context       jsonb,
	   last_context_seq   bigint not null default 0,
	   created_at         timestamptz not null default now(),
	   updated_at         timestamptz not null default now(),
	   constraint assistant_sessions_kind_valid check (principal_kind in ('human','agent','system')),
	   constraint assistant_sessions_state_valid check (state in ('creating','ready','failed'))
	 )`,
	`create table if not exists assistant_tool_tokens (
	   token_sha256 text primary key,
	   principal_id text not null references assistant_sessions(principal_id) on delete cascade,
	   expires_at   timestamptz not null,
	   created_at   timestamptz not null default now()
	 )`,
	`create index if not exists assistant_tool_tokens_expiry on assistant_tool_tokens (expires_at)`,
	`create table if not exists assistant_messages (
	   principal_id     text not null references assistant_sessions(principal_id) on delete cascade,
	   message_id       uuid not null,
	   message_seq      bigserial unique,
	   kind             text not null,
	   request_hash     text not null,
	   response_id      text,
	   state            text not null default 'ready',
	   dispatch_started_at timestamptz,
	   created_at       timestamptz not null default now(),
	   completed_at     timestamptz,
	   primary key (principal_id, message_id),
	   constraint assistant_messages_kind_valid check (kind in ('user','context')),
	   constraint assistant_messages_state_valid check (state in ('ready','dispatching','complete'))
	 )`,
	`alter table assistant_sessions add column if not exists last_context_seq bigint not null default 0`,
	`alter table assistant_sessions add column if not exists auth_source text not null default 'legacy'`,
	`alter table assistant_sessions add column if not exists auth_session_id text`,
	`alter table assistant_messages add column if not exists message_seq bigserial`,
	`alter table assistant_messages add column if not exists request_hash text`,
	`alter table assistant_messages add column if not exists state text not null default 'ready'`,
	`alter table assistant_messages add column if not exists dispatch_started_at timestamptz`,
	`update assistant_messages set state = 'complete' where response_id is not null`,
	`do $$ begin
	   if not exists (select 1 from pg_constraint where conname = 'assistant_messages_state_valid') then
	     alter table assistant_messages add constraint assistant_messages_state_valid
	       check (state in ('ready','dispatching','complete'));
	   end if;
	 end $$`,

	// --- N1b: current-state projection (latest per entity), keyed by the PROJECTION bucket -----
	// kind is the projection-map target (fleet|heartbeat|registry|governance|card|worker|
	// box_update|edge|edge_session|attention|subscription|delivery), NOT the emission
	// subject_kind (which is `agent` for several independent buckets).
	`create table if not exists current_state (
	   kind              text not null,
	   subject           text not null,
	   scope             text not null,
	   state             jsonb not null,
	   observed_at       timestamptz not null,
	   producer_ts       timestamptz,
	   unreachable_since timestamptz,
	   seq               bigint not null,
	   primary key (kind, subject)
	 )`,
	`create table if not exists delivery_config (
	   owner          text primary key,
	   scope          text not null,
	   channel        text not null default 'matrix' check (channel = 'matrix'),
	   target         text not null,
	   verified       boolean not null default false,
	   cocoon_until   timestamptz,
	   next_digest_at timestamptz,
	   updated_at     timestamptz not null default now(),
	   updated_by     text not null
	 )`,
	`create table if not exists signal_source_modes (
	   source_service text primary key,
	   scope          text not null default 'fleet' check (scope = 'fleet'),
	   mode           text not null check (mode in ('normal', 'development')),
	   note           text,
	   updated_at     timestamptz not null default now(),
	   updated_by     text not null
	 )`,
	`create table if not exists signal_source_mode_outbox (
	   id             uuid primary key,
	   source_service text not null,
	   mode           text not null check (mode in ('normal', 'development')),
	   note           text,
	   updated_at     timestamptz not null,
	   updated_by     text not null
	 )`,

	// projector durability: the seq up to which current_state reflects the lake.
	`create table if not exists projection_checkpoint (
	   name         text primary key,
	   through_seq  bigint not null default 0,
	   updated_at   timestamptz not null default now()
	 )`,
	// bridge cursors: the high-water mark a co-located bridge has ingested per source (durable so a
	// restart resumes; deterministic emission ids make re-processing safe regardless).
	`create table if not exists bridge_cursor (
	   source      text primary key,
		   cursor      text not null default '',
		   below_count integer not null default 0,
		   below_hash  text not null default '',
		   updated_at  timestamptz not null default now()
		 )`,
	`alter table bridge_cursor add column if not exists below_hash text not null default ''`,

	`create table if not exists bridge_dead_letter (
		   source          text not null,
		   source_cursor   text not null,
		   emission_id     text,
		   error_code      text not null,
		   quarantined_at  timestamptz not null default now(),
		   primary key (source, source_cursor)
		 )`,

	// executor signing keys: completions are executor-SIGNED, verified here; the bridge is relay-only.
	`create table if not exists executor_keys (
	   executor    text primary key,
	   algorithm   text not null default 'ed25519',
	   public_key  text not null,
	   created_at  timestamptz not null default now(),
	   revoked_at  timestamptz
	 )`,

	// Rev3 Library is the canonical polymorphic store.  The legacy items_min name is retained below
	// only as a security-invoker compatibility view for older grant code and rolling deployments.
	`do $$ begin
	   if to_regclass('public.library_items') is null
	      and exists (select 1 from pg_class where oid = to_regclass('public.items_min') and relkind = 'r') then
	     alter table items_min rename to library_items;
	   end if;
	 end $$`,
	`create table if not exists library_items (
	   id                 text primary key,
	   entity_id          text,
	   kind               text not null,
	   title              text not null,
	   scope              text not null,
	   project            text not null default 'unsorted',
	   status             text not null default 'draft',
	   body_ref           text,
	   render_mode        text not null default 'markdown',
	   confidence         double precision,
	   source_url         text,
	   properties         jsonb not null default '{}'::jsonb,
	   version            integer not null default 1,
	   valid_from         timestamptz not null default now(),
	   valid_to           timestamptz,
	   tx_from            timestamptz not null default now(),
	   is_home            boolean not null default false,
	   created_by         text,
	   responsible_human  text,
	   handed_off_to      text,
	   protection         text not null default 'open',
	   payload            jsonb not null default '{}'::jsonb,
	   updated_at         timestamptz not null default now()
	 )`,
	`alter table library_items add column if not exists entity_id text`,
	`alter table library_items add column if not exists project text not null default 'unsorted'`,
	`alter table library_items add column if not exists status text not null default 'draft'`,
	`alter table library_items add column if not exists body_ref text`,
	`alter table library_items add column if not exists render_mode text not null default 'markdown'`,
	`alter table library_items add column if not exists confidence double precision`,
	`alter table library_items add column if not exists source_url text`,
	`alter table library_items add column if not exists properties jsonb not null default '{}'::jsonb`,
	`alter table library_items add column if not exists version integer not null default 1`,
	`alter table library_items add column if not exists valid_from timestamptz not null default now()`,
	`alter table library_items add column if not exists valid_to timestamptz`,
	`alter table library_items add column if not exists tx_from timestamptz not null default now()`,
	`alter table library_items add column if not exists handed_off_to text`,
	`alter table library_items add column if not exists protection text not null default 'open'`,
	`update library_items set entity_id = id where entity_id is null`,
	`create or replace function library_item_identity_default() returns trigger
	 language plpgsql as $$ begin
	   if new.entity_id is null then new.entity_id := new.id; end if;
	   return new;
	 end $$`,
	`drop trigger if exists library_item_identity_default on library_items`,
	`create trigger library_item_identity_default before insert on library_items
	 for each row execute function library_item_identity_default()`,
	`update library_items
	 set properties = properties || jsonb_build_object('artifact_type', 'dashboard'),
	     project = case when project = 'unsorted' then 'dashboards' else project end,
	     status = case when status = 'draft' then 'verified-shared' else status end,
	     render_mode = 'html', protection = case when protection = 'open' then 'semi' else protection end
	 where kind = 'artifact' and payload ? 'panels' and properties->>'artifact_type' is null`,
	`alter table library_items alter column entity_id set not null`,
	`create index if not exists library_items_scope_tx_idx on library_items (scope, tx_from desc, id desc)`,
	`create index if not exists library_items_search_idx on library_items using gin
	   (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(properties->>'body','')))`,
	`create table if not exists library_links (
	   id          bigint generated always as identity primary key,
	   from_id     text not null references library_items(id),
	   to_id       text not null references library_items(id),
	   rel_type    text not null,
	   reason      text,
	   scope       text not null,
	   created_at  timestamptz not null default now(),
	   unique (from_id, to_id, rel_type)
	 )`,
	`create index if not exists library_links_from_idx on library_links (from_id)`,
	`create index if not exists library_links_to_idx on library_links (to_id)`,
	`create table if not exists library_item_revisions (
	   item_id     text not null references library_items(id),
	   version     integer not null,
	   tx_from     timestamptz not null,
	   snapshot    jsonb not null,
	   primary key (item_id, version)
	 )`,
	`insert into library_item_revisions (item_id, version, tx_from, snapshot)
	 select id, version, tx_from, to_jsonb(library_items) from library_items
	 on conflict (item_id, version) do nothing`,
	`create or replace function record_library_item_revision() returns trigger
	 language plpgsql as $$ begin
	   insert into library_item_revisions (item_id, version, tx_from, snapshot)
	   values (new.id, new.version, new.tx_from, to_jsonb(new))
	   on conflict (item_id, version) do update set tx_from = excluded.tx_from, snapshot = excluded.snapshot;
	   return new;
	 end $$`,
	`drop trigger if exists record_library_item_revision on library_items`,
	`create trigger record_library_item_revision after insert or update on library_items
	 for each row execute function record_library_item_revision()`,
	`create table if not exists library_holds (
	   id             bigint generated always as identity primary key,
	   item_id        text not null references library_items(id),
	   for_principal  text not null,
	   reason         text not null,
	   scope          text not null,
	   held_at        timestamptz not null default now(),
	   unique (item_id, for_principal, reason)
	 )`,
	`create table if not exists library_curation (
	   id                text primary key,
	   item_id           text not null references library_items(id),
	   proposal_type     text not null,
	   reason            text not null,
	   scope             text not null,
	   state             text not null default 'review',
	   links_in          integer not null default 0,
	   active_task_links integer not null default 0,
	   run_id            text,
	   proposed_at       timestamptz not null default now()
	 )`,
	`alter table library_curation add column if not exists capability text`,
	`alter table library_curation add column if not exists version text`,
	`alter table library_curation add column if not exists sha256 text`,
	`alter table library_curation add column if not exists proposed_by text`,
	`alter table library_curation add column if not exists reviewed_by text`,
	`alter table library_curation add column if not exists reviewed_at timestamptz`,
	`alter table library_curation add column if not exists review_reason text`,
	`drop view if exists items_min`,
	`create view items_min with (security_invoker = true) as
	 select id, kind, title, scope, is_home, created_by, responsible_human, payload, updated_at
	 from library_items`,
	`create table if not exists dashboard_mutations (
	   principal_id text not null,
	   request_id   uuid not null,
	   request_hash text not null,
	   dashboard_id text not null,
	   created_at   timestamptz not null default now(),
	   primary key (principal_id, request_id)
	 )`,

	// --- RLS: enable + force on every scoped base table, then the policy ----------------------
	`alter table current_state enable row level security`,
	`alter table current_state force row level security`,
	`alter table delivery_config enable row level security`,
	`alter table delivery_config force row level security`,
	`alter table signal_source_modes enable row level security`,
	`alter table signal_source_modes force row level security`,
	`alter table library_items enable row level security`,
	`alter table library_items force row level security`,
	`alter table library_links enable row level security`,
	`alter table library_links force row level security`,
	`alter table library_holds enable row level security`,
	`alter table library_holds force row level security`,
	`alter table library_curation enable row level security`,
	`alter table library_curation force row level security`,
	`alter table events enable row level security`,
	`alter table events force row level security`,
	`alter table event_archive enable row level security`,
	`alter table event_archive force row level security`,
	`alter table edges enable row level security`,
	`alter table edges force row level security`,
	`alter table blobs enable row level security`,
	`alter table blobs force row level security`,
	`alter table semantic_registry enable row level security`,
	`alter table semantic_registry force row level security`,
	`alter table semantic_registry_scoped enable row level security`,
	`alter table semantic_registry_scoped force row level security`,
	`alter table semantic_proposals enable row level security`,
	`alter table semantic_proposals force row level security`,
	`alter table emission_quarantine enable row level security`,
	`alter table emission_quarantine force row level security`,
	`alter table semantic_views enable row level security`,
	`alter table semantic_views force row level security`,
	`alter table semantic_documents enable row level security`,
	`alter table semantic_documents force row level security`,
	`alter table query_history enable row level security`,
	`alter table query_history force row level security`,

	// SELECT policy: a caller sees a row iff its scope is in the per-transaction app.scopes GUC.
	// Unset GUC → string_to_array(NULL,',') → NULL → scope = ANY(NULL) → NULL → row excluded
	// (fail-closed). console_writer (the appender) sees ALL rows so dedup can find any id, and may
	// INSERT any scope — scope authorization already happened at the emit door; the durable scope
	// tag is what caller reads filter on.
	`do $$ begin
	   drop policy if exists semantic_registry_scope_select on semantic_registry;
	   drop policy if exists semantic_documents_scope_select on semantic_documents;
	   drop policy if exists query_history_scope_select on query_history;
	   if not exists (select 1 from pg_policies where tablename='events' and policyname='events_scope_select') then
	     create policy events_scope_select on events for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='events' and policyname='events_writer_all') then
	     create policy events_writer_all on events to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='event_archive' and policyname='event_archive_scope_select') then
	     create policy event_archive_scope_select on event_archive for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='event_archive' and policyname='event_archive_writer_all') then
	     create policy event_archive_writer_all on event_archive to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='edges' and policyname='edges_scope_select') then
	     create policy edges_scope_select on edges for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='edges' and policyname='edges_writer_all') then
	     create policy edges_writer_all on edges to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='blobs' and policyname='blobs_scope_select') then
	     create policy blobs_scope_select on blobs for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='blobs' and policyname='blobs_writer_all') then
	     create policy blobs_writer_all on blobs to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='current_state' and policyname='current_state_scope_select') then
	     create policy current_state_scope_select on current_state for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='current_state' and policyname='current_state_writer_all') then
	     create policy current_state_writer_all on current_state to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='delivery_config' and policyname='delivery_config_scope_select') then
	     create policy delivery_config_scope_select on delivery_config for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='delivery_config' and policyname='delivery_config_writer_all') then
	     create policy delivery_config_writer_all on delivery_config to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='signal_source_modes' and policyname='signal_source_modes_scope_select') then
	     create policy signal_source_modes_scope_select on signal_source_modes for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='signal_source_modes' and policyname='signal_source_modes_writer_all') then
	     create policy signal_source_modes_writer_all on signal_source_modes to console_writer using (true) with check (true);
	   end if;
	   drop policy if exists library_items_scope_select on library_items;
	   create policy library_items_scope_select on library_items for select to console_app, console_ro
	     using (
	       scope = any (string_to_array(current_setting('app.scopes', true), ','))
	       or ('item:' || id) = any (string_to_array(current_setting('app.scopes', true), ','))
	     );
	   if not exists (select 1 from pg_policies where tablename='library_items' and policyname='library_items_writer_all') then
	     create policy library_items_writer_all on library_items to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='library_links' and policyname='library_links_scope_select') then
	     create policy library_links_scope_select on library_links for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='library_links' and policyname='library_links_writer_all') then
	     create policy library_links_writer_all on library_links to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='library_holds' and policyname='library_holds_scope_select') then
	     create policy library_holds_scope_select on library_holds for select to console_app
	       using (
	         scope = any (string_to_array(current_setting('app.scopes', true), ','))
	         and (('user:' || for_principal) = any (string_to_array(current_setting('app.scopes', true), ','))
	           or ('agent:' || for_principal) = any (string_to_array(current_setting('app.scopes', true), ',')))
	       );
	   end if;
	   if not exists (select 1 from pg_policies where tablename='library_holds' and policyname='library_holds_writer_all') then
	     create policy library_holds_writer_all on library_holds to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='library_curation' and policyname='library_curation_scope_select') then
	     create policy library_curation_scope_select on library_curation for select to console_app
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='library_curation' and policyname='library_curation_writer_all') then
	     create policy library_curation_writer_all on library_curation to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_registry' and policyname='semantic_registry_writer_all') then
	     create policy semantic_registry_writer_all on semantic_registry to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_registry_scoped' and policyname='semantic_registry_scoped_select') then
	     create policy semantic_registry_scoped_select on semantic_registry_scoped for select to console_app, console_ro
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_registry_scoped' and policyname='semantic_registry_scoped_writer_all') then
	     create policy semantic_registry_scoped_writer_all on semantic_registry_scoped to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_proposals' and policyname='semantic_proposals_scope_select') then
	     create policy semantic_proposals_scope_select on semantic_proposals for select to console_app
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_proposals' and policyname='semantic_proposals_writer_all') then
	     create policy semantic_proposals_writer_all on semantic_proposals to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='emission_quarantine' and policyname='emission_quarantine_scope_select') then
	     create policy emission_quarantine_scope_select on emission_quarantine for select to console_app
	       using (scope = any (string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='emission_quarantine' and policyname='emission_quarantine_writer_all') then
	     create policy emission_quarantine_writer_all on emission_quarantine to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_views' and policyname='semantic_views_scope_select') then
	     create policy semantic_views_scope_select on semantic_views for select to console_app, console_ro
	       using (scopes ? '*' or scopes ?| string_to_array(current_setting('app.scopes', true), ','));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_documents' and policyname='semantic_documents_scope_select') then
	     create policy semantic_documents_scope_select on semantic_documents for select to console_app
	       using (scopes ? '*' or scopes <@ to_jsonb(string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_documents' and policyname='semantic_documents_app_insert') then
	     create policy semantic_documents_app_insert on semantic_documents for insert to console_app
	       with check (scopes <@ to_jsonb(string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='semantic_documents' and policyname='semantic_documents_writer_all') then
	     create policy semantic_documents_writer_all on semantic_documents to console_writer using (true) with check (true);
	   end if;
	   if not exists (select 1 from pg_policies where tablename='query_history' and policyname='query_history_scope_select') then
	     create policy query_history_scope_select on query_history for select to console_app
	       using (scopes <@ to_jsonb(string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	   if not exists (select 1 from pg_policies where tablename='query_history' and policyname='query_history_app_insert') then
	     create policy query_history_app_insert on query_history for insert to console_app
	       with check (scopes <@ to_jsonb(string_to_array(current_setting('app.scopes', true), ',')));
	   end if;
	 end $$`,

	// --- grants -------------------------------------------------------------------------------
	`revoke all on all tables in schema public from console_ro`,
	`revoke all on grants, grant_set_state, grant_mutations, proposal_mutations,
	   assistant_sessions, assistant_tool_tokens, assistant_messages from console_app, console_ro`,
	`revoke create on schema public from console_ro`,
	`revoke select on semantic_registry from console_app, console_ro`,
	`grant usage on schema public to console_app, console_ro, console_writer`,
	`grant select on events, event_archive, lake_events, statistic_relationships, current_state, delivery_config, signal_source_modes, library_items, library_links, items_min, semantic_registry_scoped, semantic_views to console_ro`,
	// console_app: scoped reads across the read surface.
	`grant select on events, event_archive, lake_events, statistic_relationships, edges, blobs, current_state, delivery_config, signal_source_modes, library_items, library_item_revisions, library_links, library_holds, library_curation, items_min, semantic_registry_scoped, semantic_proposals, emission_quarantine, semantic_views, semantic_documents, query_history, producer_registrations, tiers, api_tokens, executor_keys to console_app`,
	`grant insert on query_history, semantic_documents to console_app`,
	// console_writer: the appender + projector (non-superuser) — insert events/edges/blobs, upsert current_state.
	`grant insert, select on emission_ids, events, event_archive, edges, blobs to console_writer`,
	`grant insert, update, select on semantic_registry, semantic_registry_scoped, semantic_field_values, semantic_field_values_scoped, producer_rate_windows, semantic_proposals, emission_quarantine, semantic_documents, grants, grant_mutations to console_writer`,
	`grant select on grant_set_state, items_min to console_writer`,
	`grant usage, select on sequence grants_id_seq, grant_zookie_seq to console_writer`,
	`grant usage, select on sequence emission_ids_seq_seq to console_writer`,
	`grant usage, select on sequence semantic_proposals_id_seq to console_writer`,
	`grant insert, update, select, delete on current_state, library_items, library_item_revisions, library_links, library_holds, library_curation to console_writer`,
	`grant usage, select on sequence library_links_id_seq, library_holds_id_seq to console_writer`,
	`grant insert, update, select, delete on items_min to console_writer`,
	`grant insert, update, select, delete on delivery_config to console_writer`,
	`grant insert, update, select, delete on signal_source_modes to console_writer`,
	`grant insert, select, delete on signal_source_mode_outbox to console_writer`,
	`grant insert, select on dashboard_mutations to console_writer`,
	`grant insert, update, select on proposal_mutations to console_writer`,
	`grant insert, update, select on assistant_sessions, assistant_messages to console_writer`,
	`grant insert, update, select, delete on assistant_tool_tokens to console_writer`,
	`grant usage, select on sequence assistant_messages_message_seq_seq to console_writer`,
	`grant insert, update, select on projection_checkpoint to console_writer`,
	`grant insert, update, select on bridge_cursor to console_writer`,
	`grant insert, select on bridge_dead_letter to console_writer`,
];

// Timescale forbids populating a continuous aggregate inside a transaction. These steps are
// additive, ordered, and resumable after the atomic schema transition above: retention is installed
// only after archive backfill and a full historical rollup refresh succeed.
const POST_COMMIT_STATEMENTS: readonly string[] = [
	`select add_continuous_aggregate_policy('event_rollup_1m',
	   start_offset => interval '29 days', end_offset => interval '1 minute',
	   schedule_interval => interval '1 minute', if_not_exists => true)`,
	`select remove_retention_policy('events', if_exists => true)`,
	`do $$ begin
	   if not exists (
	     select 1 from timescaledb_information.jobs
	     where proc_schema = 'public' and proc_name = 'console_events_refresh_then_retain'
	   ) then
	     perform add_job('public.console_events_refresh_then_retain', interval '1 day');
	   end if;
	 end $$`,
	`select add_retention_policy('event_archive', interval '370 days', if_not_exists => true)`,
	`select add_retention_policy('event_rollup_1m', interval '370 days', if_not_exists => true)`,
];

export interface MigrateOpts {
	/**
	 * When set, grant LOGIN + this password to console_app (dev/test convenience; prod uses a managed
	 * role).
	 */
	readonly appPassword?: string;
	readonly roPassword?: string;
	readonly writerPassword?: string;
}

async function backfillSemanticDocuments(admin: Sql): Promise<void> {
	await backfillEmissionFingerprints(admin);
	// A pre-L2 registry row may combine several scopes.  Copy its descriptors only when there was
	// exactly one scope; multi-scope legacy rows start conservatively empty and are enriched by new
	// emissions.  Guessing would turn historical aggregate metadata into a cross-scope disclosure.
	await admin`
		insert into semantic_registry_scoped
			(type, scope, first_seen, last_emit, dimensions, measures, joins, emit_count, updated_at)
		select r.type, s.scope, r.first_seen, r.last_emit,
			case when jsonb_array_length(r.scopes) = 1 then r.dimensions else '{}'::jsonb end,
			case when jsonb_array_length(r.scopes) = 1 then r.measures else '{}'::jsonb end,
			case when jsonb_array_length(r.scopes) = 1 then r.joins else '[]'::jsonb end,
			case when jsonb_array_length(r.scopes) = 1 then r.emit_count else 0 end,
			r.updated_at
		from semantic_registry r
		cross join lateral jsonb_array_elements_text(r.scopes) s(scope)
		on conflict (type, scope) do nothing`;
	await admin`delete from semantic_documents where kind = 'statistic'`;
	const statistics = await admin<
		{
			type: string;
			dimensions: Record<string, DimensionDescriptor>;
			measures: Record<string, MeasureDescriptor>;
			joins: JoinDescriptor[];
			scope: string;
		}[]
	>`select type, dimensions, measures, joins, scope from semantic_registry_scoped`;
	for await (const row of asynchronously(statistics)) {
		const content = semanticDocument(row.type, row);
		const embedding = vectorLiteral(embedText(content));
		await admin`
			insert into semantic_documents
				(id, kind, source_ref, content, scopes, embedding, embedding_model)
			values
				(${`stat:${row.type}:${row.scope}`}, 'statistic', ${row.type}, ${content},
				 ${admin.json([row.scope])}, ${embedding}::vector, ${EMBEDDING_MODEL})
			on conflict (id) do update set content = excluded.content, scopes = excluded.scopes,
				embedding = excluded.embedding, embedding_model = excluded.embedding_model,
				updated_at = now()`;
	}
	const views = await admin<
		{ name: string; description: string; fields: Record<string, unknown>; scopes: string[] }[]
	>`select name, description, fields, scopes from semantic_views where enabled`;
	for await (const view of asynchronously(views)) {
		const content = `registered view ${view.name} ${view.description} fields ${JSON.stringify(view.fields)}`;
		const embedding = vectorLiteral(embedText(content));
		await admin`
			insert into semantic_documents
				(id, kind, source_ref, content, scopes, embedding, embedding_model)
			values
				(${`view:${view.name}`}, 'view', ${view.name}, ${content}, ${admin.json(view.scopes)},
				 ${embedding}::vector, ${EMBEDDING_MODEL})
			on conflict (id) do update set content = excluded.content, scopes = excluded.scopes,
				embedding = excluded.embedding, embedding_model = excluded.embedding_model,
				updated_at = now()`;
	}
}

async function backfillEmissionFingerprints(admin: Sql): Promise<void> {
	let afterSeq = "0";
	for await (const iteration of asynchronously(indefinitely())) {
		void iteration;
		const rows = await admin<
			Array<{
				seq: string;
				id: string;
				type: string;
				ts: string;
				source_service: string;
				source_host: string | null;
				source_agent: string | null;
				subject: string;
				subject_kind: Emission["subject_kind"];
				severity: Emission["severity"];
				action: string | null;
				task_id: number | null;
				scope: string;
				dimensions: NonNullable<Emission["dimensions"]>;
				measures: NonNullable<Emission["measures"]>;
				links: NonNullable<Emission["links"]>;
				body_ref: string | null;
				meta: NonNullable<Emission["meta"]>;
			}>
		>`select e.seq, e.id, e.type, e.ts::text as ts, e.source_service, e.source_host,
		         e.source_agent, e.subject, e.subject_kind, e.severity, e.action, e.task_id,
		         e.scope, e.dimensions, e.measures, e.links, e.body_ref, e.meta
		  from events e join emission_ids g using (id)
		  where g.payload_sha256 is null and e.seq > ${afterSeq}::bigint
		  order by e.seq limit 500`;
		if (rows.length === 0) break;
		for await (const row of asynchronously(rows)) {
			const fingerprint = emissionFingerprint({
				schema_version: 1,
				id: row.id,
				type: row.type,
				ts: new Date(row.ts).toISOString(),
				source: { service: row.source_service, host: row.source_host, agent: row.source_agent },
				subject: row.subject,
				subject_kind: row.subject_kind,
				severity: row.severity,
				action: row.action,
				task_id: row.task_id,
				scope: row.scope,
				dimensions: row.dimensions,
				measures: row.measures,
				links: row.links,
				body_ref: row.body_ref,
				meta: row.meta,
			});
			await admin`update emission_ids set payload_sha256 = ${fingerprint}
			  where id = ${row.id} and payload_sha256 is null`;
		}
		afterSeq = rows.at(-1)?.seq ?? afterSeq;
	}
	// Gates older than raw retention cannot be reconstructed. Fail closed on body verification
	// rather than accepting an unverifiable different body as a duplicate success.
	await admin`update emission_ids set payload_sha256 = 'legacy-unverifiable'
	  where payload_sha256 is null`;
}

export async function migrate(admin: Sql, opts?: MigrateOpts): Promise<void> {
	// One atomic schema transition: a failed hypertable conversion cannot strand a populated Phase 1
	// database after its old uniqueness/identity constraints have been removed.
	await admin.begin(async (tx) => {
		// A migration owner may deliberately be NOSUPERUSER/NOBYPASSRLS. Temporarily remove FORCE
		// from the semantic tables when upgrading an existing install, perform the backfill before the
		// RLS segment, then restore FORCE and policies in the same transaction. Any failure rolls the
		// temporary change back.
		await tx.unsafe(`do $$ begin
		  if to_regclass('events') is not null then alter table events no force row level security; end if;
		  if to_regclass('event_archive') is not null then alter table event_archive no force row level security; end if;
		  if to_regclass('semantic_registry') is not null then alter table semantic_registry no force row level security; end if;
		  if to_regclass('semantic_registry_scoped') is not null then alter table semantic_registry_scoped no force row level security; end if;
		  if to_regclass('semantic_views') is not null then alter table semantic_views no force row level security; end if;
		  if to_regclass('semantic_documents') is not null then alter table semantic_documents no force row level security; end if;
		end $$`);
		const rlsStart = DOMAIN_SCHEMA_STATEMENTS.indexOf(
			`alter table current_state enable row level security`,
		);
		if (rlsStart < 0) throw new Error("migration RLS boundary missing");
		for await (const stmt of asynchronously(DOMAIN_SCHEMA_STATEMENTS.slice(0, rlsStart)))
			await tx.unsafe(stmt);
		await backfillSemanticDocuments(txSql(tx));
		for await (const stmt of asynchronously(DOMAIN_SCHEMA_STATEMENTS.slice(rlsStart)))
			await tx.unsafe(stmt);
	});
	const rollupBackfill = await admin<{ done: boolean }[]>`
		select exists(select 1 from schema_migrations where name = 'l1_rollup_backfill') as done`;
	if (!rollupBackfill[0].done) {
		await admin.unsafe(
			`call refresh_continuous_aggregate('event_rollup_1m', null, now() - interval '1 minute')`,
		);
		await admin`
			insert into schema_migrations (name) values ('l1_rollup_backfill') on conflict do nothing`;
	}
	for await (const stmt of asynchronously(POST_COMMIT_STATEMENTS)) await admin.unsafe(stmt);
	if (opts?.appPassword)
		await admin.unsafe(
			`alter role console_app login password '${opts.appPassword.replace(/'/g, "''")}'`,
		);
	if (opts?.roPassword)
		await admin.unsafe(
			`alter role console_ro login password '${opts.roPassword.replace(/'/g, "''")}'`,
		);
	if (opts?.writerPassword)
		await admin.unsafe(
			`alter role console_writer login password '${opts.writerPassword.replace(/'/g, "''")}'`,
		);
}
