name: zizmor

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "37 6 * * 1"

permissions:
  contents: read

jobs:
  zizmor:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
